// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package providers

import (
	"context"
	"time"

	"github.com/gemyago/signal-foundry/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWindowSyncApplyStore creates a new instance of MockWindowSyncApplyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWindowSyncApplyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWindowSyncApplyStore {
	mock := &MockWindowSyncApplyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWindowSyncApplyStore is an autogenerated mock type for the WindowSyncApplyStore type
type MockWindowSyncApplyStore struct {
	mock.Mock
}

type MockWindowSyncApplyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWindowSyncApplyStore) EXPECT() *MockWindowSyncApplyStore_Expecter {
	return &MockWindowSyncApplyStore_Expecter{mock: &_m.Mock}
}

// SaveBalanceSnapshot provides a mock function for the type MockWindowSyncApplyStore
func (_mock *MockWindowSyncApplyStore) SaveBalanceSnapshot(ctx context.Context, snapshot domain.BalanceSnapshot) (domain.BalanceSnapshot, error) {
	ret := _mock.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for SaveBalanceSnapshot")
	}

	var r0 domain.BalanceSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.BalanceSnapshot) (domain.BalanceSnapshot, error)); ok {
		return returnFunc(ctx, snapshot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.BalanceSnapshot) domain.BalanceSnapshot); ok {
		r0 = returnFunc(ctx, snapshot)
	} else {
		r0 = ret.Get(0).(domain.BalanceSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.BalanceSnapshot) error); ok {
		r1 = returnFunc(ctx, snapshot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncApplyStore_SaveBalanceSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBalanceSnapshot'
type MockWindowSyncApplyStore_SaveBalanceSnapshot_Call struct {
	*mock.Call
}

// SaveBalanceSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshot domain.BalanceSnapshot
func (_e *MockWindowSyncApplyStore_Expecter) SaveBalanceSnapshot(ctx interface{}, snapshot interface{}) *MockWindowSyncApplyStore_SaveBalanceSnapshot_Call {
	return &MockWindowSyncApplyStore_SaveBalanceSnapshot_Call{Call: _e.mock.On("SaveBalanceSnapshot", ctx, snapshot)}
}

func (_c *MockWindowSyncApplyStore_SaveBalanceSnapshot_Call) Run(run func(ctx context.Context, snapshot domain.BalanceSnapshot)) *MockWindowSyncApplyStore_SaveBalanceSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.BalanceSnapshot
		if args[1] != nil {
			arg1 = args[1].(domain.BalanceSnapshot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveBalanceSnapshot_Call) Return(balanceSnapshot domain.BalanceSnapshot, err error) *MockWindowSyncApplyStore_SaveBalanceSnapshot_Call {
	_c.Call.Return(balanceSnapshot, err)
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveBalanceSnapshot_Call) RunAndReturn(run func(ctx context.Context, snapshot domain.BalanceSnapshot) (domain.BalanceSnapshot, error)) *MockWindowSyncApplyStore_SaveBalanceSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// SaveConnectionProviderAccount provides a mock function for the type MockWindowSyncApplyStore
func (_mock *MockWindowSyncApplyStore) SaveConnectionProviderAccount(ctx context.Context, account domain.ConnectionProviderAccount) (domain.ConnectionProviderAccount, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for SaveConnectionProviderAccount")
	}

	var r0 domain.ConnectionProviderAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConnectionProviderAccount) (domain.ConnectionProviderAccount, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConnectionProviderAccount) domain.ConnectionProviderAccount); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Get(0).(domain.ConnectionProviderAccount)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ConnectionProviderAccount) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConnectionProviderAccount'
type MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call struct {
	*mock.Call
}

// SaveConnectionProviderAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account domain.ConnectionProviderAccount
func (_e *MockWindowSyncApplyStore_Expecter) SaveConnectionProviderAccount(ctx interface{}, account interface{}) *MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call {
	return &MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call{Call: _e.mock.On("SaveConnectionProviderAccount", ctx, account)}
}

func (_c *MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call) Run(run func(ctx context.Context, account domain.ConnectionProviderAccount)) *MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ConnectionProviderAccount
		if args[1] != nil {
			arg1 = args[1].(domain.ConnectionProviderAccount)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call) Return(connectionProviderAccount domain.ConnectionProviderAccount, err error) *MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call {
	_c.Call.Return(connectionProviderAccount, err)
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call) RunAndReturn(run func(ctx context.Context, account domain.ConnectionProviderAccount) (domain.ConnectionProviderAccount, error)) *MockWindowSyncApplyStore_SaveConnectionProviderAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProviderTransactionMatch provides a mock function for the type MockWindowSyncApplyStore
func (_mock *MockWindowSyncApplyStore) SaveProviderTransactionMatch(ctx context.Context, match domain.ProviderTransactionMatch) (domain.ProviderTransactionMatch, error) {
	ret := _mock.Called(ctx, match)

	if len(ret) == 0 {
		panic("no return value specified for SaveProviderTransactionMatch")
	}

	var r0 domain.ProviderTransactionMatch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProviderTransactionMatch) (domain.ProviderTransactionMatch, error)); ok {
		return returnFunc(ctx, match)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProviderTransactionMatch) domain.ProviderTransactionMatch); ok {
		r0 = returnFunc(ctx, match)
	} else {
		r0 = ret.Get(0).(domain.ProviderTransactionMatch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ProviderTransactionMatch) error); ok {
		r1 = returnFunc(ctx, match)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProviderTransactionMatch'
type MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call struct {
	*mock.Call
}

// SaveProviderTransactionMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - match domain.ProviderTransactionMatch
func (_e *MockWindowSyncApplyStore_Expecter) SaveProviderTransactionMatch(ctx interface{}, match interface{}) *MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call {
	return &MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call{Call: _e.mock.On("SaveProviderTransactionMatch", ctx, match)}
}

func (_c *MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call) Run(run func(ctx context.Context, match domain.ProviderTransactionMatch)) *MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ProviderTransactionMatch
		if args[1] != nil {
			arg1 = args[1].(domain.ProviderTransactionMatch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call) Return(providerTransactionMatch domain.ProviderTransactionMatch, err error) *MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call {
	_c.Call.Return(providerTransactionMatch, err)
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call) RunAndReturn(run func(ctx context.Context, match domain.ProviderTransactionMatch) (domain.ProviderTransactionMatch, error)) *MockWindowSyncApplyStore_SaveProviderTransactionMatch_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRawPayload provides a mock function for the type MockWindowSyncApplyStore
func (_mock *MockWindowSyncApplyStore) SaveRawPayload(ctx context.Context, payload domain.RawPayload) (domain.RawPayload, error) {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveRawPayload")
	}

	var r0 domain.RawPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RawPayload) (domain.RawPayload, error)); ok {
		return returnFunc(ctx, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RawPayload) domain.RawPayload); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Get(0).(domain.RawPayload)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RawPayload) error); ok {
		r1 = returnFunc(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncApplyStore_SaveRawPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRawPayload'
type MockWindowSyncApplyStore_SaveRawPayload_Call struct {
	*mock.Call
}

// SaveRawPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - payload domain.RawPayload
func (_e *MockWindowSyncApplyStore_Expecter) SaveRawPayload(ctx interface{}, payload interface{}) *MockWindowSyncApplyStore_SaveRawPayload_Call {
	return &MockWindowSyncApplyStore_SaveRawPayload_Call{Call: _e.mock.On("SaveRawPayload", ctx, payload)}
}

func (_c *MockWindowSyncApplyStore_SaveRawPayload_Call) Run(run func(ctx context.Context, payload domain.RawPayload)) *MockWindowSyncApplyStore_SaveRawPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RawPayload
		if args[1] != nil {
			arg1 = args[1].(domain.RawPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveRawPayload_Call) Return(rawPayload domain.RawPayload, err error) *MockWindowSyncApplyStore_SaveRawPayload_Call {
	_c.Call.Return(rawPayload, err)
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveRawPayload_Call) RunAndReturn(run func(ctx context.Context, payload domain.RawPayload) (domain.RawPayload, error)) *MockWindowSyncApplyStore_SaveRawPayload_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTransaction provides a mock function for the type MockWindowSyncApplyStore
func (_mock *MockWindowSyncApplyStore) SaveTransaction(ctx context.Context, transaction domain.Transaction) (domain.Transaction, error) {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for SaveTransaction")
	}

	var r0 domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) (domain.Transaction, error)); ok {
		return returnFunc(ctx, transaction)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Transaction) domain.Transaction); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Transaction) error); ok {
		r1 = returnFunc(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncApplyStore_SaveTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTransaction'
type MockWindowSyncApplyStore_SaveTransaction_Call struct {
	*mock.Call
}

// SaveTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction domain.Transaction
func (_e *MockWindowSyncApplyStore_Expecter) SaveTransaction(ctx interface{}, transaction interface{}) *MockWindowSyncApplyStore_SaveTransaction_Call {
	return &MockWindowSyncApplyStore_SaveTransaction_Call{Call: _e.mock.On("SaveTransaction", ctx, transaction)}
}

func (_c *MockWindowSyncApplyStore_SaveTransaction_Call) Run(run func(ctx context.Context, transaction domain.Transaction)) *MockWindowSyncApplyStore_SaveTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveTransaction_Call) Return(transaction1 domain.Transaction, err error) *MockWindowSyncApplyStore_SaveTransaction_Call {
	_c.Call.Return(transaction1, err)
	return _c
}

func (_c *MockWindowSyncApplyStore_SaveTransaction_Call) RunAndReturn(run func(ctx context.Context, transaction domain.Transaction) (domain.Transaction, error)) *MockWindowSyncApplyStore_SaveTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWindowSyncPersistence creates a new instance of MockWindowSyncPersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWindowSyncPersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWindowSyncPersistence {
	mock := &MockWindowSyncPersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWindowSyncPersistence is an autogenerated mock type for the WindowSyncPersistence type
type MockWindowSyncPersistence struct {
	mock.Mock
}

type MockWindowSyncPersistence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWindowSyncPersistence) EXPECT() *MockWindowSyncPersistence_Expecter {
	return &MockWindowSyncPersistence_Expecter{mock: &_m.Mock}
}

// ListConnectionProviderAccounts provides a mock function for the type MockWindowSyncPersistence
func (_mock *MockWindowSyncPersistence) ListConnectionProviderAccounts(ctx context.Context, connectionID string) ([]domain.ConnectionProviderAccount, error) {
	ret := _mock.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for ListConnectionProviderAccounts")
	}

	var r0 []domain.ConnectionProviderAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.ConnectionProviderAccount, error)); ok {
		return returnFunc(ctx, connectionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.ConnectionProviderAccount); ok {
		r0 = returnFunc(ctx, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ConnectionProviderAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, connectionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncPersistence_ListConnectionProviderAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConnectionProviderAccounts'
type MockWindowSyncPersistence_ListConnectionProviderAccounts_Call struct {
	*mock.Call
}

// ListConnectionProviderAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
func (_e *MockWindowSyncPersistence_Expecter) ListConnectionProviderAccounts(ctx interface{}, connectionID interface{}) *MockWindowSyncPersistence_ListConnectionProviderAccounts_Call {
	return &MockWindowSyncPersistence_ListConnectionProviderAccounts_Call{Call: _e.mock.On("ListConnectionProviderAccounts", ctx, connectionID)}
}

func (_c *MockWindowSyncPersistence_ListConnectionProviderAccounts_Call) Run(run func(ctx context.Context, connectionID string)) *MockWindowSyncPersistence_ListConnectionProviderAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowSyncPersistence_ListConnectionProviderAccounts_Call) Return(connectionProviderAccounts []domain.ConnectionProviderAccount, err error) *MockWindowSyncPersistence_ListConnectionProviderAccounts_Call {
	_c.Call.Return(connectionProviderAccounts, err)
	return _c
}

func (_c *MockWindowSyncPersistence_ListConnectionProviderAccounts_Call) RunAndReturn(run func(ctx context.Context, connectionID string) ([]domain.ConnectionProviderAccount, error)) *MockWindowSyncPersistence_ListConnectionProviderAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// ListProviderTransactionMatchesByTransactionIDs provides a mock function for the type MockWindowSyncPersistence
func (_mock *MockWindowSyncPersistence) ListProviderTransactionMatchesByTransactionIDs(ctx context.Context, connectionID string, transactionIDs []string) ([]domain.ProviderTransactionMatch, error) {
	ret := _mock.Called(ctx, connectionID, transactionIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListProviderTransactionMatchesByTransactionIDs")
	}

	var r0 []domain.ProviderTransactionMatch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]domain.ProviderTransactionMatch, error)); ok {
		return returnFunc(ctx, connectionID, transactionIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []domain.ProviderTransactionMatch); ok {
		r0 = returnFunc(ctx, connectionID, transactionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProviderTransactionMatch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, connectionID, transactionIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProviderTransactionMatchesByTransactionIDs'
type MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call struct {
	*mock.Call
}

// ListProviderTransactionMatchesByTransactionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID string
//   - transactionIDs []string
func (_e *MockWindowSyncPersistence_Expecter) ListProviderTransactionMatchesByTransactionIDs(ctx interface{}, connectionID interface{}, transactionIDs interface{}) *MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call {
	return &MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call{Call: _e.mock.On("ListProviderTransactionMatchesByTransactionIDs", ctx, connectionID, transactionIDs)}
}

func (_c *MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call) Run(run func(ctx context.Context, connectionID string, transactionIDs []string)) *MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call) Return(providerTransactionMatchs []domain.ProviderTransactionMatch, err error) *MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call {
	_c.Call.Return(providerTransactionMatchs, err)
	return _c
}

func (_c *MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call) RunAndReturn(run func(ctx context.Context, connectionID string, transactionIDs []string) ([]domain.ProviderTransactionMatch, error)) *MockWindowSyncPersistence_ListProviderTransactionMatchesByTransactionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListProviderTransactionsInWindow provides a mock function for the type MockWindowSyncPersistence
func (_mock *MockWindowSyncPersistence) ListProviderTransactionsInWindow(ctx context.Context, financeAccountIDs []string, window domain.ProviderSyncWindow) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, financeAccountIDs, window)

	if len(ret) == 0 {
		panic("no return value specified for ListProviderTransactionsInWindow")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, domain.ProviderSyncWindow) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, financeAccountIDs, window)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, domain.ProviderSyncWindow) []domain.Transaction); ok {
		r0 = returnFunc(ctx, financeAccountIDs, window)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, domain.ProviderSyncWindow) error); ok {
		r1 = returnFunc(ctx, financeAccountIDs, window)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProviderTransactionsInWindow'
type MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call struct {
	*mock.Call
}

// ListProviderTransactionsInWindow is a helper method to define mock.On call
//   - ctx context.Context
//   - financeAccountIDs []string
//   - window domain.ProviderSyncWindow
func (_e *MockWindowSyncPersistence_Expecter) ListProviderTransactionsInWindow(ctx interface{}, financeAccountIDs interface{}, window interface{}) *MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call {
	return &MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call{Call: _e.mock.On("ListProviderTransactionsInWindow", ctx, financeAccountIDs, window)}
}

func (_c *MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call) Run(run func(ctx context.Context, financeAccountIDs []string, window domain.ProviderSyncWindow)) *MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 domain.ProviderSyncWindow
		if args[2] != nil {
			arg2 = args[2].(domain.ProviderSyncWindow)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call) Return(transactions []domain.Transaction, err error) *MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call) RunAndReturn(run func(ctx context.Context, financeAccountIDs []string, window domain.ProviderSyncWindow) ([]domain.Transaction, error)) *MockWindowSyncPersistence_ListProviderTransactionsInWindow_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockWindowSyncPersistence
func (_mock *MockWindowSyncPersistence) WithTransaction(ctx context.Context, fn func(WindowSyncApplyStore) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(WindowSyncApplyStore) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWindowSyncPersistence_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockWindowSyncPersistence_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(WindowSyncApplyStore) error
func (_e *MockWindowSyncPersistence_Expecter) WithTransaction(ctx interface{}, fn interface{}) *MockWindowSyncPersistence_WithTransaction_Call {
	return &MockWindowSyncPersistence_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *MockWindowSyncPersistence_WithTransaction_Call) Run(run func(ctx context.Context, fn func(WindowSyncApplyStore) error)) *MockWindowSyncPersistence_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(WindowSyncApplyStore) error
		if args[1] != nil {
			arg1 = args[1].(func(WindowSyncApplyStore) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowSyncPersistence_WithTransaction_Call) Return(err error) *MockWindowSyncPersistence_WithTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWindowSyncPersistence_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(WindowSyncApplyStore) error) error) *MockWindowSyncPersistence_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncStateJournal creates a new instance of MockSyncStateJournal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncStateJournal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncStateJournal {
	mock := &MockSyncStateJournal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSyncStateJournal is an autogenerated mock type for the SyncStateJournal type
type MockSyncStateJournal struct {
	mock.Mock
}

type MockSyncStateJournal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncStateJournal) EXPECT() *MockSyncStateJournal_Expecter {
	return &MockSyncStateJournal_Expecter{mock: &_m.Mock}
}

// AppendSyncState provides a mock function for the type MockSyncStateJournal
func (_mock *MockSyncStateJournal) AppendSyncState(ctx context.Context, state domain.ProviderSyncState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for AppendSyncState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProviderSyncState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncStateJournal_AppendSyncState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendSyncState'
type MockSyncStateJournal_AppendSyncState_Call struct {
	*mock.Call
}

// AppendSyncState is a helper method to define mock.On call
//   - ctx context.Context
//   - state domain.ProviderSyncState
func (_e *MockSyncStateJournal_Expecter) AppendSyncState(ctx interface{}, state interface{}) *MockSyncStateJournal_AppendSyncState_Call {
	return &MockSyncStateJournal_AppendSyncState_Call{Call: _e.mock.On("AppendSyncState", ctx, state)}
}

func (_c *MockSyncStateJournal_AppendSyncState_Call) Run(run func(ctx context.Context, state domain.ProviderSyncState)) *MockSyncStateJournal_AppendSyncState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ProviderSyncState
		if args[1] != nil {
			arg1 = args[1].(domain.ProviderSyncState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncStateJournal_AppendSyncState_Call) Return(err error) *MockSyncStateJournal_AppendSyncState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncStateJournal_AppendSyncState_Call) RunAndReturn(run func(ctx context.Context, state domain.ProviderSyncState) error) *MockSyncStateJournal_AppendSyncState_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLastState provides a mock function for the type MockSyncStateJournal
func (_mock *MockSyncStateJournal) LoadLastState(ctx context.Context, connection domain.ProviderConnectionRef) (*domain.ProviderSyncState, error) {
	ret := _mock.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for LoadLastState")
	}

	var r0 *domain.ProviderSyncState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProviderConnectionRef) (*domain.ProviderSyncState, error)); ok {
		return returnFunc(ctx, connection)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProviderConnectionRef) *domain.ProviderSyncState); ok {
		r0 = returnFunc(ctx, connection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProviderSyncState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ProviderConnectionRef) error); ok {
		r1 = returnFunc(ctx, connection)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSyncStateJournal_LoadLastState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLastState'
type MockSyncStateJournal_LoadLastState_Call struct {
	*mock.Call
}

// LoadLastState is a helper method to define mock.On call
//   - ctx context.Context
//   - connection domain.ProviderConnectionRef
func (_e *MockSyncStateJournal_Expecter) LoadLastState(ctx interface{}, connection interface{}) *MockSyncStateJournal_LoadLastState_Call {
	return &MockSyncStateJournal_LoadLastState_Call{Call: _e.mock.On("LoadLastState", ctx, connection)}
}

func (_c *MockSyncStateJournal_LoadLastState_Call) Run(run func(ctx context.Context, connection domain.ProviderConnectionRef)) *MockSyncStateJournal_LoadLastState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ProviderConnectionRef
		if args[1] != nil {
			arg1 = args[1].(domain.ProviderConnectionRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSyncStateJournal_LoadLastState_Call) Return(providerSyncState *domain.ProviderSyncState, err error) *MockSyncStateJournal_LoadLastState_Call {
	_c.Call.Return(providerSyncState, err)
	return _c
}

func (_c *MockSyncStateJournal_LoadLastState_Call) RunAndReturn(run func(ctx context.Context, connection domain.ProviderConnectionRef) (*domain.ProviderSyncState, error)) *MockSyncStateJournal_LoadLastState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTargetWindowPolicy creates a new instance of MockTargetWindowPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargetWindowPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargetWindowPolicy {
	mock := &MockTargetWindowPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTargetWindowPolicy is an autogenerated mock type for the TargetWindowPolicy type
type MockTargetWindowPolicy struct {
	mock.Mock
}

type MockTargetWindowPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargetWindowPolicy) EXPECT() *MockTargetWindowPolicy_Expecter {
	return &MockTargetWindowPolicy_Expecter{mock: &_m.Mock}
}

// Determine provides a mock function for the type MockTargetWindowPolicy
func (_mock *MockTargetWindowPolicy) Determine(now time.Time, state *domain.ProviderSyncState) (domain.ProviderSyncWindow, error) {
	ret := _mock.Called(now, state)

	if len(ret) == 0 {
		panic("no return value specified for Determine")
	}

	var r0 domain.ProviderSyncWindow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, *domain.ProviderSyncState) (domain.ProviderSyncWindow, error)); ok {
		return returnFunc(now, state)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, *domain.ProviderSyncState) domain.ProviderSyncWindow); ok {
		r0 = returnFunc(now, state)
	} else {
		r0 = ret.Get(0).(domain.ProviderSyncWindow)
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, *domain.ProviderSyncState) error); ok {
		r1 = returnFunc(now, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargetWindowPolicy_Determine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Determine'
type MockTargetWindowPolicy_Determine_Call struct {
	*mock.Call
}

// Determine is a helper method to define mock.On call
//   - now time.Time
//   - state *domain.ProviderSyncState
func (_e *MockTargetWindowPolicy_Expecter) Determine(now interface{}, state interface{}) *MockTargetWindowPolicy_Determine_Call {
	return &MockTargetWindowPolicy_Determine_Call{Call: _e.mock.On("Determine", now, state)}
}

func (_c *MockTargetWindowPolicy_Determine_Call) Run(run func(now time.Time, state *domain.ProviderSyncState)) *MockTargetWindowPolicy_Determine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 *domain.ProviderSyncState
		if args[1] != nil {
			arg1 = args[1].(*domain.ProviderSyncState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetWindowPolicy_Determine_Call) Return(providerSyncWindow domain.ProviderSyncWindow, err error) *MockTargetWindowPolicy_Determine_Call {
	_c.Call.Return(providerSyncWindow, err)
	return _c
}

func (_c *MockTargetWindowPolicy_Determine_Call) RunAndReturn(run func(now time.Time, state *domain.ProviderSyncState) (domain.ProviderSyncWindow, error)) *MockTargetWindowPolicy_Determine_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWindowChunkPolicy creates a new instance of MockWindowChunkPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWindowChunkPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWindowChunkPolicy {
	mock := &MockWindowChunkPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWindowChunkPolicy is an autogenerated mock type for the WindowChunkPolicy type
type MockWindowChunkPolicy struct {
	mock.Mock
}

type MockWindowChunkPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWindowChunkPolicy) EXPECT() *MockWindowChunkPolicy_Expecter {
	return &MockWindowChunkPolicy_Expecter{mock: &_m.Mock}
}

// Split provides a mock function for the type MockWindowChunkPolicy
func (_mock *MockWindowChunkPolicy) Split(window domain.ProviderSyncWindow) ([]domain.ProviderSyncWindow, error) {
	ret := _mock.Called(window)

	if len(ret) == 0 {
		panic("no return value specified for Split")
	}

	var r0 []domain.ProviderSyncWindow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.ProviderSyncWindow) ([]domain.ProviderSyncWindow, error)); ok {
		return returnFunc(window)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.ProviderSyncWindow) []domain.ProviderSyncWindow); ok {
		r0 = returnFunc(window)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProviderSyncWindow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.ProviderSyncWindow) error); ok {
		r1 = returnFunc(window)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowChunkPolicy_Split_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Split'
type MockWindowChunkPolicy_Split_Call struct {
	*mock.Call
}

// Split is a helper method to define mock.On call
//   - window domain.ProviderSyncWindow
func (_e *MockWindowChunkPolicy_Expecter) Split(window interface{}) *MockWindowChunkPolicy_Split_Call {
	return &MockWindowChunkPolicy_Split_Call{Call: _e.mock.On("Split", window)}
}

func (_c *MockWindowChunkPolicy_Split_Call) Run(run func(window domain.ProviderSyncWindow)) *MockWindowChunkPolicy_Split_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ProviderSyncWindow
		if args[0] != nil {
			arg0 = args[0].(domain.ProviderSyncWindow)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWindowChunkPolicy_Split_Call) Return(providerSyncWindows []domain.ProviderSyncWindow, err error) *MockWindowChunkPolicy_Split_Call {
	_c.Call.Return(providerSyncWindows, err)
	return _c
}

func (_c *MockWindowChunkPolicy_Split_Call) RunAndReturn(run func(window domain.ProviderSyncWindow) ([]domain.ProviderSyncWindow, error)) *MockWindowChunkPolicy_Split_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWindowExecutor creates a new instance of MockWindowExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWindowExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWindowExecutor {
	mock := &MockWindowExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWindowExecutor is an autogenerated mock type for the WindowExecutor type
type MockWindowExecutor struct {
	mock.Mock
}

type MockWindowExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWindowExecutor) EXPECT() *MockWindowExecutor_Expecter {
	return &MockWindowExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockWindowExecutor
func (_mock *MockWindowExecutor) Execute(ctx context.Context, request WindowSyncRequest) (WindowSyncResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 WindowSyncResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, WindowSyncRequest) (WindowSyncResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, WindowSyncRequest) WindowSyncResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(WindowSyncResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, WindowSyncRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWindowExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockWindowExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - request WindowSyncRequest
func (_e *MockWindowExecutor_Expecter) Execute(ctx interface{}, request interface{}) *MockWindowExecutor_Execute_Call {
	return &MockWindowExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, request)}
}

func (_c *MockWindowExecutor_Execute_Call) Run(run func(ctx context.Context, request WindowSyncRequest)) *MockWindowExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 WindowSyncRequest
		if args[1] != nil {
			arg1 = args[1].(WindowSyncRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWindowExecutor_Execute_Call) Return(windowSyncResult WindowSyncResult, err error) *MockWindowExecutor_Execute_Call {
	_c.Call.Return(windowSyncResult, err)
	return _c
}

func (_c *MockWindowExecutor_Execute_Call) RunAndReturn(run func(ctx context.Context, request WindowSyncRequest) (WindowSyncResult, error)) *MockWindowExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}
