// Code generated by mockery-style fixture; DO NOT EDIT.
// github.com/vektra/mockery

//go:build !release

package providers_test

import (
	"context"

	"github.com/gemyago/sumweave/finance/domain"
	"github.com/gemyago/sumweave/finance/internal/providers"
	mock "github.com/stretchr/testify/mock"
)

func NewMockWindowSyncStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWindowSyncStore {
	mockStore := &MockWindowSyncStore{}
	mockStore.Mock.Test(t)

	t.Cleanup(func() { mockStore.AssertExpectations(t) })

	return mockStore
}

type MockWindowSyncStore struct {
	mock.Mock
}

type MockWindowSyncStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWindowSyncStore) EXPECT() *MockWindowSyncStore_Expecter {
	return &MockWindowSyncStore_Expecter{mock: &_m.Mock}
}

func (_mock *MockWindowSyncStore) LoadExistingWindow(
	ctx context.Context,
	connection domain.ProviderConnectionRef,
	window domain.ProviderSyncWindow,
) (providers.ExistingWindowSnapshot, error) {
	ret := _mock.Called(ctx, connection, window)

	if len(ret) == 0 {
		panic("no return value specified for LoadExistingWindow")
	}

	var r0 providers.ExistingWindowSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProviderConnectionRef, domain.ProviderSyncWindow) (providers.ExistingWindowSnapshot, error)); ok {
		return returnFunc(ctx, connection, window)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProviderConnectionRef, domain.ProviderSyncWindow) providers.ExistingWindowSnapshot); ok {
		r0 = returnFunc(ctx, connection, window)
	} else {
		r0 = ret.Get(0).(providers.ExistingWindowSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ProviderConnectionRef, domain.ProviderSyncWindow) error); ok {
		r1 = returnFunc(ctx, connection, window)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockWindowSyncStore_LoadExistingWindow_Call struct {
	*mock.Call
}

func (_e *MockWindowSyncStore_Expecter) LoadExistingWindow(
	ctx interface{},
	connection interface{},
	window interface{},
) *MockWindowSyncStore_LoadExistingWindow_Call {
	return &MockWindowSyncStore_LoadExistingWindow_Call{Call: _e.mock.On("LoadExistingWindow", ctx, connection, window)}
}

func (_c *MockWindowSyncStore_LoadExistingWindow_Call) Run(
	run func(ctx context.Context, connection domain.ProviderConnectionRef, window domain.ProviderSyncWindow),
) *MockWindowSyncStore_LoadExistingWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ProviderConnectionRef
		if args[1] != nil {
			arg1 = args[1].(domain.ProviderConnectionRef)
		}
		var arg2 domain.ProviderSyncWindow
		if args[2] != nil {
			arg2 = args[2].(domain.ProviderSyncWindow)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockWindowSyncStore_LoadExistingWindow_Call) Return(
	snapshot providers.ExistingWindowSnapshot,
	err error,
) *MockWindowSyncStore_LoadExistingWindow_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockWindowSyncStore_LoadExistingWindow_Call) RunAndReturn(
	run func(context.Context, domain.ProviderConnectionRef, domain.ProviderSyncWindow) (providers.ExistingWindowSnapshot, error),
) *MockWindowSyncStore_LoadExistingWindow_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockWindowSyncStore) ApplySync(
	ctx context.Context,
	diffPlan providers.ProviderDiffPlan,
	applyPlan providers.ApplyPlan,
	successStates ...domain.ProviderSyncState,
) (domain.ProviderSyncStats, error) {
	ca := make([]interface{}, 0, 3+len(successStates))
	ca = append(ca, ctx, diffPlan, applyPlan)
	for _, successState := range successStates {
		ca = append(ca, successState)
	}
	ret := _mock.Called(ca...)

	if len(ret) == 0 {
		panic("no return value specified for ApplySync")
	}

	var r0 domain.ProviderSyncStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, providers.ProviderDiffPlan, providers.ApplyPlan, ...domain.ProviderSyncState) (domain.ProviderSyncStats, error)); ok {
		return returnFunc(ctx, diffPlan, applyPlan, successStates...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, providers.ProviderDiffPlan, providers.ApplyPlan, ...domain.ProviderSyncState) domain.ProviderSyncStats); ok {
		r0 = returnFunc(ctx, diffPlan, applyPlan, successStates...)
	} else {
		r0 = ret.Get(0).(domain.ProviderSyncStats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, providers.ProviderDiffPlan, providers.ApplyPlan, ...domain.ProviderSyncState) error); ok {
		r1 = returnFunc(ctx, diffPlan, applyPlan, successStates...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockWindowSyncStore_ApplySync_Call struct {
	*mock.Call
}

func (_e *MockWindowSyncStore_Expecter) ApplySync(
	ctx interface{},
	diffPlan interface{},
	applyPlan interface{},
	successStates ...interface{},
) *MockWindowSyncStore_ApplySync_Call {
	ca := make([]interface{}, 0, 3+len(successStates))
	ca = append(ca, ctx, diffPlan, applyPlan)
	ca = append(ca, successStates...)
	return &MockWindowSyncStore_ApplySync_Call{Call: _e.mock.On("ApplySync", ca...)}
}

func (_c *MockWindowSyncStore_ApplySync_Call) Run(
	run func(ctx context.Context, diffPlan providers.ProviderDiffPlan, applyPlan providers.ApplyPlan, successStates ...domain.ProviderSyncState),
) *MockWindowSyncStore_ApplySync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 providers.ProviderDiffPlan
		if args[1] != nil {
			arg1 = args[1].(providers.ProviderDiffPlan)
		}
		var arg2 providers.ApplyPlan
		if args[2] != nil {
			arg2 = args[2].(providers.ApplyPlan)
		}
		successStates := make([]domain.ProviderSyncState, 0, len(args)-3)
		for index := 3; index < len(args); index++ {
			if args[index] != nil {
				successStates = append(successStates, args[index].(domain.ProviderSyncState))
			}
		}
		run(arg0, arg1, arg2, successStates...)
	})
	return _c
}

func (_c *MockWindowSyncStore_ApplySync_Call) Return(
	stats domain.ProviderSyncStats,
	err error,
) *MockWindowSyncStore_ApplySync_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockWindowSyncStore_ApplySync_Call) RunAndReturn(
	run func(context.Context, providers.ProviderDiffPlan, providers.ApplyPlan, ...domain.ProviderSyncState) (domain.ProviderSyncStats, error),
) *MockWindowSyncStore_ApplySync_Call {
	_c.Call.Return(run)
	return _c
}
