// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package financeapp

import (
	"context"
	"database/sql"

	"github.com/gemyago/sumweave/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBankSyncWindowCompletionPublisher creates a new instance of MockBankSyncWindowCompletionPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankSyncWindowCompletionPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankSyncWindowCompletionPublisher {
	mock := &MockBankSyncWindowCompletionPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBankSyncWindowCompletionPublisher is an autogenerated mock type for the BankSyncWindowCompletionPublisher type
type MockBankSyncWindowCompletionPublisher struct {
	mock.Mock
}

type MockBankSyncWindowCompletionPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankSyncWindowCompletionPublisher) EXPECT() *MockBankSyncWindowCompletionPublisher_Expecter {
	return &MockBankSyncWindowCompletionPublisher_Expecter{mock: &_m.Mock}
}

// PublishBankSyncWindowCompleted provides a mock function for the type MockBankSyncWindowCompletionPublisher
func (_mock *MockBankSyncWindowCompletionPublisher) PublishBankSyncWindowCompleted(context1 context.Context, tx *sql.Tx, bankSyncWindowCompleted domain.BankSyncWindowCompleted) error {
	ret := _mock.Called(context1, tx, bankSyncWindowCompleted)

	if len(ret) == 0 {
		panic("no return value specified for PublishBankSyncWindowCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, domain.BankSyncWindowCompleted) error); ok {
		r0 = returnFunc(context1, tx, bankSyncWindowCompleted)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBankSyncWindowCompleted'
type MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call struct {
	*mock.Call
}

// PublishBankSyncWindowCompleted is a helper method to define mock.On call
//   - context1 context.Context
//   - tx *sql.Tx
//   - bankSyncWindowCompleted domain.BankSyncWindowCompleted
func (_e *MockBankSyncWindowCompletionPublisher_Expecter) PublishBankSyncWindowCompleted(context1 interface{}, tx interface{}, bankSyncWindowCompleted interface{}) *MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call {
	return &MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call{Call: _e.mock.On("PublishBankSyncWindowCompleted", context1, tx, bankSyncWindowCompleted)}
}

func (_c *MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call) Run(run func(context1 context.Context, tx *sql.Tx, bankSyncWindowCompleted domain.BankSyncWindowCompleted)) *MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 domain.BankSyncWindowCompleted
		if args[2] != nil {
			arg2 = args[2].(domain.BankSyncWindowCompleted)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call) Return(err error) *MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call) RunAndReturn(run func(context1 context.Context, tx *sql.Tx, bankSyncWindowCompleted domain.BankSyncWindowCompleted) error) *MockBankSyncWindowCompletionPublisher_PublishBankSyncWindowCompleted_Call {
	_c.Call.Return(run)
	return _c
}
