// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package financeapp

import (
	"context"
	"database/sql"

	"github.com/gemyago/sumweave/apps/sumweave/internal/appdispatch"
	"github.com/gemyago/sumweave/finance"
	mock "github.com/stretchr/testify/mock"
)

// newMockfxRefreshJobService creates a new instance of mockfxRefreshJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfxRefreshJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfxRefreshJobService {
	mock := &mockfxRefreshJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfxRefreshJobService is an autogenerated mock type for the fxRefreshJobService type
type mockfxRefreshJobService struct {
	mock.Mock
}

type mockfxRefreshJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfxRefreshJobService) EXPECT() *mockfxRefreshJobService_Expecter {
	return &mockfxRefreshJobService_Expecter{mock: &_m.Mock}
}

// RefreshRequiredFXRates provides a mock function for the type mockfxRefreshJobService
func (_mock *mockfxRefreshJobService) RefreshRequiredFXRates(context1 context.Context, refreshFXRatesParams finance.RefreshFXRatesParams) (finance.RefreshFXRatesResult, error) {
	ret := _mock.Called(context1, refreshFXRatesParams)

	if len(ret) == 0 {
		panic("no return value specified for RefreshRequiredFXRates")
	}

	var r0 finance.RefreshFXRatesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RefreshFXRatesParams) (finance.RefreshFXRatesResult, error)); ok {
		return returnFunc(context1, refreshFXRatesParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RefreshFXRatesParams) finance.RefreshFXRatesResult); ok {
		r0 = returnFunc(context1, refreshFXRatesParams)
	} else {
		r0 = ret.Get(0).(finance.RefreshFXRatesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.RefreshFXRatesParams) error); ok {
		r1 = returnFunc(context1, refreshFXRatesParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfxRefreshJobService_RefreshRequiredFXRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshRequiredFXRates'
type mockfxRefreshJobService_RefreshRequiredFXRates_Call struct {
	*mock.Call
}

// RefreshRequiredFXRates is a helper method to define mock.On call
//   - context1 context.Context
//   - refreshFXRatesParams finance.RefreshFXRatesParams
func (_e *mockfxRefreshJobService_Expecter) RefreshRequiredFXRates(context1 any, refreshFXRatesParams any) *mockfxRefreshJobService_RefreshRequiredFXRates_Call {
	return &mockfxRefreshJobService_RefreshRequiredFXRates_Call{Call: _e.mock.On("RefreshRequiredFXRates", context1, refreshFXRatesParams)}
}

func (_c *mockfxRefreshJobService_RefreshRequiredFXRates_Call) Run(run func(context1 context.Context, refreshFXRatesParams finance.RefreshFXRatesParams)) *mockfxRefreshJobService_RefreshRequiredFXRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.RefreshFXRatesParams
		if args[1] != nil {
			arg1 = args[1].(finance.RefreshFXRatesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfxRefreshJobService_RefreshRequiredFXRates_Call) Return(refreshFXRatesResult finance.RefreshFXRatesResult, err error) *mockfxRefreshJobService_RefreshRequiredFXRates_Call {
	_c.Call.Return(refreshFXRatesResult, err)
	return _c
}

func (_c *mockfxRefreshJobService_RefreshRequiredFXRates_Call) RunAndReturn(run func(context1 context.Context, refreshFXRatesParams finance.RefreshFXRatesParams) (finance.RefreshFXRatesResult, error)) *mockfxRefreshJobService_RefreshRequiredFXRates_Call {
	_c.Call.Return(run)
	return _c
}

// newMockcsvImportJobService creates a new instance of mockcsvImportJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcsvImportJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcsvImportJobService {
	mock := &mockcsvImportJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcsvImportJobService is an autogenerated mock type for the csvImportJobService type
type mockcsvImportJobService struct {
	mock.Mock
}

type mockcsvImportJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcsvImportJobService) EXPECT() *mockcsvImportJobService_Expecter {
	return &mockcsvImportJobService_Expecter{mock: &_m.Mock}
}

// RunCSVImportJob provides a mock function for the type mockcsvImportJobService
func (_mock *mockcsvImportJobService) RunCSVImportJob(context1 context.Context, runCSVImportJobParams finance.RunCSVImportJobParams) (finance.CSVImportRunResult, error) {
	ret := _mock.Called(context1, runCSVImportJobParams)

	if len(ret) == 0 {
		panic("no return value specified for RunCSVImportJob")
	}

	var r0 finance.CSVImportRunResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RunCSVImportJobParams) (finance.CSVImportRunResult, error)); ok {
		return returnFunc(context1, runCSVImportJobParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RunCSVImportJobParams) finance.CSVImportRunResult); ok {
		r0 = returnFunc(context1, runCSVImportJobParams)
	} else {
		r0 = ret.Get(0).(finance.CSVImportRunResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.RunCSVImportJobParams) error); ok {
		r1 = returnFunc(context1, runCSVImportJobParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcsvImportJobService_RunCSVImportJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCSVImportJob'
type mockcsvImportJobService_RunCSVImportJob_Call struct {
	*mock.Call
}

// RunCSVImportJob is a helper method to define mock.On call
//   - context1 context.Context
//   - runCSVImportJobParams finance.RunCSVImportJobParams
func (_e *mockcsvImportJobService_Expecter) RunCSVImportJob(context1 any, runCSVImportJobParams any) *mockcsvImportJobService_RunCSVImportJob_Call {
	return &mockcsvImportJobService_RunCSVImportJob_Call{Call: _e.mock.On("RunCSVImportJob", context1, runCSVImportJobParams)}
}

func (_c *mockcsvImportJobService_RunCSVImportJob_Call) Run(run func(context1 context.Context, runCSVImportJobParams finance.RunCSVImportJobParams)) *mockcsvImportJobService_RunCSVImportJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.RunCSVImportJobParams
		if args[1] != nil {
			arg1 = args[1].(finance.RunCSVImportJobParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcsvImportJobService_RunCSVImportJob_Call) Return(cSVImportRunResult finance.CSVImportRunResult, err error) *mockcsvImportJobService_RunCSVImportJob_Call {
	_c.Call.Return(cSVImportRunResult, err)
	return _c
}

func (_c *mockcsvImportJobService_RunCSVImportJob_Call) RunAndReturn(run func(context1 context.Context, runCSVImportJobParams finance.RunCSVImportJobParams) (finance.CSVImportRunResult, error)) *mockcsvImportJobService_RunCSVImportJob_Call {
	_c.Call.Return(run)
	return _c
}

// newMockbankSyncJobService creates a new instance of mockbankSyncJobService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbankSyncJobService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbankSyncJobService {
	mock := &mockbankSyncJobService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbankSyncJobService is an autogenerated mock type for the bankSyncJobService type
type mockbankSyncJobService struct {
	mock.Mock
}

type mockbankSyncJobService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbankSyncJobService) EXPECT() *mockbankSyncJobService_Expecter {
	return &mockbankSyncJobService_Expecter{mock: &_m.Mock}
}

// RunBankConnectionSync provides a mock function for the type mockbankSyncJobService
func (_mock *mockbankSyncJobService) RunBankConnectionSync(context1 context.Context, runBankConnectionSyncParams finance.RunBankConnectionSyncParams) (finance.BankConnectionSyncResult, error) {
	ret := _mock.Called(context1, runBankConnectionSyncParams)

	if len(ret) == 0 {
		panic("no return value specified for RunBankConnectionSync")
	}

	var r0 finance.BankConnectionSyncResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RunBankConnectionSyncParams) (finance.BankConnectionSyncResult, error)); ok {
		return returnFunc(context1, runBankConnectionSyncParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RunBankConnectionSyncParams) finance.BankConnectionSyncResult); ok {
		r0 = returnFunc(context1, runBankConnectionSyncParams)
	} else {
		r0 = ret.Get(0).(finance.BankConnectionSyncResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.RunBankConnectionSyncParams) error); ok {
		r1 = returnFunc(context1, runBankConnectionSyncParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockbankSyncJobService_RunBankConnectionSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunBankConnectionSync'
type mockbankSyncJobService_RunBankConnectionSync_Call struct {
	*mock.Call
}

// RunBankConnectionSync is a helper method to define mock.On call
//   - context1 context.Context
//   - runBankConnectionSyncParams finance.RunBankConnectionSyncParams
func (_e *mockbankSyncJobService_Expecter) RunBankConnectionSync(context1 any, runBankConnectionSyncParams any) *mockbankSyncJobService_RunBankConnectionSync_Call {
	return &mockbankSyncJobService_RunBankConnectionSync_Call{Call: _e.mock.On("RunBankConnectionSync", context1, runBankConnectionSyncParams)}
}

func (_c *mockbankSyncJobService_RunBankConnectionSync_Call) Run(run func(context1 context.Context, runBankConnectionSyncParams finance.RunBankConnectionSyncParams)) *mockbankSyncJobService_RunBankConnectionSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.RunBankConnectionSyncParams
		if args[1] != nil {
			arg1 = args[1].(finance.RunBankConnectionSyncParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbankSyncJobService_RunBankConnectionSync_Call) Return(bankConnectionSyncResult finance.BankConnectionSyncResult, err error) *mockbankSyncJobService_RunBankConnectionSync_Call {
	_c.Call.Return(bankConnectionSyncResult, err)
	return _c
}

func (_c *mockbankSyncJobService_RunBankConnectionSync_Call) RunAndReturn(run func(context1 context.Context, runBankConnectionSyncParams finance.RunBankConnectionSyncParams) (finance.BankConnectionSyncResult, error)) *mockbankSyncJobService_RunBankConnectionSync_Call {
	_c.Call.Return(run)
	return _c
}

// newMockappdispatchPublisher creates a new instance of mockappdispatchPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockappdispatchPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockappdispatchPublisher {
	mock := &mockappdispatchPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockappdispatchPublisher is an autogenerated mock type for the appdispatchPublisher type
type mockappdispatchPublisher struct {
	mock.Mock
}

type mockappdispatchPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockappdispatchPublisher) EXPECT() *mockappdispatchPublisher_Expecter {
	return &mockappdispatchPublisher_Expecter{mock: &_m.Mock}
}

// PublishRequest provides a mock function for the type mockappdispatchPublisher
func (_mock *mockappdispatchPublisher) PublishRequest(context1 context.Context, publicationRequest appdispatch.PublicationRequest) (appdispatch.PublicationReference, error) {
	ret := _mock.Called(context1, publicationRequest)

	if len(ret) == 0 {
		panic("no return value specified for PublishRequest")
	}

	var r0 appdispatch.PublicationReference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, appdispatch.PublicationRequest) (appdispatch.PublicationReference, error)); ok {
		return returnFunc(context1, publicationRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, appdispatch.PublicationRequest) appdispatch.PublicationReference); ok {
		r0 = returnFunc(context1, publicationRequest)
	} else {
		r0 = ret.Get(0).(appdispatch.PublicationReference)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, appdispatch.PublicationRequest) error); ok {
		r1 = returnFunc(context1, publicationRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockappdispatchPublisher_PublishRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishRequest'
type mockappdispatchPublisher_PublishRequest_Call struct {
	*mock.Call
}

// PublishRequest is a helper method to define mock.On call
//   - context1 context.Context
//   - publicationRequest appdispatch.PublicationRequest
func (_e *mockappdispatchPublisher_Expecter) PublishRequest(context1 any, publicationRequest any) *mockappdispatchPublisher_PublishRequest_Call {
	return &mockappdispatchPublisher_PublishRequest_Call{Call: _e.mock.On("PublishRequest", context1, publicationRequest)}
}

func (_c *mockappdispatchPublisher_PublishRequest_Call) Run(run func(context1 context.Context, publicationRequest appdispatch.PublicationRequest)) *mockappdispatchPublisher_PublishRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 appdispatch.PublicationRequest
		if args[1] != nil {
			arg1 = args[1].(appdispatch.PublicationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockappdispatchPublisher_PublishRequest_Call) Return(publicationReference appdispatch.PublicationReference, err error) *mockappdispatchPublisher_PublishRequest_Call {
	_c.Call.Return(publicationReference, err)
	return _c
}

func (_c *mockappdispatchPublisher_PublishRequest_Call) RunAndReturn(run func(context1 context.Context, publicationRequest appdispatch.PublicationRequest) (appdispatch.PublicationReference, error)) *mockappdispatchPublisher_PublishRequest_Call {
	_c.Call.Return(run)
	return _c
}

// PublishRequestInTx provides a mock function for the type mockappdispatchPublisher
func (_mock *mockappdispatchPublisher) PublishRequestInTx(context1 context.Context, tx *sql.Tx, publicationRequest appdispatch.PublicationRequest) (appdispatch.PublicationReference, error) {
	ret := _mock.Called(context1, tx, publicationRequest)

	if len(ret) == 0 {
		panic("no return value specified for PublishRequestInTx")
	}

	var r0 appdispatch.PublicationReference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, appdispatch.PublicationRequest) (appdispatch.PublicationReference, error)); ok {
		return returnFunc(context1, tx, publicationRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, appdispatch.PublicationRequest) appdispatch.PublicationReference); ok {
		r0 = returnFunc(context1, tx, publicationRequest)
	} else {
		r0 = ret.Get(0).(appdispatch.PublicationReference)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, appdispatch.PublicationRequest) error); ok {
		r1 = returnFunc(context1, tx, publicationRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockappdispatchPublisher_PublishRequestInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishRequestInTx'
type mockappdispatchPublisher_PublishRequestInTx_Call struct {
	*mock.Call
}

// PublishRequestInTx is a helper method to define mock.On call
//   - context1 context.Context
//   - tx *sql.Tx
//   - publicationRequest appdispatch.PublicationRequest
func (_e *mockappdispatchPublisher_Expecter) PublishRequestInTx(context1 any, tx any, publicationRequest any) *mockappdispatchPublisher_PublishRequestInTx_Call {
	return &mockappdispatchPublisher_PublishRequestInTx_Call{Call: _e.mock.On("PublishRequestInTx", context1, tx, publicationRequest)}
}

func (_c *mockappdispatchPublisher_PublishRequestInTx_Call) Run(run func(context1 context.Context, tx *sql.Tx, publicationRequest appdispatch.PublicationRequest)) *mockappdispatchPublisher_PublishRequestInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 appdispatch.PublicationRequest
		if args[2] != nil {
			arg2 = args[2].(appdispatch.PublicationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockappdispatchPublisher_PublishRequestInTx_Call) Return(publicationReference appdispatch.PublicationReference, err error) *mockappdispatchPublisher_PublishRequestInTx_Call {
	_c.Call.Return(publicationReference, err)
	return _c
}

func (_c *mockappdispatchPublisher_PublishRequestInTx_Call) RunAndReturn(run func(context1 context.Context, tx *sql.Tx, publicationRequest appdispatch.PublicationRequest) (appdispatch.PublicationReference, error)) *mockappdispatchPublisher_PublishRequestInTx_Call {
	_c.Call.Return(run)
	return _c
}
