// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package middleware

import (
	"context"

	"github.com/gemyago/sumweave/apps/sumweave/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// newMockjwtValidator creates a new instance of mockjwtValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjwtValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjwtValidator {
	mock := &mockjwtValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjwtValidator is an autogenerated mock type for the jwtValidator type
type mockjwtValidator struct {
	mock.Mock
}

type mockjwtValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjwtValidator) EXPECT() *mockjwtValidator_Expecter {
	return &mockjwtValidator_Expecter{mock: &_m.Mock}
}

// ValidateAccessToken provides a mock function for the type mockjwtValidator
func (_mock *mockjwtValidator) ValidateAccessToken(tokenStr string) (*auth.JWTClaims, error) {
	ret := _mock.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *auth.JWTClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.JWTClaims, error)); ok {
		return returnFunc(tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.JWTClaims); ok {
		r0 = returnFunc(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.JWTClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjwtValidator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type mockjwtValidator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *mockjwtValidator_Expecter) ValidateAccessToken(tokenStr interface{}) *mockjwtValidator_ValidateAccessToken_Call {
	return &mockjwtValidator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenStr)}
}

func (_c *mockjwtValidator_ValidateAccessToken_Call) Run(run func(tokenStr string)) *mockjwtValidator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjwtValidator_ValidateAccessToken_Call) Return(jWTClaims *auth.JWTClaims, err error) *mockjwtValidator_ValidateAccessToken_Call {
	_c.Call.Return(jWTClaims, err)
	return _c
}

func (_c *mockjwtValidator_ValidateAccessToken_Call) RunAndReturn(run func(tokenStr string) (*auth.JWTClaims, error)) *mockjwtValidator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// newMockaccessTokenValidator creates a new instance of mockaccessTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockaccessTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockaccessTokenValidator {
	mock := &mockaccessTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockaccessTokenValidator is an autogenerated mock type for the accessTokenValidator type
type mockaccessTokenValidator struct {
	mock.Mock
}

type mockaccessTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockaccessTokenValidator) EXPECT() *mockaccessTokenValidator_Expecter {
	return &mockaccessTokenValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type mockaccessTokenValidator
func (_mock *mockaccessTokenValidator) Validate(context1 context.Context, s string) (*auth.ValidatedAccessToken, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *auth.ValidatedAccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.ValidatedAccessToken, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.ValidatedAccessToken); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.ValidatedAccessToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockaccessTokenValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type mockaccessTokenValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *mockaccessTokenValidator_Expecter) Validate(context1 interface{}, s interface{}) *mockaccessTokenValidator_Validate_Call {
	return &mockaccessTokenValidator_Validate_Call{Call: _e.mock.On("Validate", context1, s)}
}

func (_c *mockaccessTokenValidator_Validate_Call) Run(run func(context1 context.Context, s string)) *mockaccessTokenValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockaccessTokenValidator_Validate_Call) Return(validatedAccessToken *auth.ValidatedAccessToken, err error) *mockaccessTokenValidator_Validate_Call {
	_c.Call.Return(validatedAccessToken, err)
	return _c
}

func (_c *mockaccessTokenValidator_Validate_Call) RunAndReturn(run func(context1 context.Context, s string) (*auth.ValidatedAccessToken, error)) *mockaccessTokenValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
