#!/usr/bin/env bash
# Generate OpenCode sub-agents from .agents/prompts/openspec-manager.yaml.
# Usage: .agents/prompts/sync-opencode-agents.sh [path-to-yaml]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG="${1:-$SCRIPT_DIR/openspec-manager.yaml}"
AGENTS_DIR="$REPO_ROOT/.opencode/agents"

if [[ ! -f "$CONFIG" ]]; then
  echo "error: config not found: $CONFIG" >&2
  exit 1
fi

mkdir -p "$AGENTS_DIR"

mapfile -t written < <(python3 - "$CONFIG" "$AGENTS_DIR" <<'PY'
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("error: PyYAML is required (pip install pyyaml)")

config_path = Path(sys.argv[1])
agents_dir = Path(sys.argv[2])

ROLE_META = {
    "planning": {
        "name": "OpenSpec Planning",
        "description": "OpenSpec manager sub-agent (role: planning). Run openspec propose for new work or planning redos.",
        "prompt": "You are the OpenSpec planning sub-agent. Follow the Planning sub-agent handoff in `.agents/prompts/openspec-manager.md`.",
    },
    "plan-reviewing": {
        "name": "OpenSpec Plan Review",
        "description": "OpenSpec manager sub-agent (role: plan-reviewing). Review proposals, chunk work, and gate planning commits.",
        "prompt": "You are the OpenSpec plan-reviewing sub-agent. Follow the Plan-reviewing sub-agent handoff in `.agents/prompts/openspec-manager.md`.",
    },
    "implementation": {
        "name": "OpenSpec Implementation",
        "description": "OpenSpec manager sub-agent (role: implementation). Apply one implementation chunk with openspec apply.",
        "prompt": "You are the OpenSpec implementation sub-agent. Follow the Implementation sub-agent handoff in `.agents/prompts/openspec-manager.md`.",
    },
    "chunk-finalizing": {
        "name": "OpenSpec Chunk Finalize",
        "description": "OpenSpec manager sub-agent (role: chunk-finalizing). Shallow review, cleanup, and commit one implemented chunk.",
        "prompt": "You are the OpenSpec chunk-finalizing sub-agent. Follow the Chunk-finalizing sub-agent handoff in `.agents/prompts/openspec-manager.md`.",
    },
    "implementation-finalizing": {
        "name": "OpenSpec Final Review",
        "description": "OpenSpec manager sub-agent (role: implementation-finalizing). Whole-change final review and commit gate.",
        "prompt": "You are the OpenSpec implementation-finalizing sub-agent. Follow the Implementation-finalizing sub-agent handoff in `.agents/prompts/openspec-manager.md`.",
    },
    "comments-addressing": {
        "name": "OpenSpec Comments",
        "description": "OpenSpec manager sub-agent (role: comments-addressing). Address user review comments via openspec apply.",
        "prompt": "You are the OpenSpec comments-addressing sub-agent. Follow the Comments-addressing sub-agent handoff in `.agents/prompts/openspec-manager.md`.",
    },
}

with config_path.open(encoding="utf-8") as f:
    config = yaml.safe_load(f) or {}

sub_agents = config.get("sub-agents") or config.get("sub_agents")
if not isinstance(sub_agents, dict) or not sub_agents:
    sys.exit(f"error: no sub-agents found in {config_path}")

written = []
for role, settings in sub_agents.items():
    if not isinstance(settings, dict):
        sys.exit(f"error: sub-agents.{role} must be a mapping")

    agent_id = settings.get("sub_agent_name")
    if not agent_id:
        sys.exit(f"error: sub-agents.{role}.sub_agent_name is required")

    model = settings.get("model")
    if not model:
        sys.exit(f"error: sub-agents.{role}.model is required")

    reasoning = settings.get("reasoning_effort") or settings.get("reasoningEffort")
    if not reasoning:
        sys.exit(f"error: sub-agents.{role}.reasoning_effort is required")

    meta = ROLE_META.get(role, {})
    name = meta.get("name", agent_id.replace("-", " ").title())
    description = meta.get(
        "description",
        f"OpenSpec manager sub-agent (role: {role}).",
    )
    prompt = meta.get(
        "prompt",
        f"You are the OpenSpec `{role}` sub-agent. Follow `.agents/prompts/openspec-manager.md`.",
    )

    lines = [
        "---",
        f"name: {name}",
        f"description: {description}",
        "mode: subagent",
        f"model: {model}",
        f"reasoningEffort: {reasoning}",
        "---",
        "",
        f"<!-- openspec-role: {role}; openspec-agent: {agent_id} -->",
        "<!-- Generated by .agents/prompts/sync-opencode-agents.sh; edit openspec-manager.yaml and re-run. -->",
        "",
        prompt,
        "",
        "Read `.agents/prompts/openspec-manager.md` for workflow rules, artifact paths, and the exact handoff template for this phase.",
        "",
    ]

    out_path = agents_dir / f"{agent_id}.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    written.append(out_path)

for path in sorted(written):
    print(path)
PY
)

echo "Synced ${#written[@]} OpenCode agents into $AGENTS_DIR"
for path in "${written[@]}"; do
  echo "  $path"
done
