// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package jobs

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/gemyago/signal-foundry/apps/signal-foundry/internal/appdispatch"
	mock "github.com/stretchr/testify/mock"
)

// newMockdispatchPublisher creates a new instance of mockdispatchPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdispatchPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdispatchPublisher {
	mock := &mockdispatchPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdispatchPublisher is an autogenerated mock type for the dispatchPublisher type
type mockdispatchPublisher struct {
	mock.Mock
}

type mockdispatchPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdispatchPublisher) EXPECT() *mockdispatchPublisher_Expecter {
	return &mockdispatchPublisher_Expecter{mock: &_m.Mock}
}

// PublishInTx provides a mock function for the type mockdispatchPublisher
func (_mock *mockdispatchPublisher) PublishInTx(context1 context.Context, tx *sql.Tx, envelope appdispatch.Envelope) error {
	ret := _mock.Called(context1, tx, envelope)

	if len(ret) == 0 {
		panic("no return value specified for PublishInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, appdispatch.Envelope) error); ok {
		r0 = returnFunc(context1, tx, envelope)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdispatchPublisher_PublishInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishInTx'
type mockdispatchPublisher_PublishInTx_Call struct {
	*mock.Call
}

// PublishInTx is a helper method to define mock.On call
//   - context1 context.Context
//   - tx *sql.Tx
//   - envelope appdispatch.Envelope
func (_e *mockdispatchPublisher_Expecter) PublishInTx(context1 any, tx any, envelope any) *mockdispatchPublisher_PublishInTx_Call {
	return &mockdispatchPublisher_PublishInTx_Call{Call: _e.mock.On("PublishInTx", context1, tx, envelope)}
}

func (_c *mockdispatchPublisher_PublishInTx_Call) Run(run func(context1 context.Context, tx *sql.Tx, envelope appdispatch.Envelope)) *mockdispatchPublisher_PublishInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 appdispatch.Envelope
		if args[2] != nil {
			arg2 = args[2].(appdispatch.Envelope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockdispatchPublisher_PublishInTx_Call) Return(err error) *mockdispatchPublisher_PublishInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdispatchPublisher_PublishInTx_Call) RunAndReturn(run func(context1 context.Context, tx *sql.Tx, envelope appdispatch.Envelope) error) *mockdispatchPublisher_PublishInTx_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkerStore creates a new instance of mockworkerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerStore {
	mock := &mockworkerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkerStore is an autogenerated mock type for the workerStore type
type mockworkerStore struct {
	mock.Mock
}

type mockworkerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerStore) EXPECT() *mockworkerStore_Expecter {
	return &mockworkerStore_Expecter{mock: &_m.Mock}
}

// ClaimQueued provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) ClaimQueued(context1 context.Context, s string, s1 string, time1 time.Time) (*Job, error) {
	ret := _mock.Called(context1, s, s1, time1)

	if len(ret) == 0 {
		panic("no return value specified for ClaimQueued")
	}

	var r0 *Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*Job, error)); ok {
		return returnFunc(context1, s, s1, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *Job); ok {
		r0 = returnFunc(context1, s, s1, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(context1, s, s1, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerStore_ClaimQueued_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimQueued'
type mockworkerStore_ClaimQueued_Call struct {
	*mock.Call
}

// ClaimQueued is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) ClaimQueued(context1 any, s any, s1 any, time1 any) *mockworkerStore_ClaimQueued_Call {
	return &mockworkerStore_ClaimQueued_Call{Call: _e.mock.On("ClaimQueued", context1, s, s1, time1)}
}

func (_c *mockworkerStore_ClaimQueued_Call) Run(run func(context1 context.Context, s string, s1 string, time1 time.Time)) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_ClaimQueued_Call) Return(job *Job, err error) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *mockworkerStore_ClaimQueued_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, time1 time.Time) (*Job, error)) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) Get(context1 context.Context, s string) (*Job, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Job, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Job); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockworkerStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *mockworkerStore_Expecter) Get(context1 any, s any) *mockworkerStore_Get_Call {
	return &mockworkerStore_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *mockworkerStore_Get_Call) Run(run func(context1 context.Context, s string)) *mockworkerStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkerStore_Get_Call) Return(job *Job, err error) *mockworkerStore_Get_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *mockworkerStore_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (*Job, error)) *mockworkerStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) MarkFailed(context1 context.Context, s string, s1 string, jobError *JobError, time1 time.Time) error {
	ret := _mock.Called(context1, s, s1, jobError, time1)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *JobError, time.Time) error); ok {
		r0 = returnFunc(context1, s, s1, jobError, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type mockworkerStore_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - jobError *JobError
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) MarkFailed(context1 any, s any, s1 any, jobError any, time1 any) *mockworkerStore_MarkFailed_Call {
	return &mockworkerStore_MarkFailed_Call{Call: _e.mock.On("MarkFailed", context1, s, s1, jobError, time1)}
}

func (_c *mockworkerStore_MarkFailed_Call) Run(run func(context1 context.Context, s string, s1 string, jobError *JobError, time1 time.Time)) *mockworkerStore_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *JobError
		if args[3] != nil {
			arg3 = args[3].(*JobError)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockworkerStore_MarkFailed_Call) Return(err error) *mockworkerStore_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_MarkFailed_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, jobError *JobError, time1 time.Time) error) *mockworkerStore_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSucceeded provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) MarkSucceeded(context1 context.Context, s string, s1 string, v any, time1 time.Time) error {
	ret := _mock.Called(context1, s, s1, v, time1)

	if len(ret) == 0 {
		panic("no return value specified for MarkSucceeded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any, time.Time) error); ok {
		r0 = returnFunc(context1, s, s1, v, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_MarkSucceeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSucceeded'
type mockworkerStore_MarkSucceeded_Call struct {
	*mock.Call
}

// MarkSucceeded is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - v any
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) MarkSucceeded(context1 any, s any, s1 any, v any, time1 any) *mockworkerStore_MarkSucceeded_Call {
	return &mockworkerStore_MarkSucceeded_Call{Call: _e.mock.On("MarkSucceeded", context1, s, s1, v, time1)}
}

func (_c *mockworkerStore_MarkSucceeded_Call) Run(run func(context1 context.Context, s string, s1 string, v any, time1 time.Time)) *mockworkerStore_MarkSucceeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockworkerStore_MarkSucceeded_Call) Return(err error) *mockworkerStore_MarkSucceeded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_MarkSucceeded_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, v any, time1 time.Time) error) *mockworkerStore_MarkSucceeded_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverStaleRunning provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) RecoverStaleRunning(context1 context.Context, time1 time.Time, n int) error {
	ret := _mock.Called(context1, time1, n)

	if len(ret) == 0 {
		panic("no return value specified for RecoverStaleRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) error); ok {
		r0 = returnFunc(context1, time1, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_RecoverStaleRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverStaleRunning'
type mockworkerStore_RecoverStaleRunning_Call struct {
	*mock.Call
}

// RecoverStaleRunning is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 time.Time
//   - n int
func (_e *mockworkerStore_Expecter) RecoverStaleRunning(context1 any, time1 any, n any) *mockworkerStore_RecoverStaleRunning_Call {
	return &mockworkerStore_RecoverStaleRunning_Call{Call: _e.mock.On("RecoverStaleRunning", context1, time1, n)}
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) Run(run func(context1 context.Context, time1 time.Time, n int)) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) Return(err error) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) RunAndReturn(run func(context1 context.Context, time1 time.Time, n int) error) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProgress provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) UpdateProgress(context1 context.Context, s string, rawMessage json.RawMessage, time1 time.Time) error {
	ret := _mock.Called(context1, s, rawMessage, time1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, time.Time) error); ok {
		r0 = returnFunc(context1, s, rawMessage, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_UpdateProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProgress'
type mockworkerStore_UpdateProgress_Call struct {
	*mock.Call
}

// UpdateProgress is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - rawMessage json.RawMessage
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) UpdateProgress(context1 any, s any, rawMessage any, time1 any) *mockworkerStore_UpdateProgress_Call {
	return &mockworkerStore_UpdateProgress_Call{Call: _e.mock.On("UpdateProgress", context1, s, rawMessage, time1)}
}

func (_c *mockworkerStore_UpdateProgress_Call) Run(run func(context1 context.Context, s string, rawMessage json.RawMessage, time1 time.Time)) *mockworkerStore_UpdateProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_UpdateProgress_Call) Return(err error) *mockworkerStore_UpdateProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_UpdateProgress_Call) RunAndReturn(run func(context1 context.Context, s string, rawMessage json.RawMessage, time1 time.Time) error) *mockworkerStore_UpdateProgress_Call {
	_c.Call.Return(run)
	return _c
}
