dir: '{{.InterfaceDirRelative}}'
template: testify
template-data:
  mock-build-tags: '!release'
  unroll-variadic: true

packages:
  net/http:
    interfaces:
      RoundTripper:
        config:
          dir: internal/infrastructure/httpclient/
          pkgname: httpclient
  log/slog:
    interfaces:
      Handler:
        config:
          dir: internal/telemetry/
          pkgname: telemetry
          filename: mock_slog_handler_test.go
          structname: MockSlogHandler
  github.com/gemyago/signal-foundry/apps/signal-foundry/internal/auth:
    interfaces:
      userStore:
      jwtService:
      refreshTokenStore:
      passwordHasher:
  github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/middleware:
    interfaces:
      jwtValidator:
  github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1controllers:
    interfaces:
      AuthenticatingService:
      bankConnectionService:
      financeService:
      transferDetailService:
      jobsService:
      userDirectory:
  github.com/gemyago/signal-foundry/apps/signal-foundry/internal/app:
    interfaces:
      AuthUserLookup:
