// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() AuthLoginRequest

type paramsParserAuthAuthLogin struct {
	bindPayload requestParamBinder[*http.Request, *AuthLoginRequest]
}

func (p *paramsParserAuthAuthLogin) parse(router httpRouter, req *http.Request) (*AuthLoginParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &AuthLoginParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserAuthAuthLogin(rootHandler *RootHandler) paramsParser[*AuthLoginParams] {
	return &paramsParserAuthAuthLogin{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *AuthLoginRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*AuthLoginRequest],
			),
			validateValue: NewAuthLoginRequestValidator(),
		}),
	}
}

type paramsParserAuthAuthRefresh struct {
	bindPayload requestParamBinder[*http.Request, *AuthRefreshRequest]
}

func (p *paramsParserAuthAuthRefresh) parse(router httpRouter, req *http.Request) (*AuthRefreshParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &AuthRefreshParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserAuthAuthRefresh(rootHandler *RootHandler) paramsParser[*AuthRefreshParams] {
	return &paramsParserAuthAuthRefresh{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *AuthRefreshRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*AuthRefreshRequest],
			),
			validateValue: NewAuthRefreshRequestValidator(),
		}),
	}
}

type authControllerBuilder struct {
	// POST /api/v1/auth/login
	//
	// Request type: AuthLoginParams,
	//
	// Response type: AuthSessionResponse
	AuthLogin genericHandlerBuilder[
		*AuthLoginParams,
		*AuthSessionResponse,
		handlerActionFunc[*AuthLoginParams, *AuthSessionResponse],
		httpHandlerActionFunc[*AuthLoginParams, *AuthSessionResponse],
	]

	// GET /api/v1/auth/me
	//
	// Request type: none
	//
	// Response type: UserInfo
	AuthMe genericHandlerBuilder[
		void,
		*UserInfo,
		handlerActionFuncNoParams[void, *UserInfo],
		httpHandlerActionFuncNoParams[void, *UserInfo],
	]

	// POST /api/v1/auth/refresh
	//
	// Request type: AuthRefreshParams,
	//
	// Response type: AuthSessionResponse
	AuthRefresh genericHandlerBuilder[
		*AuthRefreshParams,
		*AuthSessionResponse,
		handlerActionFunc[*AuthRefreshParams, *AuthSessionResponse],
		httpHandlerActionFunc[*AuthRefreshParams, *AuthSessionResponse],
	]
}

func newAuthControllerBuilder(app *RootHandler) *authControllerBuilder {
	return &authControllerBuilder{
		// POST /api/v1/auth/login
		AuthLogin: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*AuthLoginParams,
				*AuthSessionResponse,
			](),
			newHTTPHandlerAdapter[
				*AuthLoginParams,
				*AuthSessionResponse,
			](),
			makeActionBuilderParams[
				*AuthLoginParams,
				*AuthSessionResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserAuthAuthLogin(app),
			},
		),

		// GET /api/v1/auth/me
		AuthMe: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoParams[
				void,
				*UserInfo,
			](),
			newHTTPHandlerAdapterNoParams[
				void,
				*UserInfo,
			](),
			makeActionBuilderParams[
				void,
				*UserInfo,
			]{
				defaultStatus: 200,
				paramsParser:  makeVoidParamsParser(app),
			},
		),

		// POST /api/v1/auth/refresh
		AuthRefresh: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*AuthRefreshParams,
				*AuthSessionResponse,
			](),
			newHTTPHandlerAdapter[
				*AuthRefreshParams,
				*AuthSessionResponse,
			](),
			makeActionBuilderParams[
				*AuthRefreshParams,
				*AuthSessionResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserAuthAuthRefresh(app),
			},
		),
	}
}
