// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"

	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports if that happens.
type _ func() AuthLoginRequest

type AuthController interface {
	// POST /api/v1/auth/login
	//
	// Request type: AuthLoginParams,
	//
	// Response type: AuthSessionResponse
	AuthLogin(HandlerBuilder[
		*AuthLoginParams,
		*AuthSessionResponse,
	]) http.Handler

	// GET /api/v1/auth/me
	//
	// Request type: none
	//
	// Response type: UserInfo
	AuthMe(NoParamsHandlerBuilder[
		*UserInfo,
	]) http.Handler

	// POST /api/v1/auth/refresh
	//
	// Request type: AuthRefreshParams,
	//
	// Response type: AuthSessionResponse
	AuthRefresh(HandlerBuilder[
		*AuthRefreshParams,
		*AuthSessionResponse,
	]) http.Handler
}

// RegisterAuthRoutes will attach the following routes to the root handler:
// 
// - POST /api/v1/auth/login
// 
// - GET /api/v1/auth/me
// 
// - POST /api/v1/auth/refresh
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterAuthRoutes(controller AuthController) *RootHandler {
	builder := newAuthControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("POST", "/api/v1/auth/login", controller.AuthLogin(builder.AuthLogin))
	rootHandler.router.HandleRoute("GET", "/api/v1/auth/me", controller.AuthMe(builder.AuthMe))
	rootHandler.router.HandleRoute("POST", "/api/v1/auth/refresh", controller.AuthRefresh(builder.AuthRefresh))
	return rootHandler
}