// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"

	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports if that happens.
type _ func() CandleAvailabilityListResponse

type DataController interface {
	// GET /api/v1/data/raw-payloads/{id}
	//
	// Request type: GetDataRawPayloadParams,
	//
	// Response type: RawPayloadDetailResponse
	GetDataRawPayload(HandlerBuilder[
		*GetDataRawPayloadParams,
		*RawPayloadDetailResponse,
	]) http.Handler

	// GET /api/v1/data/candle-availability
	//
	// Request type: ListDataCandleAvailabilityParams,
	//
	// Response type: CandleAvailabilityListResponse
	ListDataCandleAvailability(HandlerBuilder[
		*ListDataCandleAvailabilityParams,
		*CandleAvailabilityListResponse,
	]) http.Handler

	// GET /api/v1/data/candle-raw-payloads
	//
	// Request type: ListDataCandleRawPayloadsParams,
	//
	// Response type: CandleRawPayloadMetadataListResponse
	ListDataCandleRawPayloads(HandlerBuilder[
		*ListDataCandleRawPayloadsParams,
		*CandleRawPayloadMetadataListResponse,
	]) http.Handler

	// GET /api/v1/data/candles
	//
	// Request type: ListDataCandlesParams,
	//
	// Response type: DataCandleListResponse
	ListDataCandles(HandlerBuilder[
		*ListDataCandlesParams,
		*DataCandleListResponse,
	]) http.Handler

	// GET /api/v1/data/raw-payloads
	//
	// Request type: ListDataRawPayloadsParams,
	//
	// Response type: RawPayloadMetadataListResponse
	ListDataRawPayloads(HandlerBuilder[
		*ListDataRawPayloadsParams,
		*RawPayloadMetadataListResponse,
	]) http.Handler
}

// RegisterDataRoutes will attach the following routes to the root handler:
// 
// - GET /api/v1/data/raw-payloads/{id}
// 
// - GET /api/v1/data/candle-availability
// 
// - GET /api/v1/data/candle-raw-payloads
// 
// - GET /api/v1/data/candles
// 
// - GET /api/v1/data/raw-payloads
// 
// Routes will use provided controller to handle requests.
func(rootHandler *RootHandler) RegisterDataRoutes(controller DataController) *RootHandler {
	builder := newDataControllerBuilder(rootHandler)
	rootHandler.router.HandleRoute("GET", "/api/v1/data/raw-payloads/{id}", controller.GetDataRawPayload(builder.GetDataRawPayload))
	rootHandler.router.HandleRoute("GET", "/api/v1/data/candle-availability", controller.ListDataCandleAvailability(builder.ListDataCandleAvailability))
	rootHandler.router.HandleRoute("GET", "/api/v1/data/candle-raw-payloads", controller.ListDataCandleRawPayloads(builder.ListDataCandleRawPayloads))
	rootHandler.router.HandleRoute("GET", "/api/v1/data/candles", controller.ListDataCandles(builder.ListDataCandles))
	rootHandler.router.HandleRoute("GET", "/api/v1/data/raw-payloads", controller.ListDataRawPayloads(builder.ListDataRawPayloads))
	return rootHandler
}