// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() CandleRawPayloadMetadataListResponse

type paramsParserDataGetDataRawPayload struct {
	bindID requestParamBinder[string, string]
}

func (p *paramsParserDataGetDataRawPayload) parse(router httpRouter, req *http.Request) (*GetDataRawPayloadParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &GetDataRawPayloadParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindID(pathParamsCtx.Fork("id"), readPathValue("id", router, req), &reqParams.ID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserDataGetDataRawPayload(rootHandler *RootHandler) paramsParser[*GetDataRawPayloadParams] {
	return &paramsParserDataGetDataRawPayload{
		bindID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserDataListDataCandleRawPayloads struct {
	bindVenue requestParamBinder[[]string, string]
	bindSymbol requestParamBinder[[]string, string]
	bindAssetClass requestParamBinder[[]string, string]
	bindTimeframe requestParamBinder[[]string, string]
	bindStart requestParamBinder[[]string, time.Time]
	bindEnd requestParamBinder[[]string, time.Time]
	bindProvenanceSource requestParamBinder[[]string, string]
	bindProvenanceIDentity requestParamBinder[[]string, string]
}

func (p *paramsParserDataListDataCandleRawPayloads) parse(router httpRouter, req *http.Request) (*ListDataCandleRawPayloadsParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &ListDataCandleRawPayloadsParams{}
	// query params
	query := req.URL.Query()
	queryParamsCtx := bindingCtx.Fork("query")
	p.bindVenue(queryParamsCtx.Fork("venue"), readQueryValue("venue", query), &reqParams.Venue)
	p.bindSymbol(queryParamsCtx.Fork("symbol"), readQueryValue("symbol", query), &reqParams.Symbol)
	p.bindAssetClass(queryParamsCtx.Fork("assetClass"), readQueryValue("assetClass", query), &reqParams.AssetClass)
	p.bindTimeframe(queryParamsCtx.Fork("timeframe"), readQueryValue("timeframe", query), &reqParams.Timeframe)
	p.bindStart(queryParamsCtx.Fork("start"), readQueryValue("start", query), &reqParams.Start)
	p.bindEnd(queryParamsCtx.Fork("end"), readQueryValue("end", query), &reqParams.End)
	p.bindProvenanceSource(queryParamsCtx.Fork("provenanceSource"), readQueryValue("provenanceSource", query), &reqParams.ProvenanceSource)
	p.bindProvenanceIDentity(queryParamsCtx.Fork("provenanceIdentity"), readQueryValue("provenanceIdentity", query), &reqParams.ProvenanceIDentity)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserDataListDataCandleRawPayloads(rootHandler *RootHandler) paramsParser[*ListDataCandleRawPayloadsParams] {
	return &paramsParserDataListDataCandleRawPayloads{
		bindVenue: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindSymbol: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindAssetClass: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindTimeframe: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindStart: newRequestParamBinder(binderParams[[]string, time.Time]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.timeParser,
			),
			validateValue: NewSimpleFieldValidator[time.Time](
			),
		}),
		bindEnd: newRequestParamBinder(binderParams[[]string, time.Time]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.timeParser,
			),
			validateValue: NewSimpleFieldValidator[time.Time](
			),
		}),
		bindProvenanceSource: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindProvenanceIDentity: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserDataListDataCandles struct {
	bindVenue requestParamBinder[[]string, string]
	bindSymbol requestParamBinder[[]string, string]
	bindAssetClass requestParamBinder[[]string, string]
	bindTimeframe requestParamBinder[[]string, string]
	bindStart requestParamBinder[[]string, time.Time]
	bindEnd requestParamBinder[[]string, time.Time]
}

func (p *paramsParserDataListDataCandles) parse(router httpRouter, req *http.Request) (*ListDataCandlesParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &ListDataCandlesParams{}
	// query params
	query := req.URL.Query()
	queryParamsCtx := bindingCtx.Fork("query")
	p.bindVenue(queryParamsCtx.Fork("venue"), readQueryValue("venue", query), &reqParams.Venue)
	p.bindSymbol(queryParamsCtx.Fork("symbol"), readQueryValue("symbol", query), &reqParams.Symbol)
	p.bindAssetClass(queryParamsCtx.Fork("assetClass"), readQueryValue("assetClass", query), &reqParams.AssetClass)
	p.bindTimeframe(queryParamsCtx.Fork("timeframe"), readQueryValue("timeframe", query), &reqParams.Timeframe)
	p.bindStart(queryParamsCtx.Fork("start"), readQueryValue("start", query), &reqParams.Start)
	p.bindEnd(queryParamsCtx.Fork("end"), readQueryValue("end", query), &reqParams.End)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserDataListDataCandles(rootHandler *RootHandler) paramsParser[*ListDataCandlesParams] {
	return &paramsParserDataListDataCandles{
		bindVenue: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindSymbol: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindAssetClass: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindTimeframe: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindStart: newRequestParamBinder(binderParams[[]string, time.Time]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.timeParser,
			),
			validateValue: NewSimpleFieldValidator[time.Time](
			),
		}),
		bindEnd: newRequestParamBinder(binderParams[[]string, time.Time]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.timeParser,
			),
			validateValue: NewSimpleFieldValidator[time.Time](
			),
		}),
	}
}

type paramsParserDataListDataRawPayloads struct {
	bindVenue requestParamBinder[[]string, string]
	bindSymbol requestParamBinder[[]string, string]
	bindAssetClass requestParamBinder[[]string, string]
	bindTimeframe requestParamBinder[[]string, string]
	bindStart requestParamBinder[[]string, time.Time]
	bindEnd requestParamBinder[[]string, time.Time]
	bindIngestionRunID requestParamBinder[[]string, string]
	bindEntityHint requestParamBinder[[]string, string]
	bindEndpoint requestParamBinder[[]string, string]
	bindRequestType requestParamBinder[[]string, string]
	bindLimit requestParamBinder[[]string, int64]
	bindCursor requestParamBinder[[]string, string]
}

func (p *paramsParserDataListDataRawPayloads) parse(router httpRouter, req *http.Request) (*ListDataRawPayloadsParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &ListDataRawPayloadsParams{}
	// query params
	query := req.URL.Query()
	queryParamsCtx := bindingCtx.Fork("query")
	p.bindVenue(queryParamsCtx.Fork("venue"), readQueryValue("venue", query), &reqParams.Venue)
	p.bindSymbol(queryParamsCtx.Fork("symbol"), readQueryValue("symbol", query), &reqParams.Symbol)
	p.bindAssetClass(queryParamsCtx.Fork("assetClass"), readQueryValue("assetClass", query), &reqParams.AssetClass)
	p.bindTimeframe(queryParamsCtx.Fork("timeframe"), readQueryValue("timeframe", query), &reqParams.Timeframe)
	p.bindStart(queryParamsCtx.Fork("start"), readQueryValue("start", query), &reqParams.Start)
	p.bindEnd(queryParamsCtx.Fork("end"), readQueryValue("end", query), &reqParams.End)
	p.bindIngestionRunID(queryParamsCtx.Fork("ingestionRunId"), readQueryValue("ingestionRunId", query), &reqParams.IngestionRunID)
	p.bindEntityHint(queryParamsCtx.Fork("entityHint"), readQueryValue("entityHint", query), &reqParams.EntityHint)
	p.bindEndpoint(queryParamsCtx.Fork("endpoint"), readQueryValue("endpoint", query), &reqParams.Endpoint)
	p.bindRequestType(queryParamsCtx.Fork("requestType"), readQueryValue("requestType", query), &reqParams.RequestType)
	p.bindLimit(queryParamsCtx.Fork("limit"), readQueryValue("limit", query), &reqParams.Limit)
	p.bindCursor(queryParamsCtx.Fork("cursor"), readQueryValue("cursor", query), &reqParams.Cursor)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserDataListDataRawPayloads(rootHandler *RootHandler) paramsParser[*ListDataRawPayloadsParams] {
	return &paramsParserDataListDataRawPayloads{
		bindVenue: newRequestParamBinder(binderParams[[]string, string]{
			required: true,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindSymbol: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindAssetClass: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindTimeframe: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindStart: newRequestParamBinder(binderParams[[]string, time.Time]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.timeParser,
			),
			validateValue: NewSimpleFieldValidator[time.Time](
			),
		}),
		bindEnd: newRequestParamBinder(binderParams[[]string, time.Time]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.timeParser,
			),
			validateValue: NewSimpleFieldValidator[time.Time](
			),
		}),
		bindIngestionRunID: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindEntityHint: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindEndpoint: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindRequestType: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindLimit: newRequestParamBinder(binderParams[[]string, int64]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.int64Parser,
			),
			validateValue: NewSimpleFieldValidator[int64](
			),
		}),
		bindCursor: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type dataControllerBuilder struct {
	// GET /api/v1/data/raw-payloads/{id}
	//
	// Request type: GetDataRawPayloadParams,
	//
	// Response type: RawPayloadDetailResponse
	GetDataRawPayload genericHandlerBuilder[
		*GetDataRawPayloadParams,
		*RawPayloadDetailResponse,
		handlerActionFunc[*GetDataRawPayloadParams, *RawPayloadDetailResponse],
		httpHandlerActionFunc[*GetDataRawPayloadParams, *RawPayloadDetailResponse],
	]

	// GET /api/v1/data/candle-raw-payloads
	//
	// Request type: ListDataCandleRawPayloadsParams,
	//
	// Response type: CandleRawPayloadMetadataListResponse
	ListDataCandleRawPayloads genericHandlerBuilder[
		*ListDataCandleRawPayloadsParams,
		*CandleRawPayloadMetadataListResponse,
		handlerActionFunc[*ListDataCandleRawPayloadsParams, *CandleRawPayloadMetadataListResponse],
		httpHandlerActionFunc[*ListDataCandleRawPayloadsParams, *CandleRawPayloadMetadataListResponse],
	]

	// GET /api/v1/data/candles
	//
	// Request type: ListDataCandlesParams,
	//
	// Response type: DataCandleListResponse
	ListDataCandles genericHandlerBuilder[
		*ListDataCandlesParams,
		*DataCandleListResponse,
		handlerActionFunc[*ListDataCandlesParams, *DataCandleListResponse],
		httpHandlerActionFunc[*ListDataCandlesParams, *DataCandleListResponse],
	]

	// GET /api/v1/data/raw-payloads
	//
	// Request type: ListDataRawPayloadsParams,
	//
	// Response type: RawPayloadMetadataListResponse
	ListDataRawPayloads genericHandlerBuilder[
		*ListDataRawPayloadsParams,
		*RawPayloadMetadataListResponse,
		handlerActionFunc[*ListDataRawPayloadsParams, *RawPayloadMetadataListResponse],
		httpHandlerActionFunc[*ListDataRawPayloadsParams, *RawPayloadMetadataListResponse],
	]
}

func newDataControllerBuilder(app *RootHandler) *dataControllerBuilder {
	return &dataControllerBuilder{
		// GET /api/v1/data/raw-payloads/{id}
		GetDataRawPayload: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*GetDataRawPayloadParams,
				*RawPayloadDetailResponse,
			](),
			newHTTPHandlerAdapter[
				*GetDataRawPayloadParams,
				*RawPayloadDetailResponse,
			](),
			makeActionBuilderParams[
				*GetDataRawPayloadParams,
				*RawPayloadDetailResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserDataGetDataRawPayload(app),
			},
		),

		// GET /api/v1/data/candle-raw-payloads
		ListDataCandleRawPayloads: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*ListDataCandleRawPayloadsParams,
				*CandleRawPayloadMetadataListResponse,
			](),
			newHTTPHandlerAdapter[
				*ListDataCandleRawPayloadsParams,
				*CandleRawPayloadMetadataListResponse,
			](),
			makeActionBuilderParams[
				*ListDataCandleRawPayloadsParams,
				*CandleRawPayloadMetadataListResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserDataListDataCandleRawPayloads(app),
			},
		),

		// GET /api/v1/data/candles
		ListDataCandles: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*ListDataCandlesParams,
				*DataCandleListResponse,
			](),
			newHTTPHandlerAdapter[
				*ListDataCandlesParams,
				*DataCandleListResponse,
			](),
			makeActionBuilderParams[
				*ListDataCandlesParams,
				*DataCandleListResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserDataListDataCandles(app),
			},
		),

		// GET /api/v1/data/raw-payloads
		ListDataRawPayloads: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*ListDataRawPayloadsParams,
				*RawPayloadMetadataListResponse,
			](),
			newHTTPHandlerAdapter[
				*ListDataRawPayloadsParams,
				*RawPayloadMetadataListResponse,
			](),
			makeActionBuilderParams[
				*ListDataRawPayloadsParams,
				*RawPayloadMetadataListResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserDataListDataRawPayloads(app),
			},
		),
	}
}
