// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() CreateEvaluationRequest

type paramsParserEvaluationsCreateEvaluationBacktest struct {
	bindPayload requestParamBinder[*http.Request, *CreateEvaluationRequest]
}

func (p *paramsParserEvaluationsCreateEvaluationBacktest) parse(router httpRouter, req *http.Request) (*CreateEvaluationBacktestParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &CreateEvaluationBacktestParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserEvaluationsCreateEvaluationBacktest(rootHandler *RootHandler) paramsParser[*CreateEvaluationBacktestParams] {
	return &paramsParserEvaluationsCreateEvaluationBacktest{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *CreateEvaluationRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*CreateEvaluationRequest],
			),
			validateValue: NewCreateEvaluationRequestValidator(),
		}),
	}
}

type paramsParserEvaluationsGetEvaluationBacktest struct {
	bindRunID requestParamBinder[string, string]
}

func (p *paramsParserEvaluationsGetEvaluationBacktest) parse(router httpRouter, req *http.Request) (*GetEvaluationBacktestParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &GetEvaluationBacktestParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindRunID(pathParamsCtx.Fork("runId"), readPathValue("runId", router, req), &reqParams.RunID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserEvaluationsGetEvaluationBacktest(rootHandler *RootHandler) paramsParser[*GetEvaluationBacktestParams] {
	return &paramsParserEvaluationsGetEvaluationBacktest{
		bindRunID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserEvaluationsGetEvaluationBacktestEvidence struct {
	bindRunID requestParamBinder[string, string]
}

func (p *paramsParserEvaluationsGetEvaluationBacktestEvidence) parse(router httpRouter, req *http.Request) (*GetEvaluationBacktestEvidenceParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &GetEvaluationBacktestEvidenceParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindRunID(pathParamsCtx.Fork("runId"), readPathValue("runId", router, req), &reqParams.RunID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserEvaluationsGetEvaluationBacktestEvidence(rootHandler *RootHandler) paramsParser[*GetEvaluationBacktestEvidenceParams] {
	return &paramsParserEvaluationsGetEvaluationBacktestEvidence{
		bindRunID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserEvaluationsGetEvaluationBacktestReport struct {
	bindRunID requestParamBinder[string, string]
}

func (p *paramsParserEvaluationsGetEvaluationBacktestReport) parse(router httpRouter, req *http.Request) (*GetEvaluationBacktestReportParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &GetEvaluationBacktestReportParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindRunID(pathParamsCtx.Fork("runId"), readPathValue("runId", router, req), &reqParams.RunID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserEvaluationsGetEvaluationBacktestReport(rootHandler *RootHandler) paramsParser[*GetEvaluationBacktestReportParams] {
	return &paramsParserEvaluationsGetEvaluationBacktestReport{
		bindRunID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserEvaluationsListEvaluationBacktests struct {
	bindStrategyID requestParamBinder[[]string, string]
	bindStatus requestParamBinder[[]string, string]
}

func (p *paramsParserEvaluationsListEvaluationBacktests) parse(router httpRouter, req *http.Request) (*ListEvaluationBacktestsParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &ListEvaluationBacktestsParams{}
	// query params
	query := req.URL.Query()
	queryParamsCtx := bindingCtx.Fork("query")
	p.bindStrategyID(queryParamsCtx.Fork("strategyId"), readQueryValue("strategyId", query), &reqParams.StrategyID)
	p.bindStatus(queryParamsCtx.Fork("status"), readQueryValue("status", query), &reqParams.Status)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserEvaluationsListEvaluationBacktests(rootHandler *RootHandler) paramsParser[*ListEvaluationBacktestsParams] {
	return &paramsParserEvaluationsListEvaluationBacktests{
		bindStrategyID: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindStatus: newRequestParamBinder(binderParams[[]string, string]{
			required: false,
			parseValue: parseMultiValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type evaluationsControllerBuilder struct {
	// POST /api/v1/evaluations/backtests
	//
	// Request type: CreateEvaluationBacktestParams,
	//
	// Response type: EvaluationDetail
	CreateEvaluationBacktest genericHandlerBuilder[
		*CreateEvaluationBacktestParams,
		*EvaluationDetail,
		handlerActionFunc[*CreateEvaluationBacktestParams, *EvaluationDetail],
		httpHandlerActionFunc[*CreateEvaluationBacktestParams, *EvaluationDetail],
	]

	// GET /api/v1/evaluations/backtests/{runId}
	//
	// Request type: GetEvaluationBacktestParams,
	//
	// Response type: EvaluationDetail
	GetEvaluationBacktest genericHandlerBuilder[
		*GetEvaluationBacktestParams,
		*EvaluationDetail,
		handlerActionFunc[*GetEvaluationBacktestParams, *EvaluationDetail],
		httpHandlerActionFunc[*GetEvaluationBacktestParams, *EvaluationDetail],
	]

	// GET /api/v1/evaluations/backtests/{runId}/evidence
	//
	// Request type: GetEvaluationBacktestEvidenceParams,
	//
	// Response type: EvaluationEvidence
	GetEvaluationBacktestEvidence genericHandlerBuilder[
		*GetEvaluationBacktestEvidenceParams,
		*EvaluationEvidence,
		handlerActionFunc[*GetEvaluationBacktestEvidenceParams, *EvaluationEvidence],
		httpHandlerActionFunc[*GetEvaluationBacktestEvidenceParams, *EvaluationEvidence],
	]

	// GET /api/v1/evaluations/backtests/{runId}/report
	//
	// Request type: GetEvaluationBacktestReportParams,
	//
	// Response type: EvaluationReport
	GetEvaluationBacktestReport genericHandlerBuilder[
		*GetEvaluationBacktestReportParams,
		*EvaluationReport,
		handlerActionFunc[*GetEvaluationBacktestReportParams, *EvaluationReport],
		httpHandlerActionFunc[*GetEvaluationBacktestReportParams, *EvaluationReport],
	]

	// GET /api/v1/evaluations/backtests
	//
	// Request type: ListEvaluationBacktestsParams,
	//
	// Response type: EvaluationListResponse
	ListEvaluationBacktests genericHandlerBuilder[
		*ListEvaluationBacktestsParams,
		*EvaluationListResponse,
		handlerActionFunc[*ListEvaluationBacktestsParams, *EvaluationListResponse],
		httpHandlerActionFunc[*ListEvaluationBacktestsParams, *EvaluationListResponse],
	]
}

func newEvaluationsControllerBuilder(app *RootHandler) *evaluationsControllerBuilder {
	return &evaluationsControllerBuilder{
		// POST /api/v1/evaluations/backtests
		CreateEvaluationBacktest: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*CreateEvaluationBacktestParams,
				*EvaluationDetail,
			](),
			newHTTPHandlerAdapter[
				*CreateEvaluationBacktestParams,
				*EvaluationDetail,
			](),
			makeActionBuilderParams[
				*CreateEvaluationBacktestParams,
				*EvaluationDetail,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserEvaluationsCreateEvaluationBacktest(app),
			},
		),

		// GET /api/v1/evaluations/backtests/{runId}
		GetEvaluationBacktest: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*GetEvaluationBacktestParams,
				*EvaluationDetail,
			](),
			newHTTPHandlerAdapter[
				*GetEvaluationBacktestParams,
				*EvaluationDetail,
			](),
			makeActionBuilderParams[
				*GetEvaluationBacktestParams,
				*EvaluationDetail,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserEvaluationsGetEvaluationBacktest(app),
			},
		),

		// GET /api/v1/evaluations/backtests/{runId}/evidence
		GetEvaluationBacktestEvidence: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*GetEvaluationBacktestEvidenceParams,
				*EvaluationEvidence,
			](),
			newHTTPHandlerAdapter[
				*GetEvaluationBacktestEvidenceParams,
				*EvaluationEvidence,
			](),
			makeActionBuilderParams[
				*GetEvaluationBacktestEvidenceParams,
				*EvaluationEvidence,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserEvaluationsGetEvaluationBacktestEvidence(app),
			},
		),

		// GET /api/v1/evaluations/backtests/{runId}/report
		GetEvaluationBacktestReport: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*GetEvaluationBacktestReportParams,
				*EvaluationReport,
			](),
			newHTTPHandlerAdapter[
				*GetEvaluationBacktestReportParams,
				*EvaluationReport,
			](),
			makeActionBuilderParams[
				*GetEvaluationBacktestReportParams,
				*EvaluationReport,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserEvaluationsGetEvaluationBacktestReport(app),
			},
		),

		// GET /api/v1/evaluations/backtests
		ListEvaluationBacktests: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*ListEvaluationBacktestsParams,
				*EvaluationListResponse,
			](),
			newHTTPHandlerAdapter[
				*ListEvaluationBacktestsParams,
				*EvaluationListResponse,
			](),
			makeActionBuilderParams[
				*ListEvaluationBacktestsParams,
				*EvaluationListResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserEvaluationsListEvaluationBacktests(app),
			},
		),
	}
}
