// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint
type AccessTokenMetadataPermission string

// List of AccessTokenMetadataPermission values.
const (
	AccessTokenMetadataPermissionReadOnly AccessTokenMetadataPermission = "read-only"
	AccessTokenMetadataPermissionReadWrite AccessTokenMetadataPermission = "read-write"
)

func(v AccessTokenMetadataPermission) IsReadOnly() bool {
  return v == AccessTokenMetadataPermissionReadOnly
}

func(v AccessTokenMetadataPermission) IsReadWrite() bool {
  return v == AccessTokenMetadataPermissionReadWrite
}

func(v AccessTokenMetadataPermission) String() string {
	return string(v)
}

type assignableAccessTokenMetadataPermission interface {
	IsReadOnly() bool
	IsReadWrite() bool
	String() string
}

func AsAccessTokenMetadataPermission(v assignableAccessTokenMetadataPermission) (AccessTokenMetadataPermission) {
	return AccessTokenMetadataPermission(v.String())
}

func ParseAccessTokenMetadataPermission(str string, target *AccessTokenMetadataPermission) error {
	switch str {
	case "read-only":
		*target = AccessTokenMetadataPermissionReadOnly
	case "read-write":
		*target = AccessTokenMetadataPermissionReadWrite
	default:
		return fmt.Errorf("unexpected AccessTokenMetadataPermission value: %s", str)
	}
	return nil
}

func (v *AccessTokenMetadataPermission) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	return ParseAccessTokenMetadataPermission(str, v)
}

// All allowed values of AccessTokenMetadataPermission enum.
var AllowableAccessTokenMetadataPermissionValues = []AccessTokenMetadataPermission{
	AccessTokenMetadataPermissionReadOnly,
	AccessTokenMetadataPermissionReadWrite,
}
type AccessTokenMetadataStatus string

// List of AccessTokenMetadataStatus values.
const (
	AccessTokenMetadataStatusActive AccessTokenMetadataStatus = "active"
	AccessTokenMetadataStatusExpired AccessTokenMetadataStatus = "expired"
	AccessTokenMetadataStatusRevoked AccessTokenMetadataStatus = "revoked"
)

func(v AccessTokenMetadataStatus) IsActive() bool {
  return v == AccessTokenMetadataStatusActive
}

func(v AccessTokenMetadataStatus) IsExpired() bool {
  return v == AccessTokenMetadataStatusExpired
}

func(v AccessTokenMetadataStatus) IsRevoked() bool {
  return v == AccessTokenMetadataStatusRevoked
}

func(v AccessTokenMetadataStatus) String() string {
	return string(v)
}

type assignableAccessTokenMetadataStatus interface {
	IsActive() bool
	IsExpired() bool
	IsRevoked() bool
	String() string
}

func AsAccessTokenMetadataStatus(v assignableAccessTokenMetadataStatus) (AccessTokenMetadataStatus) {
	return AccessTokenMetadataStatus(v.String())
}

func ParseAccessTokenMetadataStatus(str string, target *AccessTokenMetadataStatus) error {
	switch str {
	case "active":
		*target = AccessTokenMetadataStatusActive
	case "expired":
		*target = AccessTokenMetadataStatusExpired
	case "revoked":
		*target = AccessTokenMetadataStatusRevoked
	default:
		return fmt.Errorf("unexpected AccessTokenMetadataStatus value: %s", str)
	}
	return nil
}

func (v *AccessTokenMetadataStatus) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	return ParseAccessTokenMetadataStatus(str, v)
}

// All allowed values of AccessTokenMetadataStatus enum.
var AllowableAccessTokenMetadataStatusValues = []AccessTokenMetadataStatus{
	AccessTokenMetadataStatusActive,
	AccessTokenMetadataStatusExpired,
	AccessTokenMetadataStatusRevoked,
}

type AccessTokenMetadata struct { 
	ID string `json:"id"`
	Name string `json:"name"`
	Hint string `json:"hint"`
	Permission AccessTokenMetadataPermission `json:"permission"`
	Status AccessTokenMetadataStatus `json:"status"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	RevokedAt *time.Time `json:"revokedAt,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
