// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint
type AccessTokenCreateRequestPermission string

// List of AccessTokenCreateRequestPermission values.
const (
	AccessTokenCreateRequestPermissionReadOnly AccessTokenCreateRequestPermission = "read-only"
	AccessTokenCreateRequestPermissionReadWrite AccessTokenCreateRequestPermission = "read-write"
)

func(v AccessTokenCreateRequestPermission) IsReadOnly() bool {
  return v == AccessTokenCreateRequestPermissionReadOnly
}

func(v AccessTokenCreateRequestPermission) IsReadWrite() bool {
  return v == AccessTokenCreateRequestPermissionReadWrite
}

func(v AccessTokenCreateRequestPermission) String() string {
	return string(v)
}

type assignableAccessTokenCreateRequestPermission interface {
	IsReadOnly() bool
	IsReadWrite() bool
	String() string
}

func AsAccessTokenCreateRequestPermission(v assignableAccessTokenCreateRequestPermission) (AccessTokenCreateRequestPermission) {
	return AccessTokenCreateRequestPermission(v.String())
}

func ParseAccessTokenCreateRequestPermission(str string, target *AccessTokenCreateRequestPermission) error {
	switch str {
	case "read-only":
		*target = AccessTokenCreateRequestPermissionReadOnly
	case "read-write":
		*target = AccessTokenCreateRequestPermissionReadWrite
	default:
		return fmt.Errorf("unexpected AccessTokenCreateRequestPermission value: %s", str)
	}
	return nil
}

func (v *AccessTokenCreateRequestPermission) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	return ParseAccessTokenCreateRequestPermission(str, v)
}

// All allowed values of AccessTokenCreateRequestPermission enum.
var AllowableAccessTokenCreateRequestPermissionValues = []AccessTokenCreateRequestPermission{
	AccessTokenCreateRequestPermissionReadOnly,
	AccessTokenCreateRequestPermissionReadWrite,
}

type AccessTokenCreateRequest struct { 
	Name string `json:"name"`
	Permission AccessTokenCreateRequestPermission `json:"permission"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}
