// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// CreateAuthAccessTokenParams - Parameters for the createAuthAccessToken operation.
type CreateAuthAccessTokenParams struct { 
	Payload *AccessTokenCreateRequest `json:"payload"`
}
