// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// CreateFinanceAccountParams - Parameters for the createFinanceAccount operation.
type CreateFinanceAccountParams struct { 
	TenantID string `json:"tenantId"`
	Payload *FinanceAccountCreateRequest `json:"payload"`
}
