// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// CreateFinanceTagParams - Parameters for the createFinanceTag operation.
type CreateFinanceTagParams struct { 
	TenantID string `json:"tenantId"`
	Payload *FinanceTagCreateRequest `json:"payload"`
}
