// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// DeleteFinanceConnectionParams - Parameters for the deleteFinanceConnection operation.
type DeleteFinanceConnectionParams struct { 
	TenantID string `json:"tenantId"`
	ConnectionID string `json:"connectionId"`
}
