// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint
type FinanceProviderSnapshotMetadataKind string

// List of FinanceProviderSnapshotMetadataKind values.
const (
	FinanceProviderSnapshotMetadataKindConnection FinanceProviderSnapshotMetadataKind = "connection"
	FinanceProviderSnapshotMetadataKindAccount FinanceProviderSnapshotMetadataKind = "account"
	FinanceProviderSnapshotMetadataKindAccountBalance FinanceProviderSnapshotMetadataKind = "account_balance"
	FinanceProviderSnapshotMetadataKindTransaction FinanceProviderSnapshotMetadataKind = "transaction"
)

func(v FinanceProviderSnapshotMetadataKind) IsConnection() bool {
  return v == FinanceProviderSnapshotMetadataKindConnection
}

func(v FinanceProviderSnapshotMetadataKind) IsAccount() bool {
  return v == FinanceProviderSnapshotMetadataKindAccount
}

func(v FinanceProviderSnapshotMetadataKind) IsAccountBalance() bool {
  return v == FinanceProviderSnapshotMetadataKindAccountBalance
}

func(v FinanceProviderSnapshotMetadataKind) IsTransaction() bool {
  return v == FinanceProviderSnapshotMetadataKindTransaction
}

func(v FinanceProviderSnapshotMetadataKind) String() string {
	return string(v)
}

type assignableFinanceProviderSnapshotMetadataKind interface {
	IsConnection() bool
	IsAccount() bool
	IsAccountBalance() bool
	IsTransaction() bool
	String() string
}

func AsFinanceProviderSnapshotMetadataKind(v assignableFinanceProviderSnapshotMetadataKind) (FinanceProviderSnapshotMetadataKind) {
	return FinanceProviderSnapshotMetadataKind(v.String())
}

func ParseFinanceProviderSnapshotMetadataKind(str string, target *FinanceProviderSnapshotMetadataKind) error {
	switch str {
	case "connection":
		*target = FinanceProviderSnapshotMetadataKindConnection
	case "account":
		*target = FinanceProviderSnapshotMetadataKindAccount
	case "account_balance":
		*target = FinanceProviderSnapshotMetadataKindAccountBalance
	case "transaction":
		*target = FinanceProviderSnapshotMetadataKindTransaction
	default:
		return fmt.Errorf("unexpected FinanceProviderSnapshotMetadataKind value: %s", str)
	}
	return nil
}

func (v *FinanceProviderSnapshotMetadataKind) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	return ParseFinanceProviderSnapshotMetadataKind(str, v)
}

// All allowed values of FinanceProviderSnapshotMetadataKind enum.
var AllowableFinanceProviderSnapshotMetadataKindValues = []FinanceProviderSnapshotMetadataKind{
	FinanceProviderSnapshotMetadataKindConnection,
	FinanceProviderSnapshotMetadataKindAccount,
	FinanceProviderSnapshotMetadataKindAccountBalance,
	FinanceProviderSnapshotMetadataKindTransaction,
}

type FinanceProviderSnapshotMetadata struct { 
	ID string `json:"id"`
	Kind FinanceProviderSnapshotMetadataKind `json:"kind"`
	ProviderObjectID string `json:"providerObjectId"`
	CapturedAt time.Time `json:"capturedAt"`
}
