// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceClassificationRule struct { 
	ID string `json:"id"`
	TenantID string `json:"tenantId"`
	MatchType string `json:"matchType"`
	Condition string `json:"condition"`
	CategoryID string `json:"categoryId"`
	TagIDs []string `json:"tagIds"`
	Position int64 `json:"position"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
