// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// GetFinanceDashboardParams - Parameters for the getFinanceDashboard operation.
type GetFinanceDashboardParams struct { 
	TenantID string `json:"tenantId"`
	StartDate time.Time `json:"startDate"`
	EndDate time.Time `json:"endDate"`
}
