// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// LinkFinanceConnectionTokenParams - Parameters for the linkFinanceConnectionToken operation.
type LinkFinanceConnectionTokenParams struct { 
	TenantID string `json:"tenantId"`
	Payload *FinanceConnectionLinkTokenRequest `json:"payload"`
}
