// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListFinanceClassificationRulesParams - Parameters for the listFinanceClassificationRules operation.
type ListFinanceClassificationRulesParams struct { 
	TenantID string `json:"tenantId"`
	CategoryID string `json:"categoryId,omitempty"`
}
