// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListFinanceTenantMembersParams - Parameters for the listFinanceTenantMembers operation.
type ListFinanceTenantMembersParams struct { 
	TenantID string `json:"tenantId"`
}
