// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// UpdateFinanceClassificationRuleParams - Parameters for the updateFinanceClassificationRule operation.
type UpdateFinanceClassificationRuleParams struct { 
	TenantID string `json:"tenantId"`
	RuleID string `json:"ruleId"`
	Payload *FinanceClassificationRuleRequest `json:"payload"`
}
