// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package internal

import (
	"context"
	"iter"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/adk/agent"
	"google.golang.org/adk/runner"
	"google.golang.org/adk/session"
	"google.golang.org/genai"
)

// NewMockLLMRunner creates a new instance of MockLLMRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMRunner {
	mock := &MockLLMRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLLMRunner is an autogenerated mock type for the LLMRunner type
type MockLLMRunner struct {
	mock.Mock
}

type MockLLMRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMRunner) EXPECT() *MockLLMRunner_Expecter {
	return &MockLLMRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockLLMRunner
func (_mock *MockLLMRunner) Run(ctx context.Context, userID string, sessionID string, msg *genai.Content, cfg agent.RunConfig, opts ...runner.RunOption) iter.Seq2[*session.Event, error] {
	// runner.RunOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, userID, sessionID, msg, cfg)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 iter.Seq2[*session.Event, error]
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *genai.Content, agent.RunConfig, ...runner.RunOption) iter.Seq2[*session.Event, error]); ok {
		r0 = returnFunc(ctx, userID, sessionID, msg, cfg, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[*session.Event, error])
		}
	}
	return r0
}

// MockLLMRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockLLMRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
//   - msg *genai.Content
//   - cfg agent.RunConfig
//   - opts ...runner.RunOption
func (_e *MockLLMRunner_Expecter) Run(ctx interface{}, userID interface{}, sessionID interface{}, msg interface{}, cfg interface{}, opts ...interface{}) *MockLLMRunner_Run_Call {
	return &MockLLMRunner_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, userID, sessionID, msg, cfg}, opts...)...)}
}

func (_c *MockLLMRunner_Run_Call) Run(run func(ctx context.Context, userID string, sessionID string, msg *genai.Content, cfg agent.RunConfig, opts ...runner.RunOption)) *MockLLMRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *genai.Content
		if args[3] != nil {
			arg3 = args[3].(*genai.Content)
		}
		var arg4 agent.RunConfig
		if args[4] != nil {
			arg4 = args[4].(agent.RunConfig)
		}
		var arg5 []runner.RunOption
		variadicArgs := make([]runner.RunOption, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(runner.RunOption)
			}
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockLLMRunner_Run_Call) Return(seq2 iter.Seq2[*session.Event, error]) *MockLLMRunner_Run_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *MockLLMRunner_Run_Call) RunAndReturn(run func(ctx context.Context, userID string, sessionID string, msg *genai.Content, cfg agent.RunConfig, opts ...runner.RunOption) iter.Seq2[*session.Event, error]) *MockLLMRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
