// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package main

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockdatabaseMigrationRunner creates a new instance of mockdatabaseMigrationRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdatabaseMigrationRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdatabaseMigrationRunner {
	mock := &mockdatabaseMigrationRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdatabaseMigrationRunner is an autogenerated mock type for the databaseMigrationRunner type
type mockdatabaseMigrationRunner struct {
	mock.Mock
}

type mockdatabaseMigrationRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdatabaseMigrationRunner) EXPECT() *mockdatabaseMigrationRunner_Expecter {
	return &mockdatabaseMigrationRunner_Expecter{mock: &_m.Mock}
}

// Migrate provides a mock function for the type mockdatabaseMigrationRunner
func (_mock *mockdatabaseMigrationRunner) Migrate(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdatabaseMigrationRunner_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type mockdatabaseMigrationRunner_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockdatabaseMigrationRunner_Expecter) Migrate(context1 any) *mockdatabaseMigrationRunner_Migrate_Call {
	return &mockdatabaseMigrationRunner_Migrate_Call{Call: _e.mock.On("Migrate", context1)}
}

func (_c *mockdatabaseMigrationRunner_Migrate_Call) Run(run func(context1 context.Context)) *mockdatabaseMigrationRunner_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdatabaseMigrationRunner_Migrate_Call) Return(err error) *mockdatabaseMigrationRunner_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdatabaseMigrationRunner_Migrate_Call) RunAndReturn(run func(context1 context.Context) error) *mockdatabaseMigrationRunner_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockjobsWorkerRunner creates a new instance of mockjobsWorkerRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjobsWorkerRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjobsWorkerRunner {
	mock := &mockjobsWorkerRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjobsWorkerRunner is an autogenerated mock type for the jobsWorkerRunner type
type mockjobsWorkerRunner struct {
	mock.Mock
}

type mockjobsWorkerRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjobsWorkerRunner) EXPECT() *mockjobsWorkerRunner_Expecter {
	return &mockjobsWorkerRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type mockjobsWorkerRunner
func (_mock *mockjobsWorkerRunner) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsWorkerRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockjobsWorkerRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsWorkerRunner_Expecter) Run(context1 any) *mockjobsWorkerRunner_Run_Call {
	return &mockjobsWorkerRunner_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *mockjobsWorkerRunner_Run_Call) Run(run func(context1 context.Context)) *mockjobsWorkerRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsWorkerRunner_Run_Call) Return(err error) *mockjobsWorkerRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsWorkerRunner_Run_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsWorkerRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunOnce provides a mock function for the type mockjobsWorkerRunner
func (_mock *mockjobsWorkerRunner) RunOnce(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for RunOnce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsWorkerRunner_RunOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOnce'
type mockjobsWorkerRunner_RunOnce_Call struct {
	*mock.Call
}

// RunOnce is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsWorkerRunner_Expecter) RunOnce(context1 any) *mockjobsWorkerRunner_RunOnce_Call {
	return &mockjobsWorkerRunner_RunOnce_Call{Call: _e.mock.On("RunOnce", context1)}
}

func (_c *mockjobsWorkerRunner_RunOnce_Call) Run(run func(context1 context.Context)) *mockjobsWorkerRunner_RunOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsWorkerRunner_RunOnce_Call) Return(err error) *mockjobsWorkerRunner_RunOnce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsWorkerRunner_RunOnce_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsWorkerRunner_RunOnce_Call {
	_c.Call.Return(run)
	return _c
}

// newMockjobsSchedulerRunner creates a new instance of mockjobsSchedulerRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjobsSchedulerRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjobsSchedulerRunner {
	mock := &mockjobsSchedulerRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjobsSchedulerRunner is an autogenerated mock type for the jobsSchedulerRunner type
type mockjobsSchedulerRunner struct {
	mock.Mock
}

type mockjobsSchedulerRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjobsSchedulerRunner) EXPECT() *mockjobsSchedulerRunner_Expecter {
	return &mockjobsSchedulerRunner_Expecter{mock: &_m.Mock}
}

// EnqueueDue provides a mock function for the type mockjobsSchedulerRunner
func (_mock *mockjobsSchedulerRunner) EnqueueDue(context1 context.Context) (int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueDue")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjobsSchedulerRunner_EnqueueDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueDue'
type mockjobsSchedulerRunner_EnqueueDue_Call struct {
	*mock.Call
}

// EnqueueDue is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsSchedulerRunner_Expecter) EnqueueDue(context1 any) *mockjobsSchedulerRunner_EnqueueDue_Call {
	return &mockjobsSchedulerRunner_EnqueueDue_Call{Call: _e.mock.On("EnqueueDue", context1)}
}

func (_c *mockjobsSchedulerRunner_EnqueueDue_Call) Run(run func(context1 context.Context)) *mockjobsSchedulerRunner_EnqueueDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsSchedulerRunner_EnqueueDue_Call) Return(n int, err error) *mockjobsSchedulerRunner_EnqueueDue_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockjobsSchedulerRunner_EnqueueDue_Call) RunAndReturn(run func(context1 context.Context) (int, error)) *mockjobsSchedulerRunner_EnqueueDue_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstartAllHTTPServer creates a new instance of mockstartAllHTTPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstartAllHTTPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstartAllHTTPServer {
	mock := &mockstartAllHTTPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstartAllHTTPServer is an autogenerated mock type for the startAllHTTPServer type
type mockstartAllHTTPServer struct {
	mock.Mock
}

type mockstartAllHTTPServer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstartAllHTTPServer) EXPECT() *mockstartAllHTTPServer_Expecter {
	return &mockstartAllHTTPServer_Expecter{mock: &_m.Mock}
}

// StartHTTPServer provides a mock function for the type mockstartAllHTTPServer
func (_mock *mockstartAllHTTPServer) StartHTTPServer(context1 context.Context, vs ...startHTTPServerOpt) error {
	// startHTTPServerOpt
	_va := make([]any, len(vs))
	for _i := range vs {
		_va[_i] = vs[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StartHTTPServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...startHTTPServerOpt) error); ok {
		r0 = returnFunc(context1, vs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstartAllHTTPServer_StartHTTPServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartHTTPServer'
type mockstartAllHTTPServer_StartHTTPServer_Call struct {
	*mock.Call
}

// StartHTTPServer is a helper method to define mock.On call
//   - context1 context.Context
//   - vs ...startHTTPServerOpt
func (_e *mockstartAllHTTPServer_Expecter) StartHTTPServer(context1 any, vs ...any) *mockstartAllHTTPServer_StartHTTPServer_Call {
	return &mockstartAllHTTPServer_StartHTTPServer_Call{Call: _e.mock.On("StartHTTPServer",
		append([]any{context1}, vs...)...)}
}

func (_c *mockstartAllHTTPServer_StartHTTPServer_Call) Run(run func(context1 context.Context, vs ...startHTTPServerOpt)) *mockstartAllHTTPServer_StartHTTPServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []startHTTPServerOpt
		variadicArgs := make([]startHTTPServerOpt, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(startHTTPServerOpt)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockstartAllHTTPServer_StartHTTPServer_Call) Return(err error) *mockstartAllHTTPServer_StartHTTPServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstartAllHTTPServer_StartHTTPServer_Call) RunAndReturn(run func(context1 context.Context, vs ...startHTTPServerOpt) error) *mockstartAllHTTPServer_StartHTTPServer_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstartAllRunner creates a new instance of mockstartAllRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstartAllRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstartAllRunner {
	mock := &mockstartAllRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstartAllRunner is an autogenerated mock type for the startAllRunner type
type mockstartAllRunner struct {
	mock.Mock
}

type mockstartAllRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstartAllRunner) EXPECT() *mockstartAllRunner_Expecter {
	return &mockstartAllRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type mockstartAllRunner
func (_mock *mockstartAllRunner) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstartAllRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockstartAllRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockstartAllRunner_Expecter) Run(context1 any) *mockstartAllRunner_Run_Call {
	return &mockstartAllRunner_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *mockstartAllRunner_Run_Call) Run(run func(context1 context.Context)) *mockstartAllRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstartAllRunner_Run_Call) Return(err error) *mockstartAllRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstartAllRunner_Run_Call) RunAndReturn(run func(context1 context.Context) error) *mockstartAllRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
