// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package finance

import (
	"context"

	"github.com/gemyago/sumweave/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockaccessGuardStore creates a new instance of mockaccessGuardStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockaccessGuardStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockaccessGuardStore {
	mock := &mockaccessGuardStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockaccessGuardStore is an autogenerated mock type for the accessGuardStore type
type mockaccessGuardStore struct {
	mock.Mock
}

type mockaccessGuardStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockaccessGuardStore) EXPECT() *mockaccessGuardStore_Expecter {
	return &mockaccessGuardStore_Expecter{mock: &_m.Mock}
}

// IsTenantMember provides a mock function for the type mockaccessGuardStore
func (_mock *mockaccessGuardStore) IsTenantMember(ctx context.Context, tenantID string, userID string) (bool, error) {
	ret := _mock.Called(ctx, tenantID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsTenantMember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, tenantID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, tenantID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockaccessGuardStore_IsTenantMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTenantMember'
type mockaccessGuardStore_IsTenantMember_Call struct {
	*mock.Call
}

// IsTenantMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID string
func (_e *mockaccessGuardStore_Expecter) IsTenantMember(ctx interface{}, tenantID interface{}, userID interface{}) *mockaccessGuardStore_IsTenantMember_Call {
	return &mockaccessGuardStore_IsTenantMember_Call{Call: _e.mock.On("IsTenantMember", ctx, tenantID, userID)}
}

func (_c *mockaccessGuardStore_IsTenantMember_Call) Run(run func(ctx context.Context, tenantID string, userID string)) *mockaccessGuardStore_IsTenantMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockaccessGuardStore_IsTenantMember_Call) Return(b bool, err error) *mockaccessGuardStore_IsTenantMember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockaccessGuardStore_IsTenantMember_Call) RunAndReturn(run func(ctx context.Context, tenantID string, userID string) (bool, error)) *mockaccessGuardStore_IsTenantMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFXRatesProvider creates a new instance of MockFXRatesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFXRatesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFXRatesProvider {
	mock := &MockFXRatesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFXRatesProvider is an autogenerated mock type for the FXRatesProvider type
type MockFXRatesProvider struct {
	mock.Mock
}

type MockFXRatesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFXRatesProvider) EXPECT() *MockFXRatesProvider_Expecter {
	return &MockFXRatesProvider_Expecter{mock: &_m.Mock}
}

// FetchLatestRates provides a mock function for the type MockFXRatesProvider
func (_mock *MockFXRatesProvider) FetchLatestRates(ctx context.Context, query FXProviderQuery) ([]domain.FXRate, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for FetchLatestRates")
	}

	var r0 []domain.FXRate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FXProviderQuery) ([]domain.FXRate, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FXProviderQuery) []domain.FXRate); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FXRate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FXProviderQuery) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFXRatesProvider_FetchLatestRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchLatestRates'
type MockFXRatesProvider_FetchLatestRates_Call struct {
	*mock.Call
}

// FetchLatestRates is a helper method to define mock.On call
//   - ctx context.Context
//   - query FXProviderQuery
func (_e *MockFXRatesProvider_Expecter) FetchLatestRates(ctx interface{}, query interface{}) *MockFXRatesProvider_FetchLatestRates_Call {
	return &MockFXRatesProvider_FetchLatestRates_Call{Call: _e.mock.On("FetchLatestRates", ctx, query)}
}

func (_c *MockFXRatesProvider_FetchLatestRates_Call) Run(run func(ctx context.Context, query FXProviderQuery)) *MockFXRatesProvider_FetchLatestRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FXProviderQuery
		if args[1] != nil {
			arg1 = args[1].(FXProviderQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFXRatesProvider_FetchLatestRates_Call) Return(fXRates []domain.FXRate, err error) *MockFXRatesProvider_FetchLatestRates_Call {
	_c.Call.Return(fXRates, err)
	return _c
}

func (_c *MockFXRatesProvider_FetchLatestRates_Call) RunAndReturn(run func(ctx context.Context, query FXProviderQuery) ([]domain.FXRate, error)) *MockFXRatesProvider_FetchLatestRates_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockFXRatesProvider
func (_mock *MockFXRatesProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFXRatesProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockFXRatesProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockFXRatesProvider_Expecter) Name() *MockFXRatesProvider_Name_Call {
	return &MockFXRatesProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockFXRatesProvider_Name_Call) Run(run func()) *MockFXRatesProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFXRatesProvider_Name_Call) Return(s string) *MockFXRatesProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFXRatesProvider_Name_Call) RunAndReturn(run func() string) *MockFXRatesProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// newMockproviderEvidenceServiceStore creates a new instance of mockproviderEvidenceServiceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockproviderEvidenceServiceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockproviderEvidenceServiceStore {
	mock := &mockproviderEvidenceServiceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockproviderEvidenceServiceStore is an autogenerated mock type for the providerEvidenceServiceStore type
type mockproviderEvidenceServiceStore struct {
	mock.Mock
}

type mockproviderEvidenceServiceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockproviderEvidenceServiceStore) EXPECT() *mockproviderEvidenceServiceStore_Expecter {
	return &mockproviderEvidenceServiceStore_Expecter{mock: &_m.Mock}
}

// GetAccountProviderEvidence provides a mock function for the type mockproviderEvidenceServiceStore
func (_mock *mockproviderEvidenceServiceStore) GetAccountProviderEvidence(context1 context.Context, s string, s1 string, s2 string) (domain.ProviderEvidence, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountProviderEvidence")
	}

	var r0 domain.ProviderEvidence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.ProviderEvidence, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) domain.ProviderEvidence); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Get(0).(domain.ProviderEvidence)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountProviderEvidence'
type mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call struct {
	*mock.Call
}

// GetAccountProviderEvidence is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *mockproviderEvidenceServiceStore_Expecter) GetAccountProviderEvidence(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}) *mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call {
	return &mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call{Call: _e.mock.On("GetAccountProviderEvidence", context1, s, s1, s2)}
}

func (_c *mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call) Return(providerEvidence domain.ProviderEvidence, err error) *mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call {
	_c.Call.Return(providerEvidence, err)
	return _c
}

func (_c *mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (domain.ProviderEvidence, error)) *mockproviderEvidenceServiceStore_GetAccountProviderEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionProviderEvidence provides a mock function for the type mockproviderEvidenceServiceStore
func (_mock *mockproviderEvidenceServiceStore) GetTransactionProviderEvidence(context1 context.Context, s string, s1 string, s2 string) (domain.ProviderEvidence, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionProviderEvidence")
	}

	var r0 domain.ProviderEvidence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.ProviderEvidence, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) domain.ProviderEvidence); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Get(0).(domain.ProviderEvidence)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionProviderEvidence'
type mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call struct {
	*mock.Call
}

// GetTransactionProviderEvidence is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *mockproviderEvidenceServiceStore_Expecter) GetTransactionProviderEvidence(context1 interface{}, s interface{}, s1 interface{}, s2 interface{}) *mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call {
	return &mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call{Call: _e.mock.On("GetTransactionProviderEvidence", context1, s, s1, s2)}
}

func (_c *mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call) Return(providerEvidence domain.ProviderEvidence, err error) *mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call {
	_c.Call.Return(providerEvidence, err)
	return _c
}

func (_c *mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (domain.ProviderEvidence, error)) *mockproviderEvidenceServiceStore_GetTransactionProviderEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// IsTenantMember provides a mock function for the type mockproviderEvidenceServiceStore
func (_mock *mockproviderEvidenceServiceStore) IsTenantMember(context1 context.Context, s string, s1 string) (bool, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for IsTenantMember")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockproviderEvidenceServiceStore_IsTenantMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTenantMember'
type mockproviderEvidenceServiceStore_IsTenantMember_Call struct {
	*mock.Call
}

// IsTenantMember is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *mockproviderEvidenceServiceStore_Expecter) IsTenantMember(context1 interface{}, s interface{}, s1 interface{}) *mockproviderEvidenceServiceStore_IsTenantMember_Call {
	return &mockproviderEvidenceServiceStore_IsTenantMember_Call{Call: _e.mock.On("IsTenantMember", context1, s, s1)}
}

func (_c *mockproviderEvidenceServiceStore_IsTenantMember_Call) Run(run func(context1 context.Context, s string, s1 string)) *mockproviderEvidenceServiceStore_IsTenantMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockproviderEvidenceServiceStore_IsTenantMember_Call) Return(b bool, err error) *mockproviderEvidenceServiceStore_IsTenantMember_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockproviderEvidenceServiceStore_IsTenantMember_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (bool, error)) *mockproviderEvidenceServiceStore_IsTenantMember_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccountProviderEvidence provides a mock function for the type mockproviderEvidenceServiceStore
func (_mock *mockproviderEvidenceServiceStore) ListAccountProviderEvidence(context1 context.Context, s string, s1 string) ([]domain.ProviderEvidence, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for ListAccountProviderEvidence")
	}

	var r0 []domain.ProviderEvidence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.ProviderEvidence, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []domain.ProviderEvidence); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProviderEvidence)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccountProviderEvidence'
type mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call struct {
	*mock.Call
}

// ListAccountProviderEvidence is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *mockproviderEvidenceServiceStore_Expecter) ListAccountProviderEvidence(context1 interface{}, s interface{}, s1 interface{}) *mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call {
	return &mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call{Call: _e.mock.On("ListAccountProviderEvidence", context1, s, s1)}
}

func (_c *mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call) Run(run func(context1 context.Context, s string, s1 string)) *mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call) Return(providerEvidences []domain.ProviderEvidence, err error) *mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call {
	_c.Call.Return(providerEvidences, err)
	return _c
}

func (_c *mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) ([]domain.ProviderEvidence, error)) *mockproviderEvidenceServiceStore_ListAccountProviderEvidence_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactionProviderEvidence provides a mock function for the type mockproviderEvidenceServiceStore
func (_mock *mockproviderEvidenceServiceStore) ListTransactionProviderEvidence(context1 context.Context, s string, s1 string) ([]domain.ProviderEvidence, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactionProviderEvidence")
	}

	var r0 []domain.ProviderEvidence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.ProviderEvidence, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []domain.ProviderEvidence); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProviderEvidence)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactionProviderEvidence'
type mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call struct {
	*mock.Call
}

// ListTransactionProviderEvidence is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *mockproviderEvidenceServiceStore_Expecter) ListTransactionProviderEvidence(context1 interface{}, s interface{}, s1 interface{}) *mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call {
	return &mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call{Call: _e.mock.On("ListTransactionProviderEvidence", context1, s, s1)}
}

func (_c *mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call) Run(run func(context1 context.Context, s string, s1 string)) *mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call) Return(providerEvidences []domain.ProviderEvidence, err error) *mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call {
	_c.Call.Return(providerEvidences, err)
	return _c
}

func (_c *mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) ([]domain.ProviderEvidence, error)) *mockproviderEvidenceServiceStore_ListTransactionProviderEvidence_Call {
	_c.Call.Return(run)
	return _c
}
