<script lang="ts">
  import { onMount } from 'svelte'
  import FinanceSubnav from '../components/FinanceSubnav.svelte'
  import { authStore } from '../lib/auth/auth-store.svelte'
  import { createSignalFinanceApiForAuth, type FinanceCategory, type FinanceTag, type FinanceTenantSummary } from '../lib/finance/api'
  import { chooseFinanceTenantId, setPreferredFinanceTenantId } from '../lib/finance/tenant-selection'
  const appBaseUrl = import.meta.env.VITE_APP_API_BASE_URL ?? '/api/v1'
  const financeApi = $derived.by(() => createSignalFinanceApiForAuth({ baseUrl: appBaseUrl, authStore }))
  let loading = $state(true); let error = $state<string | null>(null); let tenants = $state<FinanceTenantSummary[]>([]); let selectedTenantId = $state(''); let categories = $state<FinanceCategory[]>([]); let tags = $state<FinanceTag[]>([]); let categoryName = $state(''); let categoryKind = $state('expense'); let tagName = $state(''); const selectedTenant = $derived(tenants.find((item) => item.id === selectedTenantId) ?? null)
  onMount(() => { void loadPage() })
  async function loadPage() { loading = true; error = null; try { tenants = await financeApi.listTenants(); selectedTenantId = chooseFinanceTenantId(tenants); if (selectedTenantId) { setPreferredFinanceTenantId(selectedTenantId); await loadCatalogs() } } catch (loadError) { error = loadError instanceof Error ? loadError.message : 'Failed to load categories' } finally { loading = false } }
  async function loadCatalogs() { if (!selectedTenantId) return; [categories, tags] = await Promise.all([financeApi.listCategories({ tenantId: selectedTenantId }), financeApi.listTags({ tenantId: selectedTenantId })]) }
  async function createCategory(event: SubmitEvent) { event.preventDefault(); await financeApi.createCategory({ tenantId: selectedTenantId, name: categoryName, kind: categoryKind }); categoryName = ''; await loadCatalogs() }
  async function createTag(event: SubmitEvent) { event.preventDefault(); await financeApi.createTag({ tenantId: selectedTenantId, name: tagName }); tagName = ''; await loadCatalogs() }
</script>

<section class="page" aria-labelledby="finance-categories-heading"><header><h1 id="finance-categories-heading">Finance categories and tags</h1><p class="muted">Manage tenant-local reporting categories and transaction tags.</p></header><FinanceSubnav current="/finance/categories" tenantName={selectedTenant?.name ?? ''} />{#if error}<p class="error" role="alert">{error}</p>{/if}{#if loading}<p class="muted" role="status">Loading categories…</p>{:else}<section class="panel"><label><span>Tenant</span><select bind:value={selectedTenantId} onchange={() => { setPreferredFinanceTenantId(selectedTenantId); void loadCatalogs() }} aria-label="Tenant"><option value="">Select tenant</option>{#each tenants as tenant (tenant.id)}<option value={tenant.id}>{tenant.name}</option>{/each}</select></label></section><div class="grid"><form class="panel" onsubmit={createCategory}><h2>Create category</h2><label><span>Name</span><input bind:value={categoryName} aria-label="Category name" required /></label><label><span>Kind</span><select bind:value={categoryKind} aria-label="Category kind"><option value="expense">expense</option><option value="income">income</option></select></label><button class="primary" type="submit" disabled={!selectedTenantId}>Create category</button><div class="stack">{#each categories as category (category.id)}<article class="card"><strong>{category.name}</strong><span>{category.kind}</span></article>{:else}<p class="muted">No categories yet.</p>{/each}</div></form><form class="panel" onsubmit={createTag}><h2>Create tag</h2><label><span>Name</span><input bind:value={tagName} aria-label="Tag name" required /></label><button class="primary" type="submit" disabled={!selectedTenantId}>Create tag</button><div class="stack">{#each tags as tag (tag.id)}<article class="card"><strong>{tag.name}</strong></article>{:else}<p class="muted">No tags yet.</p>{/each}</div></form></div>{/if}</section>

<style>.page,.stack{display:flex;flex-direction:column;gap:var(--space-16)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:var(--space-16)}.panel{display:flex;flex-direction:column;gap:var(--space-12);padding:var(--space-16);border:1px solid var(--border);border-radius:4px;background:var(--bg-elevated,var(--bg))}.card{display:flex;justify-content:space-between;gap:var(--space-12);padding:var(--space-12);border:1px solid var(--border);border-radius:4px}.panel h2,header h1{margin:0}.muted{margin:0;color:var(--text-muted)}.error{color:var(--color-danger-red)}</style>
