apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "signal-foundry.fullname" . }}-scheduler
  labels: {{- include "signal-foundry.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scheduler.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: {{ .Values.scheduler.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.scheduler.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.scheduler.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          serviceAccountName: {{ include "signal-foundry.serviceAccountName" . }}
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets: {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: scheduler
              image: {{ include "signal-foundry.image" . | quote }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: {{- toYaml .Values.scheduler.args | nindent 16 }}
              {{- if or .Values.existingConfigMap .Values.existingSecret }}
              envFrom: {{- include "signal-foundry.envFrom" . | nindent 16 }}
              {{- end }}
              securityContext: {{- toYaml .Values.securityContext | nindent 16 }}
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
              resources: {{- toYaml .Values.scheduler.resources | nindent 16 }}
          volumes:
            - name: tmp
              emptyDir: {}
