// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package wireup

import (
	"context"

	"github.com/gemyago/sumweave/apps/sumweave/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// newMockscheduleEnqueuer creates a new instance of mockscheduleEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockscheduleEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockscheduleEnqueuer {
	mock := &mockscheduleEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockscheduleEnqueuer is an autogenerated mock type for the scheduleEnqueuer type
type mockscheduleEnqueuer struct {
	mock.Mock
}

type mockscheduleEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockscheduleEnqueuer) EXPECT() *mockscheduleEnqueuer_Expecter {
	return &mockscheduleEnqueuer_Expecter{mock: &_m.Mock}
}

// EnqueueDue provides a mock function for the type mockscheduleEnqueuer
func (_mock *mockscheduleEnqueuer) EnqueueDue(context1 context.Context) (int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueDue")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockscheduleEnqueuer_EnqueueDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueDue'
type mockscheduleEnqueuer_EnqueueDue_Call struct {
	*mock.Call
}

// EnqueueDue is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockscheduleEnqueuer_Expecter) EnqueueDue(context1 any) *mockscheduleEnqueuer_EnqueueDue_Call {
	return &mockscheduleEnqueuer_EnqueueDue_Call{Call: _e.mock.On("EnqueueDue", context1)}
}

func (_c *mockscheduleEnqueuer_EnqueueDue_Call) Run(run func(context1 context.Context)) *mockscheduleEnqueuer_EnqueueDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockscheduleEnqueuer_EnqueueDue_Call) Return(n int, err error) *mockscheduleEnqueuer_EnqueueDue_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockscheduleEnqueuer_EnqueueDue_Call) RunAndReturn(run func(context1 context.Context) (int, error)) *mockscheduleEnqueuer_EnqueueDue_Call {
	_c.Call.Return(run)
	return _c
}

// newMockmigrationRunner creates a new instance of mockmigrationRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmigrationRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmigrationRunner {
	mock := &mockmigrationRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmigrationRunner is an autogenerated mock type for the migrationRunner type
type mockmigrationRunner struct {
	mock.Mock
}

type mockmigrationRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmigrationRunner) EXPECT() *mockmigrationRunner_Expecter {
	return &mockmigrationRunner_Expecter{mock: &_m.Mock}
}

// Migrate provides a mock function for the type mockmigrationRunner
func (_mock *mockmigrationRunner) Migrate(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockmigrationRunner_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type mockmigrationRunner_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockmigrationRunner_Expecter) Migrate(context1 any) *mockmigrationRunner_Migrate_Call {
	return &mockmigrationRunner_Migrate_Call{Call: _e.mock.On("Migrate", context1)}
}

func (_c *mockmigrationRunner_Migrate_Call) Run(run func(context1 context.Context)) *mockmigrationRunner_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockmigrationRunner_Migrate_Call) Return(err error) *mockmigrationRunner_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockmigrationRunner_Migrate_Call) RunAndReturn(run func(context1 context.Context) error) *mockmigrationRunner_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockmigrationConfigLoader creates a new instance of mockmigrationConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmigrationConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmigrationConfigLoader {
	mock := &mockmigrationConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmigrationConfigLoader is an autogenerated mock type for the migrationConfigLoader type
type mockmigrationConfigLoader struct {
	mock.Mock
}

type mockmigrationConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmigrationConfigLoader) EXPECT() *mockmigrationConfigLoader_Expecter {
	return &mockmigrationConfigLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type mockmigrationConfigLoader
func (_mock *mockmigrationConfigLoader) Load(migrationOptions MigrationOptions, s string) (config.MigrationRootConfig, error) {
	ret := _mock.Called(migrationOptions, s)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 config.MigrationRootConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(MigrationOptions, string) (config.MigrationRootConfig, error)); ok {
		return returnFunc(migrationOptions, s)
	}
	if returnFunc, ok := ret.Get(0).(func(MigrationOptions, string) config.MigrationRootConfig); ok {
		r0 = returnFunc(migrationOptions, s)
	} else {
		r0 = ret.Get(0).(config.MigrationRootConfig)
	}
	if returnFunc, ok := ret.Get(1).(func(MigrationOptions, string) error); ok {
		r1 = returnFunc(migrationOptions, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockmigrationConfigLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type mockmigrationConfigLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - migrationOptions MigrationOptions
//   - s string
func (_e *mockmigrationConfigLoader_Expecter) Load(migrationOptions any, s any) *mockmigrationConfigLoader_Load_Call {
	return &mockmigrationConfigLoader_Load_Call{Call: _e.mock.On("Load", migrationOptions, s)}
}

func (_c *mockmigrationConfigLoader_Load_Call) Run(run func(migrationOptions MigrationOptions, s string)) *mockmigrationConfigLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 MigrationOptions
		if args[0] != nil {
			arg0 = args[0].(MigrationOptions)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockmigrationConfigLoader_Load_Call) Return(migrationRootConfig config.MigrationRootConfig, err error) *mockmigrationConfigLoader_Load_Call {
	_c.Call.Return(migrationRootConfig, err)
	return _c
}

func (_c *mockmigrationConfigLoader_Load_Call) RunAndReturn(run func(migrationOptions MigrationOptions, s string) (config.MigrationRootConfig, error)) *mockmigrationConfigLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// newMockagentRuntimeSchemaMigrator creates a new instance of mockagentRuntimeSchemaMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockagentRuntimeSchemaMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockagentRuntimeSchemaMigrator {
	mock := &mockagentRuntimeSchemaMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockagentRuntimeSchemaMigrator is an autogenerated mock type for the agentRuntimeSchemaMigrator type
type mockagentRuntimeSchemaMigrator struct {
	mock.Mock
}

type mockagentRuntimeSchemaMigrator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockagentRuntimeSchemaMigrator) EXPECT() *mockagentRuntimeSchemaMigrator_Expecter {
	return &mockagentRuntimeSchemaMigrator_Expecter{mock: &_m.Mock}
}

// AutoMigrate provides a mock function for the type mockagentRuntimeSchemaMigrator
func (_mock *mockagentRuntimeSchemaMigrator) AutoMigrate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoMigrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockagentRuntimeSchemaMigrator_AutoMigrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoMigrate'
type mockagentRuntimeSchemaMigrator_AutoMigrate_Call struct {
	*mock.Call
}

// AutoMigrate is a helper method to define mock.On call
func (_e *mockagentRuntimeSchemaMigrator_Expecter) AutoMigrate() *mockagentRuntimeSchemaMigrator_AutoMigrate_Call {
	return &mockagentRuntimeSchemaMigrator_AutoMigrate_Call{Call: _e.mock.On("AutoMigrate")}
}

func (_c *mockagentRuntimeSchemaMigrator_AutoMigrate_Call) Run(run func()) *mockagentRuntimeSchemaMigrator_AutoMigrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockagentRuntimeSchemaMigrator_AutoMigrate_Call) Return(err error) *mockagentRuntimeSchemaMigrator_AutoMigrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockagentRuntimeSchemaMigrator_AutoMigrate_Call) RunAndReturn(run func() error) *mockagentRuntimeSchemaMigrator_AutoMigrate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockagentRuntimeMigrationPreparer creates a new instance of mockagentRuntimeMigrationPreparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockagentRuntimeMigrationPreparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockagentRuntimeMigrationPreparer {
	mock := &mockagentRuntimeMigrationPreparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockagentRuntimeMigrationPreparer is an autogenerated mock type for the agentRuntimeMigrationPreparer type
type mockagentRuntimeMigrationPreparer struct {
	mock.Mock
}

type mockagentRuntimeMigrationPreparer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockagentRuntimeMigrationPreparer) EXPECT() *mockagentRuntimeMigrationPreparer_Expecter {
	return &mockagentRuntimeMigrationPreparer_Expecter{mock: &_m.Mock}
}

// Prepare provides a mock function for the type mockagentRuntimeMigrationPreparer
func (_mock *mockagentRuntimeMigrationPreparer) Prepare() (agentRuntimeMigrationComponents, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 agentRuntimeMigrationComponents
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (agentRuntimeMigrationComponents, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() agentRuntimeMigrationComponents); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(agentRuntimeMigrationComponents)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockagentRuntimeMigrationPreparer_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type mockagentRuntimeMigrationPreparer_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
func (_e *mockagentRuntimeMigrationPreparer_Expecter) Prepare() *mockagentRuntimeMigrationPreparer_Prepare_Call {
	return &mockagentRuntimeMigrationPreparer_Prepare_Call{Call: _e.mock.On("Prepare")}
}

func (_c *mockagentRuntimeMigrationPreparer_Prepare_Call) Run(run func()) *mockagentRuntimeMigrationPreparer_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockagentRuntimeMigrationPreparer_Prepare_Call) Return(agentRuntimeMigrationComponentsMoqParam agentRuntimeMigrationComponents, err error) *mockagentRuntimeMigrationPreparer_Prepare_Call {
	_c.Call.Return(agentRuntimeMigrationComponentsMoqParam, err)
	return _c
}

func (_c *mockagentRuntimeMigrationPreparer_Prepare_Call) RunAndReturn(run func() (agentRuntimeMigrationComponents, error)) *mockagentRuntimeMigrationPreparer_Prepare_Call {
	_c.Call.Return(run)
	return _c
}
