// Code generated by apigen DO NOT EDIT.

package handlers

import (
	"net/http"
	"time"

	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/internal"
)

// Below is to workaround unused imports if that happens.
var _ = BindingContext{}
var _ = http.MethodGet
var _ = time.Time{}
type _ func() AccessTokenCreateRequest

type paramsParserAuthAuthLogin struct {
	bindPayload requestParamBinder[*http.Request, *AuthLoginRequest]
}

func (p *paramsParserAuthAuthLogin) parse(router httpRouter, req *http.Request) (*AuthLoginParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &AuthLoginParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserAuthAuthLogin(rootHandler *RootHandler) paramsParser[*AuthLoginParams] {
	return &paramsParserAuthAuthLogin{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *AuthLoginRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*AuthLoginRequest],
			),
			validateValue: NewAuthLoginRequestValidator(),
		}),
	}
}

type paramsParserAuthAuthRefresh struct {
	bindPayload requestParamBinder[*http.Request, *AuthRefreshRequest]
}

func (p *paramsParserAuthAuthRefresh) parse(router httpRouter, req *http.Request) (*AuthRefreshParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &AuthRefreshParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserAuthAuthRefresh(rootHandler *RootHandler) paramsParser[*AuthRefreshParams] {
	return &paramsParserAuthAuthRefresh{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *AuthRefreshRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*AuthRefreshRequest],
			),
			validateValue: NewAuthRefreshRequestValidator(),
		}),
	}
}

type paramsParserAuthCreateAuthAccessToken struct {
	bindPayload requestParamBinder[*http.Request, *AccessTokenCreateRequest]
}

func (p *paramsParserAuthCreateAuthAccessToken) parse(router httpRouter, req *http.Request) (*CreateAuthAccessTokenParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &CreateAuthAccessTokenParams{}
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserAuthCreateAuthAccessToken(rootHandler *RootHandler) paramsParser[*CreateAuthAccessTokenParams] {
	return &paramsParserAuthCreateAuthAccessToken{
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *AccessTokenCreateRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*AccessTokenCreateRequest],
			),
			validateValue: NewAccessTokenCreateRequestValidator(),
		}),
	}
}

type paramsParserAuthRevokeAuthAccessToken struct {
	bindTokenID requestParamBinder[string, string]
}

func (p *paramsParserAuthRevokeAuthAccessToken) parse(router httpRouter, req *http.Request) (*RevokeAuthAccessTokenParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &RevokeAuthAccessTokenParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindTokenID(pathParamsCtx.Fork("tokenId"), readPathValue("tokenId", router, req), &reqParams.TokenID)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserAuthRevokeAuthAccessToken(rootHandler *RootHandler) paramsParser[*RevokeAuthAccessTokenParams] {
	return &paramsParserAuthRevokeAuthAccessToken{
		bindTokenID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
	}
}

type paramsParserAuthRotateAuthAccessToken struct {
	bindTokenID requestParamBinder[string, string]
	bindPayload requestParamBinder[*http.Request, *AccessTokenRotateRequest]
}

func (p *paramsParserAuthRotateAuthAccessToken) parse(router httpRouter, req *http.Request) (*RotateAuthAccessTokenParams, error) {
	bindingCtx := BindingContext{}
	reqParams := &RotateAuthAccessTokenParams{}
	// path params
	pathParamsCtx := bindingCtx.Fork("path")
	p.bindTokenID(pathParamsCtx.Fork("tokenId"), readPathValue("tokenId", router, req), &reqParams.TokenID)
	// body params
	p.bindPayload(bindingCtx.Fork("body"), readRequestBodyValue(req), &reqParams.Payload)
	return reqParams, bindingCtx.AggregatedError()
}

func newParamsParserAuthRotateAuthAccessToken(rootHandler *RootHandler) paramsParser[*RotateAuthAccessTokenParams] {
	return &paramsParserAuthRotateAuthAccessToken{
		bindTokenID: newRequestParamBinder(binderParams[string, string]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				rootHandler.knownParsers.stringParser,
			),
			validateValue: NewSimpleFieldValidator[string](
			),
		}),
		bindPayload: newRequestParamBinder(binderParams[*http.Request, *AccessTokenRotateRequest]{
			required: true,
			parseValue: parseSoloValueParamAsSoloValue(
				parseJSONPayload[*AccessTokenRotateRequest],
			),
			validateValue: NewAccessTokenRotateRequestValidator(),
		}),
	}
}

type authControllerBuilder struct {
	// POST /api/v1/auth/login
	//
	// Request type: AuthLoginParams,
	//
	// Response type: AuthSessionResponse
	AuthLogin genericHandlerBuilder[
		*AuthLoginParams,
		*AuthSessionResponse,
		handlerActionFunc[*AuthLoginParams, *AuthSessionResponse],
		httpHandlerActionFunc[*AuthLoginParams, *AuthSessionResponse],
	]

	// GET /api/v1/auth/me
	//
	// Request type: none
	//
	// Response type: UserInfo
	AuthMe genericHandlerBuilder[
		void,
		*UserInfo,
		handlerActionFuncNoParams[void, *UserInfo],
		httpHandlerActionFuncNoParams[void, *UserInfo],
	]

	// POST /api/v1/auth/refresh
	//
	// Request type: AuthRefreshParams,
	//
	// Response type: AuthSessionResponse
	AuthRefresh genericHandlerBuilder[
		*AuthRefreshParams,
		*AuthSessionResponse,
		handlerActionFunc[*AuthRefreshParams, *AuthSessionResponse],
		httpHandlerActionFunc[*AuthRefreshParams, *AuthSessionResponse],
	]

	// POST /api/v1/auth/access-tokens
	//
	// Request type: CreateAuthAccessTokenParams,
	//
	// Response type: AccessTokenIssuedResponse
	CreateAuthAccessToken genericHandlerBuilder[
		*CreateAuthAccessTokenParams,
		*AccessTokenIssuedResponse,
		handlerActionFunc[*CreateAuthAccessTokenParams, *AccessTokenIssuedResponse],
		httpHandlerActionFunc[*CreateAuthAccessTokenParams, *AccessTokenIssuedResponse],
	]

	// GET /api/v1/auth/access-tokens
	//
	// Request type: none
	//
	// Response type: AccessTokenListResponse
	ListAuthAccessTokens genericHandlerBuilder[
		void,
		*AccessTokenListResponse,
		handlerActionFuncNoParams[void, *AccessTokenListResponse],
		httpHandlerActionFuncNoParams[void, *AccessTokenListResponse],
	]

	// DELETE /api/v1/auth/access-tokens/{tokenId}
	//
	// Request type: RevokeAuthAccessTokenParams,
	//
	// Response type: none
	RevokeAuthAccessToken genericHandlerBuilder[
		*RevokeAuthAccessTokenParams,
		void,
		handlerActionFuncNoResponse[*RevokeAuthAccessTokenParams, void],
		httpHandlerActionFuncNoResponse[*RevokeAuthAccessTokenParams, void],
	]

	// POST /api/v1/auth/access-tokens/{tokenId}/rotate
	//
	// Request type: RotateAuthAccessTokenParams,
	//
	// Response type: AccessTokenIssuedResponse
	RotateAuthAccessToken genericHandlerBuilder[
		*RotateAuthAccessTokenParams,
		*AccessTokenIssuedResponse,
		handlerActionFunc[*RotateAuthAccessTokenParams, *AccessTokenIssuedResponse],
		httpHandlerActionFunc[*RotateAuthAccessTokenParams, *AccessTokenIssuedResponse],
	]
}

func newAuthControllerBuilder(app *RootHandler) *authControllerBuilder {
	return &authControllerBuilder{
		// POST /api/v1/auth/login
		AuthLogin: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*AuthLoginParams,
				*AuthSessionResponse,
			](),
			newHTTPHandlerAdapter[
				*AuthLoginParams,
				*AuthSessionResponse,
			](),
			makeActionBuilderParams[
				*AuthLoginParams,
				*AuthSessionResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserAuthAuthLogin(app),
			},
		),

		// GET /api/v1/auth/me
		AuthMe: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoParams[
				void,
				*UserInfo,
			](),
			newHTTPHandlerAdapterNoParams[
				void,
				*UserInfo,
			](),
			makeActionBuilderParams[
				void,
				*UserInfo,
			]{
				defaultStatus: 200,
				paramsParser:  makeVoidParamsParser(app),
			},
		),

		// POST /api/v1/auth/refresh
		AuthRefresh: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*AuthRefreshParams,
				*AuthSessionResponse,
			](),
			newHTTPHandlerAdapter[
				*AuthRefreshParams,
				*AuthSessionResponse,
			](),
			makeActionBuilderParams[
				*AuthRefreshParams,
				*AuthSessionResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserAuthAuthRefresh(app),
			},
		),

		// POST /api/v1/auth/access-tokens
		CreateAuthAccessToken: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*CreateAuthAccessTokenParams,
				*AccessTokenIssuedResponse,
			](),
			newHTTPHandlerAdapter[
				*CreateAuthAccessTokenParams,
				*AccessTokenIssuedResponse,
			](),
			makeActionBuilderParams[
				*CreateAuthAccessTokenParams,
				*AccessTokenIssuedResponse,
			]{
				defaultStatus: 201,
				paramsParser:  newParamsParserAuthCreateAuthAccessToken(app),
			},
		),

		// GET /api/v1/auth/access-tokens
		ListAuthAccessTokens: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoParams[
				void,
				*AccessTokenListResponse,
			](),
			newHTTPHandlerAdapterNoParams[
				void,
				*AccessTokenListResponse,
			](),
			makeActionBuilderParams[
				void,
				*AccessTokenListResponse,
			]{
				defaultStatus: 200,
				paramsParser:  makeVoidParamsParser(app),
			},
		),

		// DELETE /api/v1/auth/access-tokens/{tokenId}
		RevokeAuthAccessToken: newGenericHandlerBuilder(
			app,
			newHandlerAdapterNoResponse[
				*RevokeAuthAccessTokenParams,
				void,
			](),
			newHTTPHandlerAdapterNoResponse[
				*RevokeAuthAccessTokenParams,
				void,
			](),
			makeActionBuilderParams[
				*RevokeAuthAccessTokenParams,
				void,
			]{
				defaultStatus: 204,
				voidResult:    true,
				paramsParser:  newParamsParserAuthRevokeAuthAccessToken(app),
			},
		),

		// POST /api/v1/auth/access-tokens/{tokenId}/rotate
		RotateAuthAccessToken: newGenericHandlerBuilder(
			app,
			newHandlerAdapter[
				*RotateAuthAccessTokenParams,
				*AccessTokenIssuedResponse,
			](),
			newHTTPHandlerAdapter[
				*RotateAuthAccessTokenParams,
				*AccessTokenIssuedResponse,
			](),
			makeActionBuilderParams[
				*RotateAuthAccessTokenParams,
				*AccessTokenIssuedResponse,
			]{
				defaultStatus: 200,
				paramsParser:  newParamsParserAuthRotateAuthAccessToken(app),
			},
		),
	}
}
