#!/usr/bin/env bash
# Generate OpenCode crew-manager agents from the adjacent config.yaml.
# Usage: ./sync-opencode-agents.sh [path-to-yaml]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
MANAGER_PROMPTS_DIR="$SCRIPT_DIR"
CONFIG="${1:-$MANAGER_PROMPTS_DIR/config.yaml}"
AGENTS_DIR="$REPO_ROOT/.opencode/agents"

if [[ ! -f "$CONFIG" ]]; then
  echo "error: config not found: $CONFIG" >&2
  exit 1
fi

mkdir -p "$AGENTS_DIR"

mapfile -t written < <(python3 - "$CONFIG" "$AGENTS_DIR" "$MANAGER_PROMPTS_DIR" "$REPO_ROOT" <<'PY'
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("error: PyYAML is required (pip install pyyaml)")

config_path = Path(sys.argv[1]).resolve()
agents_dir = Path(sys.argv[2])
manager_prompts_dir = Path(sys.argv[3]).resolve()
repo_root = Path(sys.argv[4]).resolve()

try:
    manager_prompts_rel = manager_prompts_dir.relative_to(repo_root)
except ValueError:
    sys.exit(f"error: crew-manager directory must be inside repository root {repo_root}")
try:
    config_rel = config_path.relative_to(repo_root)
except ValueError:
    sys.exit(f"error: config must be inside repository root {repo_root}")

manager_prompt_prefix = f"./{manager_prompts_rel.as_posix()}"
config_prompt_path = f"./{config_rel.as_posix()}"

with config_path.open(encoding="utf-8") as f:
    config = yaml.safe_load(f) or {}

manager = config.get("manager")
if not isinstance(manager, dict):
    sys.exit(f"error: manager block is required in {config_path}")

manager_name = manager.get("agent_name")
manager_description = manager.get("description")
manager_model = manager.get("model")
manager_opencode_model = manager.get("opencode_model") or manager.get("opencodeModel")
manager_reasoning = manager.get("reasoning_effort") or manager.get("reasoningEffort")
if not manager_name:
    sys.exit("error: manager.agent_name is required")
if not manager_description:
    sys.exit("error: manager.description is required")
if not manager_model:
    sys.exit("error: manager.model is required")
if not manager_opencode_model:
    sys.exit("error: manager.opencode_model is required")
if not manager_reasoning:
    sys.exit("error: manager.reasoning_effort is required")

sub_agents = config.get("sub-agents") or config.get("sub_agents")
if not isinstance(sub_agents, dict) or not sub_agents:
    sys.exit(f"error: no sub-agents found in {config_path}")

def write_agent(path: Path, frontmatter: dict, extra_lines: list[str]) -> None:
    body = yaml.safe_dump(frontmatter, sort_keys=False).strip()
    lines = ["---", body, "---", ""]
    lines.extend(extra_lines)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

written = []
generated_marker = (
    "Generated by crew-manager sync; edit its config.yaml and re-run."
)

manager_frontmatter = {
    "name": manager_name,
    "description": manager_description,
    "mode": "primary",
    "model": manager_opencode_model,
    "reasoningEffort": manager_reasoning,
    "permission": {
        "*": "deny",
        "glob": "allow",
        "grep": "allow",
        "list": "allow",
        "todowrite": "allow",
        "question": "allow",
        "skill": {
            "*": "deny",
            "notion-user": "allow",
        },
        "read": {
            "*": "deny",
            "./**/*.md": "allow",
            config_prompt_path: "allow",
        },
        "edit": {
            "*": "deny",
            "tmp/crew-manager/**/*.*": "allow",
        },
        "bash": {
            "*": "deny",
        },
        "task": {
            "*": "deny",
            "crew-*": "allow",
        },
        "webfetch": "deny",
        "lsp": "deny",
        "external_directory": "deny",
    },
}
manager_extra = [
    f"<!-- {generated_marker} -->",
    "",
    f"Read `@{manager_prompt_prefix}/manager.md` first and follow it as the workflow contract.",
    f"Read `@{config_prompt_path}` before delegating.",
]
manager_path = agents_dir / f"{manager_name}.md"
write_agent(manager_path, manager_frontmatter, manager_extra)
written.append(manager_path)

for role, settings in sub_agents.items():
    if not isinstance(settings, dict):
        sys.exit(f"error: sub-agents.{role} must be a mapping")

    agent_id = settings.get("sub_agent_name")
    description = settings.get("description")
    model = settings.get("model")
    opencode_model = settings.get("opencode_model") or settings.get("opencodeModel")
    reasoning = settings.get("reasoning_effort") or settings.get("reasoningEffort")
    if not agent_id:
        sys.exit(f"error: sub-agents.{role}.sub_agent_name is required")
    if not description:
        sys.exit(f"error: sub-agents.{role}.description is required")
    if not model:
        sys.exit(f"error: sub-agents.{role}.model is required")
    if not opencode_model:
        sys.exit(f"error: sub-agents.{role}.opencode_model is required")
    if not reasoning:
        sys.exit(f"error: sub-agents.{role}.reasoning_effort is required")

    frontmatter = {
        "name": agent_id,
        "description": description,
        "mode": "subagent",
        "model": opencode_model,
        "reasoningEffort": reasoning,
        "permission": {
            "*": "allow",
        },
    }
    extra = [
        f"<!-- crew-role: {role}; crew-agent: {agent_id} -->",
        f"<!-- {generated_marker} -->",
        "",
        f"Read `@{manager_prompt_prefix}/shared-rules.md` first and follow it.",
    ]

    out_path = agents_dir / f"{agent_id}.md"
    write_agent(out_path, frontmatter, extra)
    written.append(out_path)

written_set = set(written)
for path in agents_dir.glob("*.md"):
    if path in written_set:
        continue
    content = path.read_text(encoding="utf-8")
    if generated_marker in content:
        path.unlink()

for path in sorted(written):
    print(path)
PY
)

echo "Synced ${#written[@]} OpenCode agents into $AGENTS_DIR"
for path in "${written[@]}"; do
  echo "  $path"
done
