// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// AcceptFinanceTenantInviteParams - Parameters for the acceptFinanceTenantInvite operation.
type AcceptFinanceTenantInviteParams struct { 
	Payload *FinanceAcceptInviteRequest `json:"payload"`
}
