// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type CandleAvailabilityListResponse struct { 
	Items []*CandleAvailabilityItem `json:"items"`
	NextCursor string `json:"nextCursor,omitempty"`
	DefaultSelection *CandleAvailabilityDefaultSelection `json:"defaultSelection,omitempty"`
}
