// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type CreateStrategyVersionRequest struct { 
	StrategyID string `json:"strategyId"`
	Version string `json:"version"`
	DisplayName string `json:"displayName"`
	Notes string `json:"notes,omitempty"`
	ParentStrategyID string `json:"parentStrategyId,omitempty"`
	ParentVersion string `json:"parentVersion,omitempty"`
	Definition *StrategyDefinition `json:"definition"`
}
