// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// CreateStrategyVersionParams - Parameters for the createStrategyVersion operation.
type CreateStrategyVersionParams struct { 
	Payload *CreateStrategyVersionRequest `json:"payload"`
}
