// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// CreateHistoricalDataBackfillJobParams - Parameters for the createHistoricalDataBackfillJob operation.
type CreateHistoricalDataBackfillJobParams struct { 
	Payload *CreateHistoricalDataBackfillJobRequest `json:"payload"`
}
