// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// CreateFinanceTenantParams - Parameters for the createFinanceTenant operation.
type CreateFinanceTenantParams struct { 
	Payload *FinanceTenantCreateRequest `json:"payload"`
}
