// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceBankConnection struct { 
	ID string `json:"id"`
	TenantID string `json:"tenantId"`
	Provider string `json:"provider"`
	DisplayName string `json:"displayName"`
	ProviderReference string `json:"providerReference"`
	ExternalID string `json:"externalId"`
	State string `json:"state"`
	LastSyncJobID string `json:"lastSyncJobId,omitempty"`
	LastSyncStartedAt time.Time `json:"lastSyncStartedAt,omitempty"`
	LastSuccessfulSyncAt time.Time `json:"lastSuccessfulSyncAt,omitempty"`
	LastSyncError string `json:"lastSyncError,omitempty"`
	Schedule *FinanceBankConnectionSchedule `json:"schedule,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
