// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceAccountCsvImportPreviewResponse struct { 
	ImportID string `json:"importId"`
	Headers []string `json:"headers"`
	RejectedRows []*FinanceCsvImportRowDiagnostic `json:"rejectedRows"`
	WouldCreateAccounts []string `json:"wouldCreateAccounts"`
}
