// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceCsvImportPreviewRequest struct { 
	ImportType string `json:"importType"`
	FileName string `json:"fileName"`
	Csv string `json:"csv"`
}
