// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceCsvImportRowOutcome struct { 
	RowNumber int64 `json:"rowNumber"`
	TransactionID string `json:"transactionId,omitempty"`
	Status string `json:"status"`
	Reason string `json:"reason"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
