// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceDashboardPeriod struct { 
	Preset string `json:"preset"`
	StartDate time.Time `json:"startDate"`
	EndDate time.Time `json:"endDate"`
	Previous *FinanceDashboardPeriodWindow `json:"previous"`
	Next *FinanceDashboardPeriodWindow `json:"next"`
}
