// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceDashboardMissingFx struct { 
	Source string `json:"source"`
	TransactionID *string `json:"transactionId"`
	AccountID *string `json:"accountId"`
	BaseCurrency string `json:"baseCurrency"`
	QuoteCurrency string `json:"quoteCurrency"`
	RateDate time.Time `json:"rateDate"`
	Provider string `json:"provider"`
}
