// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type FinanceTag struct { 
	ID string `json:"id"`
	TenantID string `json:"tenantId"`
	Name string `json:"name"`
	HiddenAt *time.Time `json:"hiddenAt,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
