// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// GetStrategyVersionParams - Parameters for the getStrategyVersion operation.
type GetStrategyVersionParams struct { 
	StrategyID string `json:"strategyId"`
	Version string `json:"version"`
}
