// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// GetFinanceCsvImportAuditParams - Parameters for the getFinanceCsvImportAudit operation.
type GetFinanceCsvImportAuditParams struct { 
	TenantID string `json:"tenantId"`
	ImportID string `json:"importId"`
}
