// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// GetDataRawPayloadParams - Parameters for the getDataRawPayload operation.
type GetDataRawPayloadParams struct { 
	ID string `json:"id"`
}
