// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// GetFinanceDashboardParams - Parameters for the getFinanceDashboard operation.
type GetFinanceDashboardParams struct { 
	TenantID string `json:"tenantId"`
	Preset string `json:"preset,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	EndDate string `json:"endDate,omitempty"`
}
