// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

type JobSummary struct { 
	ID string `json:"id"`
	JobType string `json:"jobType"`
	Status string `json:"status"`
	Requester *JobRequester `json:"requester"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	StartedAt *time.Time `json:"startedAt,omitempty"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	AttemptCount int64 `json:"attemptCount"`
	Error *JobError `json:"error,omitempty"`
}
