// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListDataCandlesParams - Parameters for the listDataCandles operation.
type ListDataCandlesParams struct { 
	Venue string `json:"venue"`
	Symbol string `json:"symbol"`
	AssetClass string `json:"assetClass"`
	Timeframe string `json:"timeframe"`
	Start time.Time `json:"start"`
	End time.Time `json:"end"`
}
