// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListJobsParams - Parameters for the listJobs operation.
type ListJobsParams struct { 
	Status []string `json:"status,omitempty"`
	JobType []string `json:"jobType,omitempty"`
	Source []string `json:"source,omitempty"`
	Limit int64 `json:"limit,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
