// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListDataRawPayloadsParams - Parameters for the listDataRawPayloads operation.
type ListDataRawPayloadsParams struct { 
	Venue string `json:"venue"`
	Symbol string `json:"symbol,omitempty"`
	AssetClass string `json:"assetClass,omitempty"`
	Timeframe string `json:"timeframe,omitempty"`
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	IngestionRunID string `json:"ingestionRunId,omitempty"`
	EntityHint string `json:"entityHint,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	RequestType string `json:"requestType,omitempty"`
	Limit int64 `json:"limit,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
