// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListFinanceTransferCandidatesParams - Parameters for the listFinanceTransferCandidates operation.
type ListFinanceTransferCandidatesParams struct { 
	TenantID string `json:"tenantId"`
	TransactionID string `json:"transactionId"`
	EffectiveFrom time.Time `json:"effectiveFrom"`
	EffectiveBefore time.Time `json:"effectiveBefore"`
	Limit int64 `json:"limit"`
	Offset int64 `json:"offset,omitempty"`
}
