// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListFinanceAccountsParams - Parameters for the listFinanceAccounts operation.
type ListFinanceAccountsParams struct { 
	TenantID string `json:"tenantId"`
	IncludeHidden bool `json:"includeHidden,omitempty"`
}
