// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// ListDataCandleAvailabilityParams - Parameters for the listDataCandleAvailability operation.
type ListDataCandleAvailabilityParams struct { 
	Venue string `json:"venue,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	AssetClass string `json:"assetClass,omitempty"`
	Limit int64 `json:"limit,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
