// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// UpdateFinanceAccountParams - Parameters for the updateFinanceAccount operation.
type UpdateFinanceAccountParams struct { 
	TenantID string `json:"tenantId"`
	AccountID string `json:"accountId"`
	Payload *FinanceRenameRequest `json:"payload"`
}
