// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package jobs

import (
	"context"
	"time"

	"github.com/gemyago/sumweave/apps/sumweave/internal/appdispatch"
	mock "github.com/stretchr/testify/mock"
)

// newMockjobReader creates a new instance of mockjobReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjobReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjobReader {
	mock := &mockjobReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjobReader is an autogenerated mock type for the jobReader type
type mockjobReader struct {
	mock.Mock
}

type mockjobReader_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjobReader) EXPECT() *mockjobReader_Expecter {
	return &mockjobReader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type mockjobReader
func (_mock *mockjobReader) Get(context1 context.Context, s string) (*Job, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Job, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Job); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjobReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockjobReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *mockjobReader_Expecter) Get(context1 any, s any) *mockjobReader_Get_Call {
	return &mockjobReader_Get_Call{Call: _e.mock.On("Get", context1, s)}
}

func (_c *mockjobReader_Get_Call) Run(run func(context1 context.Context, s string)) *mockjobReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockjobReader_Get_Call) Return(job *Job, err error) *mockjobReader_Get_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *mockjobReader_Get_Call) RunAndReturn(run func(context1 context.Context, s string) (*Job, error)) *mockjobReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockjobReader
func (_mock *mockjobReader) List(context1 context.Context, listParams ListParams) (ListResult, error) {
	ret := _mock.Called(context1, listParams)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 ListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListParams) (ListResult, error)); ok {
		return returnFunc(context1, listParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListParams) ListResult); ok {
		r0 = returnFunc(context1, listParams)
	} else {
		r0 = ret.Get(0).(ListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListParams) error); ok {
		r1 = returnFunc(context1, listParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjobReader_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockjobReader_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - listParams ListParams
func (_e *mockjobReader_Expecter) List(context1 any, listParams any) *mockjobReader_List_Call {
	return &mockjobReader_List_Call{Call: _e.mock.On("List", context1, listParams)}
}

func (_c *mockjobReader_List_Call) Run(run func(context1 context.Context, listParams ListParams)) *mockjobReader_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListParams
		if args[1] != nil {
			arg1 = args[1].(ListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockjobReader_List_Call) Return(listResult ListResult, err error) *mockjobReader_List_Call {
	_c.Call.Return(listResult, err)
	return _c
}

func (_c *mockjobReader_List_Call) RunAndReturn(run func(context1 context.Context, listParams ListParams) (ListResult, error)) *mockjobReader_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkerStore creates a new instance of mockworkerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerStore {
	mock := &mockworkerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkerStore is an autogenerated mock type for the workerStore type
type mockworkerStore struct {
	mock.Mock
}

type mockworkerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerStore) EXPECT() *mockworkerStore_Expecter {
	return &mockworkerStore_Expecter{mock: &_m.Mock}
}

// ClaimQueued provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) ClaimQueued(context1 context.Context, s string, s1 string, time1 time.Time) (*Job, error) {
	ret := _mock.Called(context1, s, s1, time1)

	if len(ret) == 0 {
		panic("no return value specified for ClaimQueued")
	}

	var r0 *Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*Job, error)); ok {
		return returnFunc(context1, s, s1, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *Job); ok {
		r0 = returnFunc(context1, s, s1, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(context1, s, s1, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerStore_ClaimQueued_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimQueued'
type mockworkerStore_ClaimQueued_Call struct {
	*mock.Call
}

// ClaimQueued is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) ClaimQueued(context1 any, s any, s1 any, time1 any) *mockworkerStore_ClaimQueued_Call {
	return &mockworkerStore_ClaimQueued_Call{Call: _e.mock.On("ClaimQueued", context1, s, s1, time1)}
}

func (_c *mockworkerStore_ClaimQueued_Call) Run(run func(context1 context.Context, s string, s1 string, time1 time.Time)) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_ClaimQueued_Call) Return(job *Job, err error) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *mockworkerStore_ClaimQueued_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, time1 time.Time) (*Job, error)) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizeRetryExhausted provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) FinalizeRetryExhausted(context1 context.Context, s string, time1 time.Time, terminalJobStateMoqParam terminalJobState) error {
	ret := _mock.Called(context1, s, time1, terminalJobStateMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeRetryExhausted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, terminalJobState) error); ok {
		r0 = returnFunc(context1, s, time1, terminalJobStateMoqParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_FinalizeRetryExhausted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeRetryExhausted'
type mockworkerStore_FinalizeRetryExhausted_Call struct {
	*mock.Call
}

// FinalizeRetryExhausted is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - time1 time.Time
//   - terminalJobStateMoqParam terminalJobState
func (_e *mockworkerStore_Expecter) FinalizeRetryExhausted(context1 any, s any, time1 any, terminalJobStateMoqParam any) *mockworkerStore_FinalizeRetryExhausted_Call {
	return &mockworkerStore_FinalizeRetryExhausted_Call{Call: _e.mock.On("FinalizeRetryExhausted", context1, s, time1, terminalJobStateMoqParam)}
}

func (_c *mockworkerStore_FinalizeRetryExhausted_Call) Run(run func(context1 context.Context, s string, time1 time.Time, terminalJobStateMoqParam terminalJobState)) *mockworkerStore_FinalizeRetryExhausted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 terminalJobState
		if args[3] != nil {
			arg3 = args[3].(terminalJobState)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_FinalizeRetryExhausted_Call) Return(err error) *mockworkerStore_FinalizeRetryExhausted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_FinalizeRetryExhausted_Call) RunAndReturn(run func(context1 context.Context, s string, time1 time.Time, terminalJobStateMoqParam terminalJobState) error) *mockworkerStore_FinalizeRetryExhausted_Call {
	_c.Call.Return(run)
	return _c
}

// MaterializeQueued provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) MaterializeQueued(context1 context.Context, job Job) (*Job, error) {
	ret := _mock.Called(context1, job)

	if len(ret) == 0 {
		panic("no return value specified for MaterializeQueued")
	}

	var r0 *Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job) (*Job, error)); ok {
		return returnFunc(context1, job)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job) *Job); ok {
		r0 = returnFunc(context1, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Job) error); ok {
		r1 = returnFunc(context1, job)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerStore_MaterializeQueued_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaterializeQueued'
type mockworkerStore_MaterializeQueued_Call struct {
	*mock.Call
}

// MaterializeQueued is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
func (_e *mockworkerStore_Expecter) MaterializeQueued(context1 any, job any) *mockworkerStore_MaterializeQueued_Call {
	return &mockworkerStore_MaterializeQueued_Call{Call: _e.mock.On("MaterializeQueued", context1, job)}
}

func (_c *mockworkerStore_MaterializeQueued_Call) Run(run func(context1 context.Context, job Job)) *mockworkerStore_MaterializeQueued_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkerStore_MaterializeQueued_Call) Return(job1 *Job, err error) *mockworkerStore_MaterializeQueued_Call {
	_c.Call.Return(job1, err)
	return _c
}

func (_c *mockworkerStore_MaterializeQueued_Call) RunAndReturn(run func(context1 context.Context, job Job) (*Job, error)) *mockworkerStore_MaterializeQueued_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverStaleRunning provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) RecoverStaleRunning(context1 context.Context, time1 time.Time, duration time.Duration, n int) error {
	ret := _mock.Called(context1, time1, duration, n)

	if len(ret) == 0 {
		panic("no return value specified for RecoverStaleRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) error); ok {
		r0 = returnFunc(context1, time1, duration, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_RecoverStaleRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverStaleRunning'
type mockworkerStore_RecoverStaleRunning_Call struct {
	*mock.Call
}

// RecoverStaleRunning is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 time.Time
//   - duration time.Duration
//   - n int
func (_e *mockworkerStore_Expecter) RecoverStaleRunning(context1 any, time1 any, duration any, n any) *mockworkerStore_RecoverStaleRunning_Call {
	return &mockworkerStore_RecoverStaleRunning_Call{Call: _e.mock.On("RecoverStaleRunning", context1, time1, duration, n)}
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) Run(run func(context1 context.Context, time1 time.Time, duration time.Duration, n int)) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) Return(err error) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) RunAndReturn(run func(context1 context.Context, time1 time.Time, duration time.Duration, n int) error) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Return(run)
	return _c
}

// RenewRunning provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) RenewRunning(context1 context.Context, job Job, time1 time.Time) error {
	ret := _mock.Called(context1, job, time1)

	if len(ret) == 0 {
		panic("no return value specified for RenewRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job, time.Time) error); ok {
		r0 = returnFunc(context1, job, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_RenewRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewRunning'
type mockworkerStore_RenewRunning_Call struct {
	*mock.Call
}

// RenewRunning is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) RenewRunning(context1 any, job any, time1 any) *mockworkerStore_RenewRunning_Call {
	return &mockworkerStore_RenewRunning_Call{Call: _e.mock.On("RenewRunning", context1, job, time1)}
}

func (_c *mockworkerStore_RenewRunning_Call) Run(run func(context1 context.Context, job Job, time1 time.Time)) *mockworkerStore_RenewRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockworkerStore_RenewRunning_Call) Return(err error) *mockworkerStore_RenewRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_RenewRunning_Call) RunAndReturn(run func(context1 context.Context, job Job, time1 time.Time) error) *mockworkerStore_RenewRunning_Call {
	_c.Call.Return(run)
	return _c
}

// RequeueRunning provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) RequeueRunning(context1 context.Context, job Job, time1 time.Time) error {
	ret := _mock.Called(context1, job, time1)

	if len(ret) == 0 {
		panic("no return value specified for RequeueRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job, time.Time) error); ok {
		r0 = returnFunc(context1, job, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_RequeueRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequeueRunning'
type mockworkerStore_RequeueRunning_Call struct {
	*mock.Call
}

// RequeueRunning is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) RequeueRunning(context1 any, job any, time1 any) *mockworkerStore_RequeueRunning_Call {
	return &mockworkerStore_RequeueRunning_Call{Call: _e.mock.On("RequeueRunning", context1, job, time1)}
}

func (_c *mockworkerStore_RequeueRunning_Call) Run(run func(context1 context.Context, job Job, time1 time.Time)) *mockworkerStore_RequeueRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockworkerStore_RequeueRunning_Call) Return(err error) *mockworkerStore_RequeueRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_RequeueRunning_Call) RunAndReturn(run func(context1 context.Context, job Job, time1 time.Time) error) *mockworkerStore_RequeueRunning_Call {
	_c.Call.Return(run)
	return _c
}

// persistTerminalState provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) persistTerminalState(context1 context.Context, job Job, terminalJobStateMoqParam terminalJobState) error {
	ret := _mock.Called(context1, job, terminalJobStateMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for persistTerminalState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job, terminalJobState) error); ok {
		r0 = returnFunc(context1, job, terminalJobStateMoqParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_persistTerminalState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'persistTerminalState'
type mockworkerStore_persistTerminalState_Call struct {
	*mock.Call
}

// persistTerminalState is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
//   - terminalJobStateMoqParam terminalJobState
func (_e *mockworkerStore_Expecter) persistTerminalState(context1 any, job any, terminalJobStateMoqParam any) *mockworkerStore_persistTerminalState_Call {
	return &mockworkerStore_persistTerminalState_Call{Call: _e.mock.On("persistTerminalState", context1, job, terminalJobStateMoqParam)}
}

func (_c *mockworkerStore_persistTerminalState_Call) Run(run func(context1 context.Context, job Job, terminalJobStateMoqParam terminalJobState)) *mockworkerStore_persistTerminalState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		var arg2 terminalJobState
		if args[2] != nil {
			arg2 = args[2].(terminalJobState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockworkerStore_persistTerminalState_Call) Return(err error) *mockworkerStore_persistTerminalState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_persistTerminalState_Call) RunAndReturn(run func(context1 context.Context, job Job, terminalJobStateMoqParam terminalJobState) error) *mockworkerStore_persistTerminalState_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkerRouter creates a new instance of mockworkerRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerRouter {
	mock := &mockworkerRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkerRouter is an autogenerated mock type for the workerRouter type
type mockworkerRouter struct {
	mock.Mock
}

type mockworkerRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerRouter) EXPECT() *mockworkerRouter_Expecter {
	return &mockworkerRouter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerRouter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockworkerRouter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockworkerRouter_Expecter) Close() *mockworkerRouter_Close_Call {
	return &mockworkerRouter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockworkerRouter_Close_Call) Run(run func()) *mockworkerRouter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockworkerRouter_Close_Call) Return(err error) *mockworkerRouter_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerRouter_Close_Call) RunAndReturn(run func() error) *mockworkerRouter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) Handle(handler appdispatch.Handler) error {
	ret := _mock.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(appdispatch.Handler) error); ok {
		r0 = returnFunc(handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerRouter_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockworkerRouter_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - handler appdispatch.Handler
func (_e *mockworkerRouter_Expecter) Handle(handler any) *mockworkerRouter_Handle_Call {
	return &mockworkerRouter_Handle_Call{Call: _e.mock.On("Handle", handler)}
}

func (_c *mockworkerRouter_Handle_Call) Run(run func(handler appdispatch.Handler)) *mockworkerRouter_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 appdispatch.Handler
		if args[0] != nil {
			arg0 = args[0].(appdispatch.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockworkerRouter_Handle_Call) Return(err error) *mockworkerRouter_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerRouter_Handle_Call) RunAndReturn(run func(handler appdispatch.Handler) error) *mockworkerRouter_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerRouter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockworkerRouter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockworkerRouter_Expecter) Run(context1 any) *mockworkerRouter_Run_Call {
	return &mockworkerRouter_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *mockworkerRouter_Run_Call) Run(run func(context1 context.Context)) *mockworkerRouter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockworkerRouter_Run_Call) Return(err error) *mockworkerRouter_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerRouter_Run_Call) RunAndReturn(run func(context1 context.Context) error) *mockworkerRouter_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SetRetryLifecycle provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) SetRetryLifecycle(retryLifecycle appdispatch.RetryLifecycle) error {
	ret := _mock.Called(retryLifecycle)

	if len(ret) == 0 {
		panic("no return value specified for SetRetryLifecycle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(appdispatch.RetryLifecycle) error); ok {
		r0 = returnFunc(retryLifecycle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerRouter_SetRetryLifecycle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRetryLifecycle'
type mockworkerRouter_SetRetryLifecycle_Call struct {
	*mock.Call
}

// SetRetryLifecycle is a helper method to define mock.On call
//   - retryLifecycle appdispatch.RetryLifecycle
func (_e *mockworkerRouter_Expecter) SetRetryLifecycle(retryLifecycle any) *mockworkerRouter_SetRetryLifecycle_Call {
	return &mockworkerRouter_SetRetryLifecycle_Call{Call: _e.mock.On("SetRetryLifecycle", retryLifecycle)}
}

func (_c *mockworkerRouter_SetRetryLifecycle_Call) Run(run func(retryLifecycle appdispatch.RetryLifecycle)) *mockworkerRouter_SetRetryLifecycle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 appdispatch.RetryLifecycle
		if args[0] != nil {
			arg0 = args[0].(appdispatch.RetryLifecycle)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockworkerRouter_SetRetryLifecycle_Call) Return(err error) *mockworkerRouter_SetRetryLifecycle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerRouter_SetRetryLifecycle_Call) RunAndReturn(run func(retryLifecycle appdispatch.RetryLifecycle) error) *mockworkerRouter_SetRetryLifecycle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkerRouterFactory creates a new instance of mockworkerRouterFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerRouterFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerRouterFactory {
	mock := &mockworkerRouterFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkerRouterFactory is an autogenerated mock type for the workerRouterFactory type
type mockworkerRouterFactory struct {
	mock.Mock
}

type mockworkerRouterFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerRouterFactory) EXPECT() *mockworkerRouterFactory_Expecter {
	return &mockworkerRouterFactory_Expecter{mock: &_m.Mock}
}

// NewRouter provides a mock function for the type mockworkerRouterFactory
func (_mock *mockworkerRouterFactory) NewRouter(s string) (workerRouterResult, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for NewRouter")
	}

	var r0 workerRouterResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (workerRouterResult, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) workerRouterResult); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(workerRouterResult)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerRouterFactory_NewRouter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRouter'
type mockworkerRouterFactory_NewRouter_Call struct {
	*mock.Call
}

// NewRouter is a helper method to define mock.On call
//   - s string
func (_e *mockworkerRouterFactory_Expecter) NewRouter(s any) *mockworkerRouterFactory_NewRouter_Call {
	return &mockworkerRouterFactory_NewRouter_Call{Call: _e.mock.On("NewRouter", s)}
}

func (_c *mockworkerRouterFactory_NewRouter_Call) Run(run func(s string)) *mockworkerRouterFactory_NewRouter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockworkerRouterFactory_NewRouter_Call) Return(workerRouterResultMoqParam workerRouterResult, err error) *mockworkerRouterFactory_NewRouter_Call {
	_c.Call.Return(workerRouterResultMoqParam, err)
	return _c
}

func (_c *mockworkerRouterFactory_NewRouter_Call) RunAndReturn(run func(s string) (workerRouterResult, error)) *mockworkerRouterFactory_NewRouter_Call {
	_c.Call.Return(run)
	return _c
}
