// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package jobs

import (
	"context"
	"time"

	"github.com/gemyago/sumweave/apps/sumweave/internal/appdispatch"
	mock "github.com/stretchr/testify/mock"
)

// newMockworkerStore creates a new instance of mockworkerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerStore {
	mock := &mockworkerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkerStore is an autogenerated mock type for the workerStore type
type mockworkerStore struct {
	mock.Mock
}

type mockworkerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerStore) EXPECT() *mockworkerStore_Expecter {
	return &mockworkerStore_Expecter{mock: &_m.Mock}
}

// ClaimQueued provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) ClaimQueued(context1 context.Context, s string, s1 string, time1 time.Time) (*Job, error) {
	ret := _mock.Called(context1, s, s1, time1)

	if len(ret) == 0 {
		panic("no return value specified for ClaimQueued")
	}

	var r0 *Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*Job, error)); ok {
		return returnFunc(context1, s, s1, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *Job); ok {
		r0 = returnFunc(context1, s, s1, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(context1, s, s1, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerStore_ClaimQueued_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimQueued'
type mockworkerStore_ClaimQueued_Call struct {
	*mock.Call
}

// ClaimQueued is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) ClaimQueued(context1 interface{}, s interface{}, s1 interface{}, time1 interface{}) *mockworkerStore_ClaimQueued_Call {
	return &mockworkerStore_ClaimQueued_Call{Call: _e.mock.On("ClaimQueued", context1, s, s1, time1)}
}

func (_c *mockworkerStore_ClaimQueued_Call) Run(run func(context1 context.Context, s string, s1 string, time1 time.Time)) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_ClaimQueued_Call) Return(job *Job, err error) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *mockworkerStore_ClaimQueued_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, time1 time.Time) (*Job, error)) *mockworkerStore_ClaimQueued_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizeRetryExhausted provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) FinalizeRetryExhausted(context1 context.Context, s string, time1 time.Time, terminalJobStateMoqParam terminalJobState) error {
	ret := _mock.Called(context1, s, time1, terminalJobStateMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeRetryExhausted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, terminalJobState) error); ok {
		r0 = returnFunc(context1, s, time1, terminalJobStateMoqParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_FinalizeRetryExhausted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizeRetryExhausted'
type mockworkerStore_FinalizeRetryExhausted_Call struct {
	*mock.Call
}

// FinalizeRetryExhausted is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - time1 time.Time
//   - terminalJobStateMoqParam terminalJobState
func (_e *mockworkerStore_Expecter) FinalizeRetryExhausted(context1 interface{}, s interface{}, time1 interface{}, terminalJobStateMoqParam interface{}) *mockworkerStore_FinalizeRetryExhausted_Call {
	return &mockworkerStore_FinalizeRetryExhausted_Call{Call: _e.mock.On("FinalizeRetryExhausted", context1, s, time1, terminalJobStateMoqParam)}
}

func (_c *mockworkerStore_FinalizeRetryExhausted_Call) Run(run func(context1 context.Context, s string, time1 time.Time, terminalJobStateMoqParam terminalJobState)) *mockworkerStore_FinalizeRetryExhausted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 terminalJobState
		if args[3] != nil {
			arg3 = args[3].(terminalJobState)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_FinalizeRetryExhausted_Call) Return(err error) *mockworkerStore_FinalizeRetryExhausted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_FinalizeRetryExhausted_Call) RunAndReturn(run func(context1 context.Context, s string, time1 time.Time, terminalJobStateMoqParam terminalJobState) error) *mockworkerStore_FinalizeRetryExhausted_Call {
	_c.Call.Return(run)
	return _c
}

// MaterializeQueued provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) MaterializeQueued(context1 context.Context, job Job) (*Job, error) {
	ret := _mock.Called(context1, job)

	if len(ret) == 0 {
		panic("no return value specified for MaterializeQueued")
	}

	var r0 *Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job) (*Job, error)); ok {
		return returnFunc(context1, job)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job) *Job); ok {
		r0 = returnFunc(context1, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Job) error); ok {
		r1 = returnFunc(context1, job)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockworkerStore_MaterializeQueued_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaterializeQueued'
type mockworkerStore_MaterializeQueued_Call struct {
	*mock.Call
}

// MaterializeQueued is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
func (_e *mockworkerStore_Expecter) MaterializeQueued(context1 interface{}, job interface{}) *mockworkerStore_MaterializeQueued_Call {
	return &mockworkerStore_MaterializeQueued_Call{Call: _e.mock.On("MaterializeQueued", context1, job)}
}

func (_c *mockworkerStore_MaterializeQueued_Call) Run(run func(context1 context.Context, job Job)) *mockworkerStore_MaterializeQueued_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockworkerStore_MaterializeQueued_Call) Return(job1 *Job, err error) *mockworkerStore_MaterializeQueued_Call {
	_c.Call.Return(job1, err)
	return _c
}

func (_c *mockworkerStore_MaterializeQueued_Call) RunAndReturn(run func(context1 context.Context, job Job) (*Job, error)) *mockworkerStore_MaterializeQueued_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverStaleRunning provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) RecoverStaleRunning(context1 context.Context, time1 time.Time, duration time.Duration, n int) error {
	ret := _mock.Called(context1, time1, duration, n)

	if len(ret) == 0 {
		panic("no return value specified for RecoverStaleRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Duration, int) error); ok {
		r0 = returnFunc(context1, time1, duration, n)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_RecoverStaleRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverStaleRunning'
type mockworkerStore_RecoverStaleRunning_Call struct {
	*mock.Call
}

// RecoverStaleRunning is a helper method to define mock.On call
//   - context1 context.Context
//   - time1 time.Time
//   - duration time.Duration
//   - n int
func (_e *mockworkerStore_Expecter) RecoverStaleRunning(context1 interface{}, time1 interface{}, duration interface{}, n interface{}) *mockworkerStore_RecoverStaleRunning_Call {
	return &mockworkerStore_RecoverStaleRunning_Call{Call: _e.mock.On("RecoverStaleRunning", context1, time1, duration, n)}
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) Run(run func(context1 context.Context, time1 time.Time, duration time.Duration, n int)) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) Return(err error) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_RecoverStaleRunning_Call) RunAndReturn(run func(context1 context.Context, time1 time.Time, duration time.Duration, n int) error) *mockworkerStore_RecoverStaleRunning_Call {
	_c.Call.Return(run)
	return _c
}

// RenewRunning provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) RenewRunning(context1 context.Context, job Job, time1 time.Time) error {
	ret := _mock.Called(context1, job, time1)

	if len(ret) == 0 {
		panic("no return value specified for RenewRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job, time.Time) error); ok {
		r0 = returnFunc(context1, job, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_RenewRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewRunning'
type mockworkerStore_RenewRunning_Call struct {
	*mock.Call
}

// RenewRunning is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) RenewRunning(context1 interface{}, job interface{}, time1 interface{}) *mockworkerStore_RenewRunning_Call {
	return &mockworkerStore_RenewRunning_Call{Call: _e.mock.On("RenewRunning", context1, job, time1)}
}

func (_c *mockworkerStore_RenewRunning_Call) Run(run func(context1 context.Context, job Job, time1 time.Time)) *mockworkerStore_RenewRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockworkerStore_RenewRunning_Call) Return(err error) *mockworkerStore_RenewRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_RenewRunning_Call) RunAndReturn(run func(context1 context.Context, job Job, time1 time.Time) error) *mockworkerStore_RenewRunning_Call {
	_c.Call.Return(run)
	return _c
}

// RequeueRunning provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) RequeueRunning(context1 context.Context, job Job, time1 time.Time) error {
	ret := _mock.Called(context1, job, time1)

	if len(ret) == 0 {
		panic("no return value specified for RequeueRunning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job, time.Time) error); ok {
		r0 = returnFunc(context1, job, time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_RequeueRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequeueRunning'
type mockworkerStore_RequeueRunning_Call struct {
	*mock.Call
}

// RequeueRunning is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
//   - time1 time.Time
func (_e *mockworkerStore_Expecter) RequeueRunning(context1 interface{}, job interface{}, time1 interface{}) *mockworkerStore_RequeueRunning_Call {
	return &mockworkerStore_RequeueRunning_Call{Call: _e.mock.On("RequeueRunning", context1, job, time1)}
}

func (_c *mockworkerStore_RequeueRunning_Call) Run(run func(context1 context.Context, job Job, time1 time.Time)) *mockworkerStore_RequeueRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockworkerStore_RequeueRunning_Call) Return(err error) *mockworkerStore_RequeueRunning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_RequeueRunning_Call) RunAndReturn(run func(context1 context.Context, job Job, time1 time.Time) error) *mockworkerStore_RequeueRunning_Call {
	_c.Call.Return(run)
	return _c
}

// persistTerminalState provides a mock function for the type mockworkerStore
func (_mock *mockworkerStore) persistTerminalState(context1 context.Context, job Job, terminalJobStateMoqParam terminalJobState) error {
	ret := _mock.Called(context1, job, terminalJobStateMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for persistTerminalState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Job, terminalJobState) error); ok {
		r0 = returnFunc(context1, job, terminalJobStateMoqParam)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerStore_persistTerminalState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'persistTerminalState'
type mockworkerStore_persistTerminalState_Call struct {
	*mock.Call
}

// persistTerminalState is a helper method to define mock.On call
//   - context1 context.Context
//   - job Job
//   - terminalJobStateMoqParam terminalJobState
func (_e *mockworkerStore_Expecter) persistTerminalState(context1 interface{}, job interface{}, terminalJobStateMoqParam interface{}) *mockworkerStore_persistTerminalState_Call {
	return &mockworkerStore_persistTerminalState_Call{Call: _e.mock.On("persistTerminalState", context1, job, terminalJobStateMoqParam)}
}

func (_c *mockworkerStore_persistTerminalState_Call) Run(run func(context1 context.Context, job Job, terminalJobStateMoqParam terminalJobState)) *mockworkerStore_persistTerminalState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Job
		if args[1] != nil {
			arg1 = args[1].(Job)
		}
		var arg2 terminalJobState
		if args[2] != nil {
			arg2 = args[2].(terminalJobState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockworkerStore_persistTerminalState_Call) Return(err error) *mockworkerStore_persistTerminalState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerStore_persistTerminalState_Call) RunAndReturn(run func(context1 context.Context, job Job, terminalJobStateMoqParam terminalJobState) error) *mockworkerStore_persistTerminalState_Call {
	_c.Call.Return(run)
	return _c
}

// newMockworkerRouter creates a new instance of mockworkerRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockworkerRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockworkerRouter {
	mock := &mockworkerRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockworkerRouter is an autogenerated mock type for the workerRouter type
type mockworkerRouter struct {
	mock.Mock
}

type mockworkerRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockworkerRouter) EXPECT() *mockworkerRouter_Expecter {
	return &mockworkerRouter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerRouter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockworkerRouter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockworkerRouter_Expecter) Close() *mockworkerRouter_Close_Call {
	return &mockworkerRouter_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockworkerRouter_Close_Call) Run(run func()) *mockworkerRouter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockworkerRouter_Close_Call) Return(err error) *mockworkerRouter_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerRouter_Close_Call) RunAndReturn(run func() error) *mockworkerRouter_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) Handle(handler appdispatch.Handler) error {
	ret := _mock.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(appdispatch.Handler) error); ok {
		r0 = returnFunc(handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerRouter_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockworkerRouter_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - handler appdispatch.Handler
func (_e *mockworkerRouter_Expecter) Handle(handler interface{}) *mockworkerRouter_Handle_Call {
	return &mockworkerRouter_Handle_Call{Call: _e.mock.On("Handle", handler)}
}

func (_c *mockworkerRouter_Handle_Call) Run(run func(handler appdispatch.Handler)) *mockworkerRouter_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 appdispatch.Handler
		if args[0] != nil {
			arg0 = args[0].(appdispatch.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockworkerRouter_Handle_Call) Return(err error) *mockworkerRouter_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerRouter_Handle_Call) RunAndReturn(run func(handler appdispatch.Handler) error) *mockworkerRouter_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockworkerRouter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockworkerRouter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockworkerRouter_Expecter) Run(context1 interface{}) *mockworkerRouter_Run_Call {
	return &mockworkerRouter_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *mockworkerRouter_Run_Call) Run(run func(context1 context.Context)) *mockworkerRouter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockworkerRouter_Run_Call) Return(err error) *mockworkerRouter_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockworkerRouter_Run_Call) RunAndReturn(run func(context1 context.Context) error) *mockworkerRouter_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SubscriptionsReady provides a mock function for the type mockworkerRouter
func (_mock *mockworkerRouter) SubscriptionsReady() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SubscriptionsReady")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// mockworkerRouter_SubscriptionsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscriptionsReady'
type mockworkerRouter_SubscriptionsReady_Call struct {
	*mock.Call
}

// SubscriptionsReady is a helper method to define mock.On call
func (_e *mockworkerRouter_Expecter) SubscriptionsReady() *mockworkerRouter_SubscriptionsReady_Call {
	return &mockworkerRouter_SubscriptionsReady_Call{Call: _e.mock.On("SubscriptionsReady")}
}

func (_c *mockworkerRouter_SubscriptionsReady_Call) Run(run func()) *mockworkerRouter_SubscriptionsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockworkerRouter_SubscriptionsReady_Call) Return(valCh <-chan struct{}) *mockworkerRouter_SubscriptionsReady_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *mockworkerRouter_SubscriptionsReady_Call) RunAndReturn(run func() <-chan struct{}) *mockworkerRouter_SubscriptionsReady_Call {
	_c.Call.Return(run)
	return _c
}
