// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package middleware

import (
	"github.com/gemyago/signal-foundry/apps/signal-foundry/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// newMockjwtValidator creates a new instance of mockjwtValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjwtValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjwtValidator {
	mock := &mockjwtValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjwtValidator is an autogenerated mock type for the jwtValidator type
type mockjwtValidator struct {
	mock.Mock
}

type mockjwtValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjwtValidator) EXPECT() *mockjwtValidator_Expecter {
	return &mockjwtValidator_Expecter{mock: &_m.Mock}
}

// ValidateAccessToken provides a mock function for the type mockjwtValidator
func (_mock *mockjwtValidator) ValidateAccessToken(tokenStr string) (*auth.JWTClaims, error) {
	ret := _mock.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *auth.JWTClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.JWTClaims, error)); ok {
		return returnFunc(tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.JWTClaims); ok {
		r0 = returnFunc(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.JWTClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjwtValidator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type mockjwtValidator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *mockjwtValidator_Expecter) ValidateAccessToken(tokenStr any) *mockjwtValidator_ValidateAccessToken_Call {
	return &mockjwtValidator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenStr)}
}

func (_c *mockjwtValidator_ValidateAccessToken_Call) Run(run func(tokenStr string)) *mockjwtValidator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjwtValidator_ValidateAccessToken_Call) Return(jWTClaims *auth.JWTClaims, err error) *mockjwtValidator_ValidateAccessToken_Call {
	_c.Call.Return(jWTClaims, err)
	return _c
}

func (_c *mockjwtValidator_ValidateAccessToken_Call) RunAndReturn(run func(tokenStr string) (*auth.JWTClaims, error)) *mockjwtValidator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
