apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sumweave.fullname" . }}-worker
  labels: {{- include "sumweave.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: {type: Recreate}
  selector:
    matchLabels: {{- include "sumweave.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels: {{- include "sumweave.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ include "sumweave.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: {{ include "sumweave.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: {{- toYaml .Values.worker.args | nindent 12 }}
          {{- if or .Values.existingConfigMap .Values.existingSecret }}
          envFrom: {{- include "sumweave.envFrom" . | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
