// Code generated by apigen DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"time"
)

// Unused imports workaround.
var _ = time.Time{}
var _ = json.Unmarshal
var _ = fmt.Sprint

// AuthRefreshParams - Parameters for the authRefresh operation.
type AuthRefreshParams struct { 
	Payload *AuthRefreshRequest `json:"payload"`
}
