// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package main

import (
	"context"

	"github.com/gemyago/sumweave/apps/sumweave"
	"github.com/gemyago/sumweave/apps/sumweave/internal/auth"
	"github.com/gemyago/sumweave/finance"
	"github.com/gemyago/sumweave/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockdatabaseMigrationRunner creates a new instance of mockdatabaseMigrationRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdatabaseMigrationRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdatabaseMigrationRunner {
	mock := &mockdatabaseMigrationRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdatabaseMigrationRunner is an autogenerated mock type for the databaseMigrationRunner type
type mockdatabaseMigrationRunner struct {
	mock.Mock
}

type mockdatabaseMigrationRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdatabaseMigrationRunner) EXPECT() *mockdatabaseMigrationRunner_Expecter {
	return &mockdatabaseMigrationRunner_Expecter{mock: &_m.Mock}
}

// Migrate provides a mock function for the type mockdatabaseMigrationRunner
func (_mock *mockdatabaseMigrationRunner) Migrate(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdatabaseMigrationRunner_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type mockdatabaseMigrationRunner_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockdatabaseMigrationRunner_Expecter) Migrate(context1 interface{}) *mockdatabaseMigrationRunner_Migrate_Call {
	return &mockdatabaseMigrationRunner_Migrate_Call{Call: _e.mock.On("Migrate", context1)}
}

func (_c *mockdatabaseMigrationRunner_Migrate_Call) Run(run func(context1 context.Context)) *mockdatabaseMigrationRunner_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdatabaseMigrationRunner_Migrate_Call) Return(err error) *mockdatabaseMigrationRunner_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdatabaseMigrationRunner_Migrate_Call) RunAndReturn(run func(context1 context.Context) error) *mockdatabaseMigrationRunner_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfinanceFixturesTenantService creates a new instance of mockfinanceFixturesTenantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfinanceFixturesTenantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfinanceFixturesTenantService {
	mock := &mockfinanceFixturesTenantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfinanceFixturesTenantService is an autogenerated mock type for the financeFixturesTenantService type
type mockfinanceFixturesTenantService struct {
	mock.Mock
}

type mockfinanceFixturesTenantService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfinanceFixturesTenantService) EXPECT() *mockfinanceFixturesTenantService_Expecter {
	return &mockfinanceFixturesTenantService_Expecter{mock: &_m.Mock}
}

// AcceptTenantInvite provides a mock function for the type mockfinanceFixturesTenantService
func (_mock *mockfinanceFixturesTenantService) AcceptTenantInvite(context1 context.Context, acceptTenantInviteParams finance.AcceptTenantInviteParams) (domain.TenantMembership, error) {
	ret := _mock.Called(context1, acceptTenantInviteParams)

	if len(ret) == 0 {
		panic("no return value specified for AcceptTenantInvite")
	}

	var r0 domain.TenantMembership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.AcceptTenantInviteParams) (domain.TenantMembership, error)); ok {
		return returnFunc(context1, acceptTenantInviteParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.AcceptTenantInviteParams) domain.TenantMembership); ok {
		r0 = returnFunc(context1, acceptTenantInviteParams)
	} else {
		r0 = ret.Get(0).(domain.TenantMembership)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.AcceptTenantInviteParams) error); ok {
		r1 = returnFunc(context1, acceptTenantInviteParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesTenantService_AcceptTenantInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptTenantInvite'
type mockfinanceFixturesTenantService_AcceptTenantInvite_Call struct {
	*mock.Call
}

// AcceptTenantInvite is a helper method to define mock.On call
//   - context1 context.Context
//   - acceptTenantInviteParams finance.AcceptTenantInviteParams
func (_e *mockfinanceFixturesTenantService_Expecter) AcceptTenantInvite(context1 interface{}, acceptTenantInviteParams interface{}) *mockfinanceFixturesTenantService_AcceptTenantInvite_Call {
	return &mockfinanceFixturesTenantService_AcceptTenantInvite_Call{Call: _e.mock.On("AcceptTenantInvite", context1, acceptTenantInviteParams)}
}

func (_c *mockfinanceFixturesTenantService_AcceptTenantInvite_Call) Run(run func(context1 context.Context, acceptTenantInviteParams finance.AcceptTenantInviteParams)) *mockfinanceFixturesTenantService_AcceptTenantInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.AcceptTenantInviteParams
		if args[1] != nil {
			arg1 = args[1].(finance.AcceptTenantInviteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesTenantService_AcceptTenantInvite_Call) Return(tenantMembership domain.TenantMembership, err error) *mockfinanceFixturesTenantService_AcceptTenantInvite_Call {
	_c.Call.Return(tenantMembership, err)
	return _c
}

func (_c *mockfinanceFixturesTenantService_AcceptTenantInvite_Call) RunAndReturn(run func(context1 context.Context, acceptTenantInviteParams finance.AcceptTenantInviteParams) (domain.TenantMembership, error)) *mockfinanceFixturesTenantService_AcceptTenantInvite_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTenant provides a mock function for the type mockfinanceFixturesTenantService
func (_mock *mockfinanceFixturesTenantService) CreateTenant(context1 context.Context, createTenantParams finance.CreateTenantParams) (domain.Tenant, error) {
	ret := _mock.Called(context1, createTenantParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateTenant")
	}

	var r0 domain.Tenant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.CreateTenantParams) (domain.Tenant, error)); ok {
		return returnFunc(context1, createTenantParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.CreateTenantParams) domain.Tenant); ok {
		r0 = returnFunc(context1, createTenantParams)
	} else {
		r0 = ret.Get(0).(domain.Tenant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.CreateTenantParams) error); ok {
		r1 = returnFunc(context1, createTenantParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesTenantService_CreateTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTenant'
type mockfinanceFixturesTenantService_CreateTenant_Call struct {
	*mock.Call
}

// CreateTenant is a helper method to define mock.On call
//   - context1 context.Context
//   - createTenantParams finance.CreateTenantParams
func (_e *mockfinanceFixturesTenantService_Expecter) CreateTenant(context1 interface{}, createTenantParams interface{}) *mockfinanceFixturesTenantService_CreateTenant_Call {
	return &mockfinanceFixturesTenantService_CreateTenant_Call{Call: _e.mock.On("CreateTenant", context1, createTenantParams)}
}

func (_c *mockfinanceFixturesTenantService_CreateTenant_Call) Run(run func(context1 context.Context, createTenantParams finance.CreateTenantParams)) *mockfinanceFixturesTenantService_CreateTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.CreateTenantParams
		if args[1] != nil {
			arg1 = args[1].(finance.CreateTenantParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesTenantService_CreateTenant_Call) Return(tenant domain.Tenant, err error) *mockfinanceFixturesTenantService_CreateTenant_Call {
	_c.Call.Return(tenant, err)
	return _c
}

func (_c *mockfinanceFixturesTenantService_CreateTenant_Call) RunAndReturn(run func(context1 context.Context, createTenantParams finance.CreateTenantParams) (domain.Tenant, error)) *mockfinanceFixturesTenantService_CreateTenant_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTenantInvite provides a mock function for the type mockfinanceFixturesTenantService
func (_mock *mockfinanceFixturesTenantService) CreateTenantInvite(context1 context.Context, createTenantInviteParams finance.CreateTenantInviteParams) (domain.TenantInvite, error) {
	ret := _mock.Called(context1, createTenantInviteParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateTenantInvite")
	}

	var r0 domain.TenantInvite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.CreateTenantInviteParams) (domain.TenantInvite, error)); ok {
		return returnFunc(context1, createTenantInviteParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.CreateTenantInviteParams) domain.TenantInvite); ok {
		r0 = returnFunc(context1, createTenantInviteParams)
	} else {
		r0 = ret.Get(0).(domain.TenantInvite)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.CreateTenantInviteParams) error); ok {
		r1 = returnFunc(context1, createTenantInviteParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesTenantService_CreateTenantInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTenantInvite'
type mockfinanceFixturesTenantService_CreateTenantInvite_Call struct {
	*mock.Call
}

// CreateTenantInvite is a helper method to define mock.On call
//   - context1 context.Context
//   - createTenantInviteParams finance.CreateTenantInviteParams
func (_e *mockfinanceFixturesTenantService_Expecter) CreateTenantInvite(context1 interface{}, createTenantInviteParams interface{}) *mockfinanceFixturesTenantService_CreateTenantInvite_Call {
	return &mockfinanceFixturesTenantService_CreateTenantInvite_Call{Call: _e.mock.On("CreateTenantInvite", context1, createTenantInviteParams)}
}

func (_c *mockfinanceFixturesTenantService_CreateTenantInvite_Call) Run(run func(context1 context.Context, createTenantInviteParams finance.CreateTenantInviteParams)) *mockfinanceFixturesTenantService_CreateTenantInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.CreateTenantInviteParams
		if args[1] != nil {
			arg1 = args[1].(finance.CreateTenantInviteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesTenantService_CreateTenantInvite_Call) Return(tenantInvite domain.TenantInvite, err error) *mockfinanceFixturesTenantService_CreateTenantInvite_Call {
	_c.Call.Return(tenantInvite, err)
	return _c
}

func (_c *mockfinanceFixturesTenantService_CreateTenantInvite_Call) RunAndReturn(run func(context1 context.Context, createTenantInviteParams finance.CreateTenantInviteParams) (domain.TenantInvite, error)) *mockfinanceFixturesTenantService_CreateTenantInvite_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfinanceFixturesCatalogService creates a new instance of mockfinanceFixturesCatalogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfinanceFixturesCatalogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfinanceFixturesCatalogService {
	mock := &mockfinanceFixturesCatalogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfinanceFixturesCatalogService is an autogenerated mock type for the financeFixturesCatalogService type
type mockfinanceFixturesCatalogService struct {
	mock.Mock
}

type mockfinanceFixturesCatalogService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfinanceFixturesCatalogService) EXPECT() *mockfinanceFixturesCatalogService_Expecter {
	return &mockfinanceFixturesCatalogService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type mockfinanceFixturesCatalogService
func (_mock *mockfinanceFixturesCatalogService) CreateAccount(context1 context.Context, createAccountParams finance.CreateAccountParams) (domain.Account, error) {
	ret := _mock.Called(context1, createAccountParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.CreateAccountParams) (domain.Account, error)); ok {
		return returnFunc(context1, createAccountParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.CreateAccountParams) domain.Account); ok {
		r0 = returnFunc(context1, createAccountParams)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.CreateAccountParams) error); ok {
		r1 = returnFunc(context1, createAccountParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesCatalogService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type mockfinanceFixturesCatalogService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - context1 context.Context
//   - createAccountParams finance.CreateAccountParams
func (_e *mockfinanceFixturesCatalogService_Expecter) CreateAccount(context1 interface{}, createAccountParams interface{}) *mockfinanceFixturesCatalogService_CreateAccount_Call {
	return &mockfinanceFixturesCatalogService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", context1, createAccountParams)}
}

func (_c *mockfinanceFixturesCatalogService_CreateAccount_Call) Run(run func(context1 context.Context, createAccountParams finance.CreateAccountParams)) *mockfinanceFixturesCatalogService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.CreateAccountParams
		if args[1] != nil {
			arg1 = args[1].(finance.CreateAccountParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesCatalogService_CreateAccount_Call) Return(account domain.Account, err error) *mockfinanceFixturesCatalogService_CreateAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *mockfinanceFixturesCatalogService_CreateAccount_Call) RunAndReturn(run func(context1 context.Context, createAccountParams finance.CreateAccountParams) (domain.Account, error)) *mockfinanceFixturesCatalogService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function for the type mockfinanceFixturesCatalogService
func (_mock *mockfinanceFixturesCatalogService) ListCategories(context1 context.Context, listCategoriesParams finance.ListCategoriesParams) ([]domain.Category, error) {
	ret := _mock.Called(context1, listCategoriesParams)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.ListCategoriesParams) ([]domain.Category, error)); ok {
		return returnFunc(context1, listCategoriesParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.ListCategoriesParams) []domain.Category); ok {
		r0 = returnFunc(context1, listCategoriesParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.ListCategoriesParams) error); ok {
		r1 = returnFunc(context1, listCategoriesParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesCatalogService_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type mockfinanceFixturesCatalogService_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - context1 context.Context
//   - listCategoriesParams finance.ListCategoriesParams
func (_e *mockfinanceFixturesCatalogService_Expecter) ListCategories(context1 interface{}, listCategoriesParams interface{}) *mockfinanceFixturesCatalogService_ListCategories_Call {
	return &mockfinanceFixturesCatalogService_ListCategories_Call{Call: _e.mock.On("ListCategories", context1, listCategoriesParams)}
}

func (_c *mockfinanceFixturesCatalogService_ListCategories_Call) Run(run func(context1 context.Context, listCategoriesParams finance.ListCategoriesParams)) *mockfinanceFixturesCatalogService_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.ListCategoriesParams
		if args[1] != nil {
			arg1 = args[1].(finance.ListCategoriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesCatalogService_ListCategories_Call) Return(categorys []domain.Category, err error) *mockfinanceFixturesCatalogService_ListCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *mockfinanceFixturesCatalogService_ListCategories_Call) RunAndReturn(run func(context1 context.Context, listCategoriesParams finance.ListCategoriesParams) ([]domain.Category, error)) *mockfinanceFixturesCatalogService_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type mockfinanceFixturesCatalogService
func (_mock *mockfinanceFixturesCatalogService) ListTags(context1 context.Context, listTagsParams finance.ListTagsParams) ([]domain.Tag, error) {
	ret := _mock.Called(context1, listTagsParams)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []domain.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.ListTagsParams) ([]domain.Tag, error)); ok {
		return returnFunc(context1, listTagsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.ListTagsParams) []domain.Tag); ok {
		r0 = returnFunc(context1, listTagsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.ListTagsParams) error); ok {
		r1 = returnFunc(context1, listTagsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesCatalogService_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type mockfinanceFixturesCatalogService_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - context1 context.Context
//   - listTagsParams finance.ListTagsParams
func (_e *mockfinanceFixturesCatalogService_Expecter) ListTags(context1 interface{}, listTagsParams interface{}) *mockfinanceFixturesCatalogService_ListTags_Call {
	return &mockfinanceFixturesCatalogService_ListTags_Call{Call: _e.mock.On("ListTags", context1, listTagsParams)}
}

func (_c *mockfinanceFixturesCatalogService_ListTags_Call) Run(run func(context1 context.Context, listTagsParams finance.ListTagsParams)) *mockfinanceFixturesCatalogService_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.ListTagsParams
		if args[1] != nil {
			arg1 = args[1].(finance.ListTagsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesCatalogService_ListTags_Call) Return(tags []domain.Tag, err error) *mockfinanceFixturesCatalogService_ListTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *mockfinanceFixturesCatalogService_ListTags_Call) RunAndReturn(run func(context1 context.Context, listTagsParams finance.ListTagsParams) ([]domain.Tag, error)) *mockfinanceFixturesCatalogService_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfinanceFixturesLedgerService creates a new instance of mockfinanceFixturesLedgerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfinanceFixturesLedgerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfinanceFixturesLedgerService {
	mock := &mockfinanceFixturesLedgerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfinanceFixturesLedgerService is an autogenerated mock type for the financeFixturesLedgerService type
type mockfinanceFixturesLedgerService struct {
	mock.Mock
}

type mockfinanceFixturesLedgerService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfinanceFixturesLedgerService) EXPECT() *mockfinanceFixturesLedgerService_Expecter {
	return &mockfinanceFixturesLedgerService_Expecter{mock: &_m.Mock}
}

// HideTransaction provides a mock function for the type mockfinanceFixturesLedgerService
func (_mock *mockfinanceFixturesLedgerService) HideTransaction(context1 context.Context, hideTransactionParams finance.HideTransactionParams) error {
	ret := _mock.Called(context1, hideTransactionParams)

	if len(ret) == 0 {
		panic("no return value specified for HideTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.HideTransactionParams) error); ok {
		r0 = returnFunc(context1, hideTransactionParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockfinanceFixturesLedgerService_HideTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HideTransaction'
type mockfinanceFixturesLedgerService_HideTransaction_Call struct {
	*mock.Call
}

// HideTransaction is a helper method to define mock.On call
//   - context1 context.Context
//   - hideTransactionParams finance.HideTransactionParams
func (_e *mockfinanceFixturesLedgerService_Expecter) HideTransaction(context1 interface{}, hideTransactionParams interface{}) *mockfinanceFixturesLedgerService_HideTransaction_Call {
	return &mockfinanceFixturesLedgerService_HideTransaction_Call{Call: _e.mock.On("HideTransaction", context1, hideTransactionParams)}
}

func (_c *mockfinanceFixturesLedgerService_HideTransaction_Call) Run(run func(context1 context.Context, hideTransactionParams finance.HideTransactionParams)) *mockfinanceFixturesLedgerService_HideTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.HideTransactionParams
		if args[1] != nil {
			arg1 = args[1].(finance.HideTransactionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesLedgerService_HideTransaction_Call) Return(err error) *mockfinanceFixturesLedgerService_HideTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockfinanceFixturesLedgerService_HideTransaction_Call) RunAndReturn(run func(context1 context.Context, hideTransactionParams finance.HideTransactionParams) error) *mockfinanceFixturesLedgerService_HideTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// LinkTransfers provides a mock function for the type mockfinanceFixturesLedgerService
func (_mock *mockfinanceFixturesLedgerService) LinkTransfers(context1 context.Context, linkTransfersParams finance.LinkTransfersParams) error {
	ret := _mock.Called(context1, linkTransfersParams)

	if len(ret) == 0 {
		panic("no return value specified for LinkTransfers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.LinkTransfersParams) error); ok {
		r0 = returnFunc(context1, linkTransfersParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockfinanceFixturesLedgerService_LinkTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkTransfers'
type mockfinanceFixturesLedgerService_LinkTransfers_Call struct {
	*mock.Call
}

// LinkTransfers is a helper method to define mock.On call
//   - context1 context.Context
//   - linkTransfersParams finance.LinkTransfersParams
func (_e *mockfinanceFixturesLedgerService_Expecter) LinkTransfers(context1 interface{}, linkTransfersParams interface{}) *mockfinanceFixturesLedgerService_LinkTransfers_Call {
	return &mockfinanceFixturesLedgerService_LinkTransfers_Call{Call: _e.mock.On("LinkTransfers", context1, linkTransfersParams)}
}

func (_c *mockfinanceFixturesLedgerService_LinkTransfers_Call) Run(run func(context1 context.Context, linkTransfersParams finance.LinkTransfersParams)) *mockfinanceFixturesLedgerService_LinkTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.LinkTransfersParams
		if args[1] != nil {
			arg1 = args[1].(finance.LinkTransfersParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesLedgerService_LinkTransfers_Call) Return(err error) *mockfinanceFixturesLedgerService_LinkTransfers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockfinanceFixturesLedgerService_LinkTransfers_Call) RunAndReturn(run func(context1 context.Context, linkTransfersParams finance.LinkTransfersParams) error) *mockfinanceFixturesLedgerService_LinkTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// RecordTransaction provides a mock function for the type mockfinanceFixturesLedgerService
func (_mock *mockfinanceFixturesLedgerService) RecordTransaction(context1 context.Context, recordTransactionParams finance.RecordTransactionParams) (domain.Transaction, error) {
	ret := _mock.Called(context1, recordTransactionParams)

	if len(ret) == 0 {
		panic("no return value specified for RecordTransaction")
	}

	var r0 domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RecordTransactionParams) (domain.Transaction, error)); ok {
		return returnFunc(context1, recordTransactionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RecordTransactionParams) domain.Transaction); ok {
		r0 = returnFunc(context1, recordTransactionParams)
	} else {
		r0 = ret.Get(0).(domain.Transaction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.RecordTransactionParams) error); ok {
		r1 = returnFunc(context1, recordTransactionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesLedgerService_RecordTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordTransaction'
type mockfinanceFixturesLedgerService_RecordTransaction_Call struct {
	*mock.Call
}

// RecordTransaction is a helper method to define mock.On call
//   - context1 context.Context
//   - recordTransactionParams finance.RecordTransactionParams
func (_e *mockfinanceFixturesLedgerService_Expecter) RecordTransaction(context1 interface{}, recordTransactionParams interface{}) *mockfinanceFixturesLedgerService_RecordTransaction_Call {
	return &mockfinanceFixturesLedgerService_RecordTransaction_Call{Call: _e.mock.On("RecordTransaction", context1, recordTransactionParams)}
}

func (_c *mockfinanceFixturesLedgerService_RecordTransaction_Call) Run(run func(context1 context.Context, recordTransactionParams finance.RecordTransactionParams)) *mockfinanceFixturesLedgerService_RecordTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.RecordTransactionParams
		if args[1] != nil {
			arg1 = args[1].(finance.RecordTransactionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesLedgerService_RecordTransaction_Call) Return(transaction domain.Transaction, err error) *mockfinanceFixturesLedgerService_RecordTransaction_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *mockfinanceFixturesLedgerService_RecordTransaction_Call) RunAndReturn(run func(context1 context.Context, recordTransactionParams finance.RecordTransactionParams) (domain.Transaction, error)) *mockfinanceFixturesLedgerService_RecordTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfinanceFixturesCSVImportService creates a new instance of mockfinanceFixturesCSVImportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfinanceFixturesCSVImportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfinanceFixturesCSVImportService {
	mock := &mockfinanceFixturesCSVImportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfinanceFixturesCSVImportService is an autogenerated mock type for the financeFixturesCSVImportService type
type mockfinanceFixturesCSVImportService struct {
	mock.Mock
}

type mockfinanceFixturesCSVImportService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfinanceFixturesCSVImportService) EXPECT() *mockfinanceFixturesCSVImportService_Expecter {
	return &mockfinanceFixturesCSVImportService_Expecter{mock: &_m.Mock}
}

// PreviewCSVImport provides a mock function for the type mockfinanceFixturesCSVImportService
func (_mock *mockfinanceFixturesCSVImportService) PreviewCSVImport(context1 context.Context, previewCSVImportParams finance.PreviewCSVImportParams) (finance.CSVImportPreview, error) {
	ret := _mock.Called(context1, previewCSVImportParams)

	if len(ret) == 0 {
		panic("no return value specified for PreviewCSVImport")
	}

	var r0 finance.CSVImportPreview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.PreviewCSVImportParams) (finance.CSVImportPreview, error)); ok {
		return returnFunc(context1, previewCSVImportParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.PreviewCSVImportParams) finance.CSVImportPreview); ok {
		r0 = returnFunc(context1, previewCSVImportParams)
	} else {
		r0 = ret.Get(0).(finance.CSVImportPreview)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.PreviewCSVImportParams) error); ok {
		r1 = returnFunc(context1, previewCSVImportParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesCSVImportService_PreviewCSVImport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreviewCSVImport'
type mockfinanceFixturesCSVImportService_PreviewCSVImport_Call struct {
	*mock.Call
}

// PreviewCSVImport is a helper method to define mock.On call
//   - context1 context.Context
//   - previewCSVImportParams finance.PreviewCSVImportParams
func (_e *mockfinanceFixturesCSVImportService_Expecter) PreviewCSVImport(context1 interface{}, previewCSVImportParams interface{}) *mockfinanceFixturesCSVImportService_PreviewCSVImport_Call {
	return &mockfinanceFixturesCSVImportService_PreviewCSVImport_Call{Call: _e.mock.On("PreviewCSVImport", context1, previewCSVImportParams)}
}

func (_c *mockfinanceFixturesCSVImportService_PreviewCSVImport_Call) Run(run func(context1 context.Context, previewCSVImportParams finance.PreviewCSVImportParams)) *mockfinanceFixturesCSVImportService_PreviewCSVImport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.PreviewCSVImportParams
		if args[1] != nil {
			arg1 = args[1].(finance.PreviewCSVImportParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesCSVImportService_PreviewCSVImport_Call) Return(cSVImportPreview finance.CSVImportPreview, err error) *mockfinanceFixturesCSVImportService_PreviewCSVImport_Call {
	_c.Call.Return(cSVImportPreview, err)
	return _c
}

func (_c *mockfinanceFixturesCSVImportService_PreviewCSVImport_Call) RunAndReturn(run func(context1 context.Context, previewCSVImportParams finance.PreviewCSVImportParams) (finance.CSVImportPreview, error)) *mockfinanceFixturesCSVImportService_PreviewCSVImport_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfinanceFixturesBankConnectionService creates a new instance of mockfinanceFixturesBankConnectionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfinanceFixturesBankConnectionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfinanceFixturesBankConnectionService {
	mock := &mockfinanceFixturesBankConnectionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfinanceFixturesBankConnectionService is an autogenerated mock type for the financeFixturesBankConnectionService type
type mockfinanceFixturesBankConnectionService struct {
	mock.Mock
}

type mockfinanceFixturesBankConnectionService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfinanceFixturesBankConnectionService) EXPECT() *mockfinanceFixturesBankConnectionService_Expecter {
	return &mockfinanceFixturesBankConnectionService_Expecter{mock: &_m.Mock}
}

// LinkTokenBankConnection provides a mock function for the type mockfinanceFixturesBankConnectionService
func (_mock *mockfinanceFixturesBankConnectionService) LinkTokenBankConnection(context1 context.Context, linkTokenBankConnectionParams finance.LinkTokenBankConnectionParams) (domain.BankConnection, error) {
	ret := _mock.Called(context1, linkTokenBankConnectionParams)

	if len(ret) == 0 {
		panic("no return value specified for LinkTokenBankConnection")
	}

	var r0 domain.BankConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.LinkTokenBankConnectionParams) (domain.BankConnection, error)); ok {
		return returnFunc(context1, linkTokenBankConnectionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.LinkTokenBankConnectionParams) domain.BankConnection); ok {
		r0 = returnFunc(context1, linkTokenBankConnectionParams)
	} else {
		r0 = ret.Get(0).(domain.BankConnection)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.LinkTokenBankConnectionParams) error); ok {
		r1 = returnFunc(context1, linkTokenBankConnectionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkTokenBankConnection'
type mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call struct {
	*mock.Call
}

// LinkTokenBankConnection is a helper method to define mock.On call
//   - context1 context.Context
//   - linkTokenBankConnectionParams finance.LinkTokenBankConnectionParams
func (_e *mockfinanceFixturesBankConnectionService_Expecter) LinkTokenBankConnection(context1 interface{}, linkTokenBankConnectionParams interface{}) *mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call {
	return &mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call{Call: _e.mock.On("LinkTokenBankConnection", context1, linkTokenBankConnectionParams)}
}

func (_c *mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call) Run(run func(context1 context.Context, linkTokenBankConnectionParams finance.LinkTokenBankConnectionParams)) *mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.LinkTokenBankConnectionParams
		if args[1] != nil {
			arg1 = args[1].(finance.LinkTokenBankConnectionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call) Return(bankConnection domain.BankConnection, err error) *mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call {
	_c.Call.Return(bankConnection, err)
	return _c
}

func (_c *mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call) RunAndReturn(run func(context1 context.Context, linkTokenBankConnectionParams finance.LinkTokenBankConnectionParams) (domain.BankConnection, error)) *mockfinanceFixturesBankConnectionService_LinkTokenBankConnection_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfinanceFixturesBankSyncService creates a new instance of mockfinanceFixturesBankSyncService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfinanceFixturesBankSyncService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfinanceFixturesBankSyncService {
	mock := &mockfinanceFixturesBankSyncService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfinanceFixturesBankSyncService is an autogenerated mock type for the financeFixturesBankSyncService type
type mockfinanceFixturesBankSyncService struct {
	mock.Mock
}

type mockfinanceFixturesBankSyncService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfinanceFixturesBankSyncService) EXPECT() *mockfinanceFixturesBankSyncService_Expecter {
	return &mockfinanceFixturesBankSyncService_Expecter{mock: &_m.Mock}
}

// UpsertBankConnectionSchedule provides a mock function for the type mockfinanceFixturesBankSyncService
func (_mock *mockfinanceFixturesBankSyncService) UpsertBankConnectionSchedule(context1 context.Context, upsertBankConnectionScheduleParams finance.UpsertBankConnectionScheduleParams) (domain.BankConnectionSchedule, error) {
	ret := _mock.Called(context1, upsertBankConnectionScheduleParams)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBankConnectionSchedule")
	}

	var r0 domain.BankConnectionSchedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.UpsertBankConnectionScheduleParams) (domain.BankConnectionSchedule, error)); ok {
		return returnFunc(context1, upsertBankConnectionScheduleParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.UpsertBankConnectionScheduleParams) domain.BankConnectionSchedule); ok {
		r0 = returnFunc(context1, upsertBankConnectionScheduleParams)
	} else {
		r0 = ret.Get(0).(domain.BankConnectionSchedule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.UpsertBankConnectionScheduleParams) error); ok {
		r1 = returnFunc(context1, upsertBankConnectionScheduleParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBankConnectionSchedule'
type mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call struct {
	*mock.Call
}

// UpsertBankConnectionSchedule is a helper method to define mock.On call
//   - context1 context.Context
//   - upsertBankConnectionScheduleParams finance.UpsertBankConnectionScheduleParams
func (_e *mockfinanceFixturesBankSyncService_Expecter) UpsertBankConnectionSchedule(context1 interface{}, upsertBankConnectionScheduleParams interface{}) *mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call {
	return &mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call{Call: _e.mock.On("UpsertBankConnectionSchedule", context1, upsertBankConnectionScheduleParams)}
}

func (_c *mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call) Run(run func(context1 context.Context, upsertBankConnectionScheduleParams finance.UpsertBankConnectionScheduleParams)) *mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.UpsertBankConnectionScheduleParams
		if args[1] != nil {
			arg1 = args[1].(finance.UpsertBankConnectionScheduleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call) Return(bankConnectionSchedule domain.BankConnectionSchedule, err error) *mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call {
	_c.Call.Return(bankConnectionSchedule, err)
	return _c
}

func (_c *mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call) RunAndReturn(run func(context1 context.Context, upsertBankConnectionScheduleParams finance.UpsertBankConnectionScheduleParams) (domain.BankConnectionSchedule, error)) *mockfinanceFixturesBankSyncService_UpsertBankConnectionSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// newMockfinanceFixturesFXService creates a new instance of mockfinanceFixturesFXService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfinanceFixturesFXService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfinanceFixturesFXService {
	mock := &mockfinanceFixturesFXService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockfinanceFixturesFXService is an autogenerated mock type for the financeFixturesFXService type
type mockfinanceFixturesFXService struct {
	mock.Mock
}

type mockfinanceFixturesFXService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfinanceFixturesFXService) EXPECT() *mockfinanceFixturesFXService_Expecter {
	return &mockfinanceFixturesFXService_Expecter{mock: &_m.Mock}
}

// RefreshRequiredFXRates provides a mock function for the type mockfinanceFixturesFXService
func (_mock *mockfinanceFixturesFXService) RefreshRequiredFXRates(context1 context.Context, refreshFXRatesParams finance.RefreshFXRatesParams) (finance.RefreshFXRatesResult, error) {
	ret := _mock.Called(context1, refreshFXRatesParams)

	if len(ret) == 0 {
		panic("no return value specified for RefreshRequiredFXRates")
	}

	var r0 finance.RefreshFXRatesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RefreshFXRatesParams) (finance.RefreshFXRatesResult, error)); ok {
		return returnFunc(context1, refreshFXRatesParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, finance.RefreshFXRatesParams) finance.RefreshFXRatesResult); ok {
		r0 = returnFunc(context1, refreshFXRatesParams)
	} else {
		r0 = ret.Get(0).(finance.RefreshFXRatesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, finance.RefreshFXRatesParams) error); ok {
		r1 = returnFunc(context1, refreshFXRatesParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockfinanceFixturesFXService_RefreshRequiredFXRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshRequiredFXRates'
type mockfinanceFixturesFXService_RefreshRequiredFXRates_Call struct {
	*mock.Call
}

// RefreshRequiredFXRates is a helper method to define mock.On call
//   - context1 context.Context
//   - refreshFXRatesParams finance.RefreshFXRatesParams
func (_e *mockfinanceFixturesFXService_Expecter) RefreshRequiredFXRates(context1 interface{}, refreshFXRatesParams interface{}) *mockfinanceFixturesFXService_RefreshRequiredFXRates_Call {
	return &mockfinanceFixturesFXService_RefreshRequiredFXRates_Call{Call: _e.mock.On("RefreshRequiredFXRates", context1, refreshFXRatesParams)}
}

func (_c *mockfinanceFixturesFXService_RefreshRequiredFXRates_Call) Run(run func(context1 context.Context, refreshFXRatesParams finance.RefreshFXRatesParams)) *mockfinanceFixturesFXService_RefreshRequiredFXRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 finance.RefreshFXRatesParams
		if args[1] != nil {
			arg1 = args[1].(finance.RefreshFXRatesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockfinanceFixturesFXService_RefreshRequiredFXRates_Call) Return(refreshFXRatesResult finance.RefreshFXRatesResult, err error) *mockfinanceFixturesFXService_RefreshRequiredFXRates_Call {
	_c.Call.Return(refreshFXRatesResult, err)
	return _c
}

func (_c *mockfinanceFixturesFXService_RefreshRequiredFXRates_Call) RunAndReturn(run func(context1 context.Context, refreshFXRatesParams finance.RefreshFXRatesParams) (finance.RefreshFXRatesResult, error)) *mockfinanceFixturesFXService_RefreshRequiredFXRates_Call {
	_c.Call.Return(run)
	return _c
}

// newMockjobsWorkerRunner creates a new instance of mockjobsWorkerRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjobsWorkerRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjobsWorkerRunner {
	mock := &mockjobsWorkerRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjobsWorkerRunner is an autogenerated mock type for the jobsWorkerRunner type
type mockjobsWorkerRunner struct {
	mock.Mock
}

type mockjobsWorkerRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjobsWorkerRunner) EXPECT() *mockjobsWorkerRunner_Expecter {
	return &mockjobsWorkerRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type mockjobsWorkerRunner
func (_mock *mockjobsWorkerRunner) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsWorkerRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockjobsWorkerRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsWorkerRunner_Expecter) Run(context1 interface{}) *mockjobsWorkerRunner_Run_Call {
	return &mockjobsWorkerRunner_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *mockjobsWorkerRunner_Run_Call) Run(run func(context1 context.Context)) *mockjobsWorkerRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsWorkerRunner_Run_Call) Return(err error) *mockjobsWorkerRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsWorkerRunner_Run_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsWorkerRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunOnce provides a mock function for the type mockjobsWorkerRunner
func (_mock *mockjobsWorkerRunner) RunOnce(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for RunOnce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsWorkerRunner_RunOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOnce'
type mockjobsWorkerRunner_RunOnce_Call struct {
	*mock.Call
}

// RunOnce is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsWorkerRunner_Expecter) RunOnce(context1 interface{}) *mockjobsWorkerRunner_RunOnce_Call {
	return &mockjobsWorkerRunner_RunOnce_Call{Call: _e.mock.On("RunOnce", context1)}
}

func (_c *mockjobsWorkerRunner_RunOnce_Call) Run(run func(context1 context.Context)) *mockjobsWorkerRunner_RunOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsWorkerRunner_RunOnce_Call) Return(err error) *mockjobsWorkerRunner_RunOnce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsWorkerRunner_RunOnce_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsWorkerRunner_RunOnce_Call {
	_c.Call.Return(run)
	return _c
}

// newMockjobsWorkerCommandRunner creates a new instance of mockjobsWorkerCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjobsWorkerCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjobsWorkerCommandRunner {
	mock := &mockjobsWorkerCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjobsWorkerCommandRunner is an autogenerated mock type for the jobsWorkerCommandRunner type
type mockjobsWorkerCommandRunner struct {
	mock.Mock
}

type mockjobsWorkerCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjobsWorkerCommandRunner) EXPECT() *mockjobsWorkerCommandRunner_Expecter {
	return &mockjobsWorkerCommandRunner_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockjobsWorkerCommandRunner
func (_mock *mockjobsWorkerCommandRunner) Close(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsWorkerCommandRunner_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockjobsWorkerCommandRunner_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsWorkerCommandRunner_Expecter) Close(context1 interface{}) *mockjobsWorkerCommandRunner_Close_Call {
	return &mockjobsWorkerCommandRunner_Close_Call{Call: _e.mock.On("Close", context1)}
}

func (_c *mockjobsWorkerCommandRunner_Close_Call) Run(run func(context1 context.Context)) *mockjobsWorkerCommandRunner_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsWorkerCommandRunner_Close_Call) Return(err error) *mockjobsWorkerCommandRunner_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsWorkerCommandRunner_Close_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsWorkerCommandRunner_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type mockjobsWorkerCommandRunner
func (_mock *mockjobsWorkerCommandRunner) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsWorkerCommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockjobsWorkerCommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsWorkerCommandRunner_Expecter) Run(context1 interface{}) *mockjobsWorkerCommandRunner_Run_Call {
	return &mockjobsWorkerCommandRunner_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *mockjobsWorkerCommandRunner_Run_Call) Run(run func(context1 context.Context)) *mockjobsWorkerCommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsWorkerCommandRunner_Run_Call) Return(err error) *mockjobsWorkerCommandRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsWorkerCommandRunner_Run_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsWorkerCommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// RunOnce provides a mock function for the type mockjobsWorkerCommandRunner
func (_mock *mockjobsWorkerCommandRunner) RunOnce(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for RunOnce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsWorkerCommandRunner_RunOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOnce'
type mockjobsWorkerCommandRunner_RunOnce_Call struct {
	*mock.Call
}

// RunOnce is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsWorkerCommandRunner_Expecter) RunOnce(context1 interface{}) *mockjobsWorkerCommandRunner_RunOnce_Call {
	return &mockjobsWorkerCommandRunner_RunOnce_Call{Call: _e.mock.On("RunOnce", context1)}
}

func (_c *mockjobsWorkerCommandRunner_RunOnce_Call) Run(run func(context1 context.Context)) *mockjobsWorkerCommandRunner_RunOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsWorkerCommandRunner_RunOnce_Call) Return(err error) *mockjobsWorkerCommandRunner_RunOnce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsWorkerCommandRunner_RunOnce_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsWorkerCommandRunner_RunOnce_Call {
	_c.Call.Return(run)
	return _c
}

// newMockjobsSchedulerRunner creates a new instance of mockjobsSchedulerRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjobsSchedulerRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjobsSchedulerRunner {
	mock := &mockjobsSchedulerRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjobsSchedulerRunner is an autogenerated mock type for the jobsSchedulerRunner type
type mockjobsSchedulerRunner struct {
	mock.Mock
}

type mockjobsSchedulerRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjobsSchedulerRunner) EXPECT() *mockjobsSchedulerRunner_Expecter {
	return &mockjobsSchedulerRunner_Expecter{mock: &_m.Mock}
}

// EnqueueDue provides a mock function for the type mockjobsSchedulerRunner
func (_mock *mockjobsSchedulerRunner) EnqueueDue(context1 context.Context) (int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueDue")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjobsSchedulerRunner_EnqueueDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueDue'
type mockjobsSchedulerRunner_EnqueueDue_Call struct {
	*mock.Call
}

// EnqueueDue is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsSchedulerRunner_Expecter) EnqueueDue(context1 interface{}) *mockjobsSchedulerRunner_EnqueueDue_Call {
	return &mockjobsSchedulerRunner_EnqueueDue_Call{Call: _e.mock.On("EnqueueDue", context1)}
}

func (_c *mockjobsSchedulerRunner_EnqueueDue_Call) Run(run func(context1 context.Context)) *mockjobsSchedulerRunner_EnqueueDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsSchedulerRunner_EnqueueDue_Call) Return(n int, err error) *mockjobsSchedulerRunner_EnqueueDue_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockjobsSchedulerRunner_EnqueueDue_Call) RunAndReturn(run func(context1 context.Context) (int, error)) *mockjobsSchedulerRunner_EnqueueDue_Call {
	_c.Call.Return(run)
	return _c
}

// newMockjobsSchedulerCommandRunner creates a new instance of mockjobsSchedulerCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockjobsSchedulerCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockjobsSchedulerCommandRunner {
	mock := &mockjobsSchedulerCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockjobsSchedulerCommandRunner is an autogenerated mock type for the jobsSchedulerCommandRunner type
type mockjobsSchedulerCommandRunner struct {
	mock.Mock
}

type mockjobsSchedulerCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockjobsSchedulerCommandRunner) EXPECT() *mockjobsSchedulerCommandRunner_Expecter {
	return &mockjobsSchedulerCommandRunner_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockjobsSchedulerCommandRunner
func (_mock *mockjobsSchedulerCommandRunner) Close(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockjobsSchedulerCommandRunner_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockjobsSchedulerCommandRunner_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsSchedulerCommandRunner_Expecter) Close(context1 interface{}) *mockjobsSchedulerCommandRunner_Close_Call {
	return &mockjobsSchedulerCommandRunner_Close_Call{Call: _e.mock.On("Close", context1)}
}

func (_c *mockjobsSchedulerCommandRunner_Close_Call) Run(run func(context1 context.Context)) *mockjobsSchedulerCommandRunner_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsSchedulerCommandRunner_Close_Call) Return(err error) *mockjobsSchedulerCommandRunner_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockjobsSchedulerCommandRunner_Close_Call) RunAndReturn(run func(context1 context.Context) error) *mockjobsSchedulerCommandRunner_Close_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueDue provides a mock function for the type mockjobsSchedulerCommandRunner
func (_mock *mockjobsSchedulerCommandRunner) EnqueueDue(context1 context.Context) (int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueDue")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockjobsSchedulerCommandRunner_EnqueueDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueDue'
type mockjobsSchedulerCommandRunner_EnqueueDue_Call struct {
	*mock.Call
}

// EnqueueDue is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockjobsSchedulerCommandRunner_Expecter) EnqueueDue(context1 interface{}) *mockjobsSchedulerCommandRunner_EnqueueDue_Call {
	return &mockjobsSchedulerCommandRunner_EnqueueDue_Call{Call: _e.mock.On("EnqueueDue", context1)}
}

func (_c *mockjobsSchedulerCommandRunner_EnqueueDue_Call) Run(run func(context1 context.Context)) *mockjobsSchedulerCommandRunner_EnqueueDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockjobsSchedulerCommandRunner_EnqueueDue_Call) Return(n int, err error) *mockjobsSchedulerCommandRunner_EnqueueDue_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockjobsSchedulerCommandRunner_EnqueueDue_Call) RunAndReturn(run func(context1 context.Context) (int, error)) *mockjobsSchedulerCommandRunner_EnqueueDue_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstartServerRunner creates a new instance of mockstartServerRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstartServerRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstartServerRunner {
	mock := &mockstartServerRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstartServerRunner is an autogenerated mock type for the startServerRunner type
type mockstartServerRunner struct {
	mock.Mock
}

type mockstartServerRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstartServerRunner) EXPECT() *mockstartServerRunner_Expecter {
	return &mockstartServerRunner_Expecter{mock: &_m.Mock}
}

// StartHTTPServer provides a mock function for the type mockstartServerRunner
func (_mock *mockstartServerRunner) StartHTTPServer(context1 context.Context, engineStartServerOpts ...sumweave.EngineStartServerOpt) error {
	// sumweave.EngineStartServerOpt
	_va := make([]interface{}, len(engineStartServerOpts))
	for _i := range engineStartServerOpts {
		_va[_i] = engineStartServerOpts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StartHTTPServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...sumweave.EngineStartServerOpt) error); ok {
		r0 = returnFunc(context1, engineStartServerOpts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstartServerRunner_StartHTTPServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartHTTPServer'
type mockstartServerRunner_StartHTTPServer_Call struct {
	*mock.Call
}

// StartHTTPServer is a helper method to define mock.On call
//   - context1 context.Context
//   - engineStartServerOpts ...sumweave.EngineStartServerOpt
func (_e *mockstartServerRunner_Expecter) StartHTTPServer(context1 interface{}, engineStartServerOpts ...interface{}) *mockstartServerRunner_StartHTTPServer_Call {
	return &mockstartServerRunner_StartHTTPServer_Call{Call: _e.mock.On("StartHTTPServer",
		append([]interface{}{context1}, engineStartServerOpts...)...)}
}

func (_c *mockstartServerRunner_StartHTTPServer_Call) Run(run func(context1 context.Context, engineStartServerOpts ...sumweave.EngineStartServerOpt)) *mockstartServerRunner_StartHTTPServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []sumweave.EngineStartServerOpt
		variadicArgs := make([]sumweave.EngineStartServerOpt, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(sumweave.EngineStartServerOpt)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockstartServerRunner_StartHTTPServer_Call) Return(err error) *mockstartServerRunner_StartHTTPServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstartServerRunner_StartHTTPServer_Call) RunAndReturn(run func(context1 context.Context, engineStartServerOpts ...sumweave.EngineStartServerOpt) error) *mockstartServerRunner_StartHTTPServer_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstartAllHTTPServer creates a new instance of mockstartAllHTTPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstartAllHTTPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstartAllHTTPServer {
	mock := &mockstartAllHTTPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstartAllHTTPServer is an autogenerated mock type for the startAllHTTPServer type
type mockstartAllHTTPServer struct {
	mock.Mock
}

type mockstartAllHTTPServer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstartAllHTTPServer) EXPECT() *mockstartAllHTTPServer_Expecter {
	return &mockstartAllHTTPServer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockstartAllHTTPServer
func (_mock *mockstartAllHTTPServer) Close(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstartAllHTTPServer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockstartAllHTTPServer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockstartAllHTTPServer_Expecter) Close(context1 interface{}) *mockstartAllHTTPServer_Close_Call {
	return &mockstartAllHTTPServer_Close_Call{Call: _e.mock.On("Close", context1)}
}

func (_c *mockstartAllHTTPServer_Close_Call) Run(run func(context1 context.Context)) *mockstartAllHTTPServer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstartAllHTTPServer_Close_Call) Return(err error) *mockstartAllHTTPServer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstartAllHTTPServer_Close_Call) RunAndReturn(run func(context1 context.Context) error) *mockstartAllHTTPServer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// StartHTTPServer provides a mock function for the type mockstartAllHTTPServer
func (_mock *mockstartAllHTTPServer) StartHTTPServer(context1 context.Context, vs ...startHTTPServerOpt) error {
	// startHTTPServerOpt
	_va := make([]interface{}, len(vs))
	for _i := range vs {
		_va[_i] = vs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StartHTTPServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...startHTTPServerOpt) error); ok {
		r0 = returnFunc(context1, vs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstartAllHTTPServer_StartHTTPServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartHTTPServer'
type mockstartAllHTTPServer_StartHTTPServer_Call struct {
	*mock.Call
}

// StartHTTPServer is a helper method to define mock.On call
//   - context1 context.Context
//   - vs ...startHTTPServerOpt
func (_e *mockstartAllHTTPServer_Expecter) StartHTTPServer(context1 interface{}, vs ...interface{}) *mockstartAllHTTPServer_StartHTTPServer_Call {
	return &mockstartAllHTTPServer_StartHTTPServer_Call{Call: _e.mock.On("StartHTTPServer",
		append([]interface{}{context1}, vs...)...)}
}

func (_c *mockstartAllHTTPServer_StartHTTPServer_Call) Run(run func(context1 context.Context, vs ...startHTTPServerOpt)) *mockstartAllHTTPServer_StartHTTPServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []startHTTPServerOpt
		variadicArgs := make([]startHTTPServerOpt, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(startHTTPServerOpt)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockstartAllHTTPServer_StartHTTPServer_Call) Return(err error) *mockstartAllHTTPServer_StartHTTPServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstartAllHTTPServer_StartHTTPServer_Call) RunAndReturn(run func(context1 context.Context, vs ...startHTTPServerOpt) error) *mockstartAllHTTPServer_StartHTTPServer_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstartAllRunner creates a new instance of mockstartAllRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstartAllRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstartAllRunner {
	mock := &mockstartAllRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstartAllRunner is an autogenerated mock type for the startAllRunner type
type mockstartAllRunner struct {
	mock.Mock
}

type mockstartAllRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstartAllRunner) EXPECT() *mockstartAllRunner_Expecter {
	return &mockstartAllRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type mockstartAllRunner
func (_mock *mockstartAllRunner) Run(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstartAllRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockstartAllRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockstartAllRunner_Expecter) Run(context1 interface{}) *mockstartAllRunner_Run_Call {
	return &mockstartAllRunner_Run_Call{Call: _e.mock.On("Run", context1)}
}

func (_c *mockstartAllRunner_Run_Call) Run(run func(context1 context.Context)) *mockstartAllRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstartAllRunner_Run_Call) Return(err error) *mockstartAllRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstartAllRunner_Run_Call) RunAndReturn(run func(context1 context.Context) error) *mockstartAllRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// newMockuserCommandStore creates a new instance of mockuserCommandStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserCommandStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserCommandStore {
	mock := &mockuserCommandStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserCommandStore is an autogenerated mock type for the userCommandStore type
type mockuserCommandStore struct {
	mock.Mock
}

type mockuserCommandStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserCommandStore) EXPECT() *mockuserCommandStore_Expecter {
	return &mockuserCommandStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockuserCommandStore
func (_mock *mockuserCommandStore) Create(context1 context.Context, createUserParams auth.CreateUserParams) (*auth.User, error) {
	ret := _mock.Called(context1, createUserParams)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *auth.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.CreateUserParams) (*auth.User, error)); ok {
		return returnFunc(context1, createUserParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.CreateUserParams) *auth.User); ok {
		r0 = returnFunc(context1, createUserParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.CreateUserParams) error); ok {
		r1 = returnFunc(context1, createUserParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserCommandStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockuserCommandStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - createUserParams auth.CreateUserParams
func (_e *mockuserCommandStore_Expecter) Create(context1 interface{}, createUserParams interface{}) *mockuserCommandStore_Create_Call {
	return &mockuserCommandStore_Create_Call{Call: _e.mock.On("Create", context1, createUserParams)}
}

func (_c *mockuserCommandStore_Create_Call) Run(run func(context1 context.Context, createUserParams auth.CreateUserParams)) *mockuserCommandStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(auth.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserCommandStore_Create_Call) Return(user *auth.User, err error) *mockuserCommandStore_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserCommandStore_Create_Call) RunAndReturn(run func(context1 context.Context, createUserParams auth.CreateUserParams) (*auth.User, error)) *mockuserCommandStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type mockuserCommandStore
func (_mock *mockuserCommandStore) GetByUsername(context1 context.Context, s string) (*auth.User, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *auth.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.User, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.User); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserCommandStore_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type mockuserCommandStore_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *mockuserCommandStore_Expecter) GetByUsername(context1 interface{}, s interface{}) *mockuserCommandStore_GetByUsername_Call {
	return &mockuserCommandStore_GetByUsername_Call{Call: _e.mock.On("GetByUsername", context1, s)}
}

func (_c *mockuserCommandStore_GetByUsername_Call) Run(run func(context1 context.Context, s string)) *mockuserCommandStore_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserCommandStore_GetByUsername_Call) Return(user *auth.User, err error) *mockuserCommandStore_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserCommandStore_GetByUsername_Call) RunAndReturn(run func(context1 context.Context, s string) (*auth.User, error)) *mockuserCommandStore_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type mockuserCommandStore
func (_mock *mockuserCommandStore) List(context1 context.Context) ([]auth.User, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []auth.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]auth.User, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []auth.User); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auth.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserCommandStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockuserCommandStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockuserCommandStore_Expecter) List(context1 interface{}) *mockuserCommandStore_List_Call {
	return &mockuserCommandStore_List_Call{Call: _e.mock.On("List", context1)}
}

func (_c *mockuserCommandStore_List_Call) Run(run func(context1 context.Context)) *mockuserCommandStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockuserCommandStore_List_Call) Return(users []auth.User, err error) *mockuserCommandStore_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *mockuserCommandStore_List_Call) RunAndReturn(run func(context1 context.Context) ([]auth.User, error)) *mockuserCommandStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type mockuserCommandStore
func (_mock *mockuserCommandStore) UpdatePassword(context1 context.Context, s string, s1 string) error {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockuserCommandStore_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type mockuserCommandStore_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *mockuserCommandStore_Expecter) UpdatePassword(context1 interface{}, s interface{}, s1 interface{}) *mockuserCommandStore_UpdatePassword_Call {
	return &mockuserCommandStore_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", context1, s, s1)}
}

func (_c *mockuserCommandStore_UpdatePassword_Call) Run(run func(context1 context.Context, s string, s1 string)) *mockuserCommandStore_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockuserCommandStore_UpdatePassword_Call) Return(err error) *mockuserCommandStore_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockuserCommandStore_UpdatePassword_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) error) *mockuserCommandStore_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}
