// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewCandleAvailabilityTimeframeSummaryValidator() FieldValidator[*CandleAvailabilityTimeframeSummary] {
	validateTimeframe := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStart := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateEnd := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateCount := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	
	return func(bindingCtx *BindingContext, value *CandleAvailabilityTimeframeSummary) {
		validateTimeframe(bindingCtx.Fork("timeframe"), value.Timeframe)
		validateStart(bindingCtx.Fork("start"), value.Start)
		validateEnd(bindingCtx.Fork("end"), value.End)
		validateCount(bindingCtx.Fork("count"), value.Count)
	}
}
