// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewCandleAvailabilityDefaultSelectionValidator() FieldValidator[*CandleAvailabilityDefaultSelection] {
	validateVenue := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSymbol := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAssetClass := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateTimeframe := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStart := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateEnd := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *CandleAvailabilityDefaultSelection) {
		validateVenue(bindingCtx.Fork("venue"), value.Venue)
		validateSymbol(bindingCtx.Fork("symbol"), value.Symbol)
		validateAssetClass(bindingCtx.Fork("assetClass"), value.AssetClass)
		validateTimeframe(bindingCtx.Fork("timeframe"), value.Timeframe)
		validateStart(bindingCtx.Fork("start"), value.Start)
		validateEnd(bindingCtx.Fork("end"), value.End)
	}
}
