// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewCandleAvailabilityItemValidator() FieldValidator[*CandleAvailabilityItem] {
	validateVenue := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSymbol := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAssetClass := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateTimeframes := NewArrayValidator[*CandleAvailabilityTimeframeSummary](
		NewSimpleFieldValidator[[]*CandleAvailabilityTimeframeSummary](
			EnsureArrayFieldRequired,
		),
		NewCandleAvailabilityTimeframeSummaryValidator(),
	)
	validateDefaultSlice := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewCandleAvailabilityDefaultSliceValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *CandleAvailabilityItem) {
		validateVenue(bindingCtx.Fork("venue"), value.Venue)
		validateSymbol(bindingCtx.Fork("symbol"), value.Symbol)
		validateAssetClass(bindingCtx.Fork("assetClass"), value.AssetClass)
		validateTimeframes(bindingCtx.Fork("timeframes"), value.Timeframes)
		validateDefaultSlice(bindingCtx.Fork("defaultSlice"), value.DefaultSlice)
	}
}
