// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewCandleAvailabilityListResponseValidator() FieldValidator[*CandleAvailabilityListResponse] {
	validateItems := NewArrayValidator[*CandleAvailabilityItem](
		NewSimpleFieldValidator[[]*CandleAvailabilityItem](
			EnsureArrayFieldRequired,
		),
		NewCandleAvailabilityItemValidator(),
	)
	validateNextCursor := NewSimpleFieldValidator[string](
	)
	validateDefaultSelection := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: false, Nullable: false},
		NewCandleAvailabilityDefaultSelectionValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *CandleAvailabilityListResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
		validateNextCursor(bindingCtx.Fork("nextCursor"), value.NextCursor)
		validateDefaultSelection(bindingCtx.Fork("defaultSelection"), value.DefaultSelection)
	}
}
