// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTransactionProviderOriginalValidator() FieldValidator[*FinanceTransactionProviderOriginal] {
	validateAmountMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateCurrency := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDescription := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateEffectiveAt := NewSimpleFieldValidator[*time.Time](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTransactionProviderOriginal) {
		validateAmountMinor(bindingCtx.Fork("amountMinor"), value.AmountMinor)
		validateCurrency(bindingCtx.Fork("currency"), value.Currency)
		validateDescription(bindingCtx.Fork("description"), value.Description)
		validateEffectiveAt(bindingCtx.Fork("effectiveAt"), value.EffectiveAt)
	}
}
