// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceRenameRequestValidator() FieldValidator[*FinanceRenameRequest] {
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceRenameRequest) {
		validateName(bindingCtx.Fork("name"), value.Name)
	}
}
