// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTenantInvitesResponseValidator() FieldValidator[*FinanceTenantInvitesResponse] {
	validateItems := NewArrayValidator[*FinanceTenantInvite](
		NewSimpleFieldValidator[[]*FinanceTenantInvite](
			EnsureArrayFieldRequired,
		),
		NewFinanceTenantInviteValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTenantInvitesResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
	}
}
