// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceCsvImportPreviewRequestValidator() FieldValidator[*FinanceCsvImportPreviewRequest] {
	validateImportType := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateFileName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateCsv := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceCsvImportPreviewRequest) {
		validateImportType(bindingCtx.Fork("importType"), value.ImportType)
		validateFileName(bindingCtx.Fork("fileName"), value.FileName)
		validateCsv(bindingCtx.Fork("csv"), value.Csv)
	}
}
