// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTenantMemberValidator() FieldValidator[*FinanceTenantMember] {
	validateTenantID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateUserID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateUsername := NewSimpleFieldValidator[*string](
	)
	validateJoinedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTenantMember) {
		validateTenantID(bindingCtx.Fork("tenantId"), value.TenantID)
		validateUserID(bindingCtx.Fork("userId"), value.UserID)
		validateUsername(bindingCtx.Fork("username"), value.Username)
		validateJoinedAt(bindingCtx.Fork("joinedAt"), value.JoinedAt)
	}
}
