// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceFxDiagnosticsResponseProvidersInnerValidator() FieldValidator[*FinanceFxDiagnosticsResponseProvidersInner] {
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDefault := NewSimpleFieldValidator[bool](
	)
	validateReady := NewSimpleFieldValidator[bool](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceFxDiagnosticsResponseProvidersInner) {
		validateName(bindingCtx.Fork("name"), value.Name)
		validateDefault(bindingCtx.Fork("default"), value.Default)
		validateReady(bindingCtx.Fork("ready"), value.Ready)
	}
}
