// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTransactionValidator() FieldValidator[*FinanceTransaction] {
	validateID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateTenantID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAccountID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSource := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStatus := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateKind := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAmountMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateCurrency := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDescription := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateEffectiveAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateCategoryID := NewSimpleFieldValidator[string](
	)
	validateTransferGroupID := NewSimpleFieldValidator[string](
	)
	validateTransferMatchedAt := NewSimpleFieldValidator[time.Time](
	)
	validateHiddenAt := NewSimpleFieldValidator[time.Time](
	)
	validateProviderOriginal := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: false, Nullable: false},
		NewFinanceTransactionProviderOriginalValidator(),
	)
	validateCreatedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateUpdatedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTransaction) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateTenantID(bindingCtx.Fork("tenantId"), value.TenantID)
		validateAccountID(bindingCtx.Fork("accountId"), value.AccountID)
		validateSource(bindingCtx.Fork("source"), value.Source)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validateKind(bindingCtx.Fork("kind"), value.Kind)
		validateAmountMinor(bindingCtx.Fork("amountMinor"), value.AmountMinor)
		validateCurrency(bindingCtx.Fork("currency"), value.Currency)
		validateDescription(bindingCtx.Fork("description"), value.Description)
		validateEffectiveAt(bindingCtx.Fork("effectiveAt"), value.EffectiveAt)
		validateCategoryID(bindingCtx.Fork("categoryId"), value.CategoryID)
		validateTransferGroupID(bindingCtx.Fork("transferGroupId"), value.TransferGroupID)
		validateTransferMatchedAt(bindingCtx.Fork("transferMatchedAt"), value.TransferMatchedAt)
		validateHiddenAt(bindingCtx.Fork("hiddenAt"), value.HiddenAt)
		validateProviderOriginal(bindingCtx.Fork("providerOriginal"), value.ProviderOriginal)
		validateCreatedAt(bindingCtx.Fork("createdAt"), value.CreatedAt)
		validateUpdatedAt(bindingCtx.Fork("updatedAt"), value.UpdatedAt)
	}
}
