// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTransferPairRequestValidator() FieldValidator[*FinanceTransferPairRequest] {
	validateFirstTransactionID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSecondTransactionID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTransferPairRequest) {
		validateFirstTransactionID(bindingCtx.Fork("firstTransactionId"), value.FirstTransactionID)
		validateSecondTransactionID(bindingCtx.Fork("secondTransactionId"), value.SecondTransactionID)
	}
}
