// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTenantMembersResponseValidator() FieldValidator[*FinanceTenantMembersResponse] {
	validateItems := NewArrayValidator[*FinanceTenantMember](
		NewSimpleFieldValidator[[]*FinanceTenantMember](
			EnsureArrayFieldRequired,
		),
		NewFinanceTenantMemberValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTenantMembersResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
	}
}
