// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceProviderEvidenceValidator() FieldValidator[*FinanceProviderEvidence] {
	validateID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateScope := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateProviderObjectID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateCapturedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validatePayload := NewSimpleFieldValidator[map[string]interface{}](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceProviderEvidence) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateScope(bindingCtx.Fork("scope"), value.Scope)
		validateProviderObjectID(bindingCtx.Fork("providerObjectId"), value.ProviderObjectID)
		validateCapturedAt(bindingCtx.Fork("capturedAt"), value.CapturedAt)
		validatePayload(bindingCtx.Fork("payload"), value.Payload)
	}
}
