// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceDashboardMissingFxValidator() FieldValidator[*FinanceDashboardMissingFx] {
	validateSource := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateTransactionID := NewSimpleFieldValidator[*string](
		SkipNullValidator(EnsureNonDefault[string]),
	)
	validateAccountID := NewSimpleFieldValidator[*string](
		SkipNullValidator(EnsureNonDefault[string]),
	)
	validateBaseCurrency := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateQuoteCurrency := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateRateDate := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateProvider := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceDashboardMissingFx) {
		validateSource(bindingCtx.Fork("source"), value.Source)
		validateTransactionID(bindingCtx.Fork("transactionId"), value.TransactionID)
		validateAccountID(bindingCtx.Fork("accountId"), value.AccountID)
		validateBaseCurrency(bindingCtx.Fork("baseCurrency"), value.BaseCurrency)
		validateQuoteCurrency(bindingCtx.Fork("quoteCurrency"), value.QuoteCurrency)
		validateRateDate(bindingCtx.Fork("rateDate"), value.RateDate)
		validateProvider(bindingCtx.Fork("provider"), value.Provider)
	}
}
