// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewJobRequesterValidator() FieldValidator[*JobRequester] {
	validateUserID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSource := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAgentSessionID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAgentRunID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *JobRequester) {
		validateUserID(bindingCtx.Fork("userId"), value.UserID)
		validateSource(bindingCtx.Fork("source"), value.Source)
		validateAgentSessionID(bindingCtx.Fork("agentSessionId"), value.AgentSessionID)
		validateAgentRunID(bindingCtx.Fork("agentRunId"), value.AgentRunID)
	}
}
