// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewJobListResponseValidator() FieldValidator[*JobListResponse] {
	validateItems := NewArrayValidator[*JobSummary](
		NewSimpleFieldValidator[[]*JobSummary](
			EnsureArrayFieldRequired,
		),
		NewJobSummaryValidator(),
	)
	validateNextCursor := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *JobListResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
		validateNextCursor(bindingCtx.Fork("nextCursor"), value.NextCursor)
	}
}
