// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewJobDetailResponseValidator() FieldValidator[*JobDetailResponse] {
	validateID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateJobType := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStatus := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateRequester := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewJobRequesterValidator(),
	)
	validateCreatedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateUpdatedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateStartedAt := NewSimpleFieldValidator[*time.Time](
	)
	validateCompletedAt := NewSimpleFieldValidator[*time.Time](
	)
	validateAttemptCount := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateError := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: false, Nullable: false},
		NewJobErrorValidator(),
	)
	validateWorkerID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateLastAttemptAt := NewSimpleFieldValidator[*time.Time](
	)
	
	return func(bindingCtx *BindingContext, value *JobDetailResponse) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateJobType(bindingCtx.Fork("jobType"), value.JobType)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validateRequester(bindingCtx.Fork("requester"), value.Requester)
		validateCreatedAt(bindingCtx.Fork("createdAt"), value.CreatedAt)
		validateUpdatedAt(bindingCtx.Fork("updatedAt"), value.UpdatedAt)
		validateStartedAt(bindingCtx.Fork("startedAt"), value.StartedAt)
		validateCompletedAt(bindingCtx.Fork("completedAt"), value.CompletedAt)
		validateAttemptCount(bindingCtx.Fork("attemptCount"), value.AttemptCount)
		validateError(bindingCtx.Fork("error"), value.Error)
		validateWorkerID(bindingCtx.Fork("workerId"), value.WorkerID)
		validateLastAttemptAt(bindingCtx.Fork("lastAttemptAt"), value.LastAttemptAt)
	}
}
