// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewJobTimeRangeValidator() FieldValidator[*JobTimeRange] {
	validateStart := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateEnd := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *JobTimeRange) {
		validateStart(bindingCtx.Fork("start"), value.Start)
		validateEnd(bindingCtx.Fork("end"), value.End)
	}
}
