// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewRawPayloadMetadataValidator() FieldValidator[*RawPayloadMetadata] {
	validateID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateIngestionRunID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSource := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateVenue := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateEndpoint := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateRequestType := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateRequestPayloadHash := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateRequestAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateResponseAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateHttpStatus := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateResponseBodyHash := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validatePayloadBodyRef := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateEntityHint := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSymbol := NewSimpleFieldValidator[string](
	)
	validateAssetClass := NewSimpleFieldValidator[string](
	)
	validateTimeframe := NewSimpleFieldValidator[string](
	)
	validateStart := NewSimpleFieldValidator[*time.Time](
	)
	validateEnd := NewSimpleFieldValidator[*time.Time](
	)
	validateReceivedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *RawPayloadMetadata) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateIngestionRunID(bindingCtx.Fork("ingestionRunId"), value.IngestionRunID)
		validateSource(bindingCtx.Fork("source"), value.Source)
		validateVenue(bindingCtx.Fork("venue"), value.Venue)
		validateEndpoint(bindingCtx.Fork("endpoint"), value.Endpoint)
		validateRequestType(bindingCtx.Fork("requestType"), value.RequestType)
		validateRequestPayloadHash(bindingCtx.Fork("requestPayloadHash"), value.RequestPayloadHash)
		validateRequestAt(bindingCtx.Fork("requestAt"), value.RequestAt)
		validateResponseAt(bindingCtx.Fork("responseAt"), value.ResponseAt)
		validateHttpStatus(bindingCtx.Fork("httpStatus"), value.HttpStatus)
		validateResponseBodyHash(bindingCtx.Fork("responseBodyHash"), value.ResponseBodyHash)
		validatePayloadBodyRef(bindingCtx.Fork("payloadBodyRef"), value.PayloadBodyRef)
		validateEntityHint(bindingCtx.Fork("entityHint"), value.EntityHint)
		validateSymbol(bindingCtx.Fork("symbol"), value.Symbol)
		validateAssetClass(bindingCtx.Fork("assetClass"), value.AssetClass)
		validateTimeframe(bindingCtx.Fork("timeframe"), value.Timeframe)
		validateStart(bindingCtx.Fork("start"), value.Start)
		validateEnd(bindingCtx.Fork("end"), value.End)
		validateReceivedAt(bindingCtx.Fork("receivedAt"), value.ReceivedAt)
	}
}
