// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewStrategyValidationPreviewValidator() FieldValidator[*StrategyValidationPreview] {
	validateSchemaVersion := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateKind := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateInstrument := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewStrategyDefinitionInstrumentValidator(),
	)
	validateTimeframe := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateParameterSummary := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewStrategyParameterSummaryValidator(),
	)
	validateCanonicalJson := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateArtifactHash := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateExistingArtifact := NewSimpleFieldValidator[bool](
	)
	
	return func(bindingCtx *BindingContext, value *StrategyValidationPreview) {
		validateSchemaVersion(bindingCtx.Fork("schemaVersion"), value.SchemaVersion)
		validateKind(bindingCtx.Fork("kind"), value.Kind)
		validateInstrument(bindingCtx.Fork("instrument"), value.Instrument)
		validateTimeframe(bindingCtx.Fork("timeframe"), value.Timeframe)
		validateParameterSummary(bindingCtx.Fork("parameterSummary"), value.ParameterSummary)
		validateCanonicalJson(bindingCtx.Fork("canonicalJson"), value.CanonicalJson)
		validateArtifactHash(bindingCtx.Fork("artifactHash"), value.ArtifactHash)
		validateExistingArtifact(bindingCtx.Fork("existingArtifact"), value.ExistingArtifact)
	}
}
