// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewStrategyVersionDetailValidator() FieldValidator[*StrategyVersionDetail] {
	validateStrategyID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateVersion := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDisplayName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStatus := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSourceType := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSourceLabel := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateArtifactHash := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSchemaVersion := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateKind := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateInstrument := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewStrategyDefinitionInstrumentValidator(),
	)
	validateTimeframe := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateParameterSummary := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewStrategyParameterSummaryValidator(),
	)
	validateNotes := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateCreatedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateUpdatedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateDefinition := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewStrategyDefinitionValidator(),
	)
	validateParentStrategyID := NewSimpleFieldValidator[string](
	)
	validateParentVersion := NewSimpleFieldValidator[string](
	)
	
	return func(bindingCtx *BindingContext, value *StrategyVersionDetail) {
		validateStrategyID(bindingCtx.Fork("strategyId"), value.StrategyID)
		validateVersion(bindingCtx.Fork("version"), value.Version)
		validateDisplayName(bindingCtx.Fork("displayName"), value.DisplayName)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validateSourceType(bindingCtx.Fork("sourceType"), value.SourceType)
		validateSourceLabel(bindingCtx.Fork("sourceLabel"), value.SourceLabel)
		validateArtifactHash(bindingCtx.Fork("artifactHash"), value.ArtifactHash)
		validateSchemaVersion(bindingCtx.Fork("schemaVersion"), value.SchemaVersion)
		validateKind(bindingCtx.Fork("kind"), value.Kind)
		validateInstrument(bindingCtx.Fork("instrument"), value.Instrument)
		validateTimeframe(bindingCtx.Fork("timeframe"), value.Timeframe)
		validateParameterSummary(bindingCtx.Fork("parameterSummary"), value.ParameterSummary)
		validateNotes(bindingCtx.Fork("notes"), value.Notes)
		validateCreatedAt(bindingCtx.Fork("createdAt"), value.CreatedAt)
		validateUpdatedAt(bindingCtx.Fork("updatedAt"), value.UpdatedAt)
		validateDefinition(bindingCtx.Fork("definition"), value.Definition)
		validateParentStrategyID(bindingCtx.Fork("parentStrategyId"), value.ParentStrategyID)
		validateParentVersion(bindingCtx.Fork("parentVersion"), value.ParentVersion)
	}
}
