// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewStrategyVersionCandidateValidator() FieldValidator[*StrategyVersionCandidate] {
	validateStrategyID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateVersion := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDisplayName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStatus := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSourceType := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSourceLabel := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateNotes := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDefinition := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewStrategyDefinitionValidator(),
	)
	validateParentStrategyID := NewSimpleFieldValidator[string](
	)
	validateParentVersion := NewSimpleFieldValidator[string](
	)
	
	return func(bindingCtx *BindingContext, value *StrategyVersionCandidate) {
		validateStrategyID(bindingCtx.Fork("strategyId"), value.StrategyID)
		validateVersion(bindingCtx.Fork("version"), value.Version)
		validateDisplayName(bindingCtx.Fork("displayName"), value.DisplayName)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validateSourceType(bindingCtx.Fork("sourceType"), value.SourceType)
		validateSourceLabel(bindingCtx.Fork("sourceLabel"), value.SourceLabel)
		validateNotes(bindingCtx.Fork("notes"), value.Notes)
		validateDefinition(bindingCtx.Fork("definition"), value.Definition)
		validateParentStrategyID(bindingCtx.Fork("parentStrategyId"), value.ParentStrategyID)
		validateParentVersion(bindingCtx.Fork("parentVersion"), value.ParentVersion)
	}
}
