// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewStrategyDefinitionParametersValidator() FieldValidator[*StrategyDefinitionParameters] {
	validateFastWindow := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateSlowWindow := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	
	return func(bindingCtx *BindingContext, value *StrategyDefinitionParameters) {
		validateFastWindow(bindingCtx.Fork("fastWindow"), value.FastWindow)
		validateSlowWindow(bindingCtx.Fork("slowWindow"), value.SlowWindow)
	}
}
