// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/signal-foundry/apps/signal-foundry/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewStrategyDefinitionInstrumentValidator() FieldValidator[*StrategyDefinitionInstrument] {
	validateVenue := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSymbol := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAssetClass := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateActive := NewSimpleFieldValidator[bool](
	)
	
	return func(bindingCtx *BindingContext, value *StrategyDefinitionInstrument) {
		validateVenue(bindingCtx.Fork("venue"), value.Venue)
		validateSymbol(bindingCtx.Fork("symbol"), value.Symbol)
		validateAssetClass(bindingCtx.Fork("assetClass"), value.AssetClass)
		validateActive(bindingCtx.Fork("active"), value.Active)
	}
}
