// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewAccessTokenListResponseValidator() FieldValidator[*AccessTokenListResponse] {
	validateItems := NewArrayValidator[*AccessTokenMetadata](
		NewSimpleFieldValidator[[]*AccessTokenMetadata](
			EnsureArrayFieldRequired,
		),
		NewAccessTokenMetadataValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *AccessTokenListResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
	}
}
