// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewAuthSessionResponseValidator() FieldValidator[*AuthSessionResponse] {
	validateAccessToken := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateRefreshToken := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateUser := NewObjectFieldValidator(
		ObjectFieldValidatorParams{Required: true, Nullable: false},
		NewUserInfoValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *AuthSessionResponse) {
		validateAccessToken(bindingCtx.Fork("accessToken"), value.AccessToken)
		validateRefreshToken(bindingCtx.Fork("refreshToken"), value.RefreshToken)
		validateUser(bindingCtx.Fork("user"), value.User)
	}
}
