// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewErrorValidator() FieldValidator[*Error] {
	validateCode := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateMessage := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateCorrelationID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *Error) {
		validateCode(bindingCtx.Fork("code"), value.Code)
		validateMessage(bindingCtx.Fork("message"), value.Message)
		validateCorrelationID(bindingCtx.Fork("correlationId"), value.CorrelationID)
	}
}
