// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceConnectionLinkTokenRequestValidator() FieldValidator[*FinanceConnectionLinkTokenRequest] {
	validateProvider := NewSimpleFieldValidator[FinanceBankLinkTokenProvider](
		EnsureNonDefault[FinanceBankLinkTokenProvider],
	)
	validateToken := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceConnectionLinkTokenRequest) {
		validateProvider(bindingCtx.Fork("provider"), value.Provider)
		validateToken(bindingCtx.Fork("token"), value.Token)
	}
}
