// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceCsvImportAuditResponseValidator() FieldValidator[*FinanceCsvImportAuditResponse] {
	validateImportID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateTenantID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStatus := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateJobID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateConfirmedByUserID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateImportedCount := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateRejectedRows := NewArrayValidator[*FinanceCsvImportRowDiagnostic](
		NewSimpleFieldValidator[[]*FinanceCsvImportRowDiagnostic](
			EnsureArrayFieldRequired,
		),
		NewFinanceCsvImportRowDiagnosticValidator(),
	)
	validateRowOutcomes := NewArrayValidator[*FinanceCsvImportRowOutcome](
		NewSimpleFieldValidator[[]*FinanceCsvImportRowOutcome](
			EnsureArrayFieldRequired,
		),
		NewFinanceCsvImportRowOutcomeValidator(),
	)
	validateCreatedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateConfirmedAt := NewSimpleFieldValidator[*time.Time](
	)
	validateCompletedAt := NewSimpleFieldValidator[*time.Time](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceCsvImportAuditResponse) {
		validateImportID(bindingCtx.Fork("importId"), value.ImportID)
		validateTenantID(bindingCtx.Fork("tenantId"), value.TenantID)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validateJobID(bindingCtx.Fork("jobId"), value.JobID)
		validateConfirmedByUserID(bindingCtx.Fork("confirmedByUserId"), value.ConfirmedByUserID)
		validateImportedCount(bindingCtx.Fork("importedCount"), value.ImportedCount)
		validateRejectedRows(bindingCtx.Fork("rejectedRows"), value.RejectedRows)
		validateRowOutcomes(bindingCtx.Fork("rowOutcomes"), value.RowOutcomes)
		validateCreatedAt(bindingCtx.Fork("createdAt"), value.CreatedAt)
		validateConfirmedAt(bindingCtx.Fork("confirmedAt"), value.ConfirmedAt)
		validateCompletedAt(bindingCtx.Fork("completedAt"), value.CompletedAt)
	}
}
