// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTenantCreateRequestValidator() FieldValidator[*FinanceTenantCreateRequest] {
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDisplayCurrency := NewSimpleFieldValidator[FinanceTenantDisplayCurrency](
		EnsureNonDefault[FinanceTenantDisplayCurrency],
	)
	validateSeedDefaults := NewSimpleFieldValidator[*bool](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTenantCreateRequest) {
		validateName(bindingCtx.Fork("name"), value.Name)
		validateDisplayCurrency(bindingCtx.Fork("displayCurrency"), value.DisplayCurrency)
		validateSeedDefaults(bindingCtx.Fork("seedDefaults"), value.SeedDefaults)
	}
}
