// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTransactionClassificationRequestValidator() FieldValidator[*FinanceTransactionClassificationRequest] {
	validateRangeStart := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateRangeEndExclusive := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTransactionClassificationRequest) {
		validateRangeStart(bindingCtx.Fork("rangeStart"), value.RangeStart)
		validateRangeEndExclusive(bindingCtx.Fork("rangeEndExclusive"), value.RangeEndExclusive)
	}
}
