// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

// We don't need to validate enums. This file is just a placeholder.
// Below is to workaround unused imports.
var _ FinanceBankLinkTokenProvider
