// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceCsvImportRowDiagnosticValidator() FieldValidator[*FinanceCsvImportRowDiagnostic] {
	validateRowNumber := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateField := NewSimpleFieldValidator[string](
	)
	validateReason := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceCsvImportRowDiagnostic) {
		validateRowNumber(bindingCtx.Fork("rowNumber"), value.RowNumber)
		validateField(bindingCtx.Fork("field"), value.Field)
		validateReason(bindingCtx.Fork("reason"), value.Reason)
	}
}
