// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceCategoryUpdateRequestValidator() FieldValidator[*FinanceCategoryUpdateRequest] {
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateKind := NewSimpleFieldValidator[FinanceCategoryUpdateRequestKind](
		EnsureNonDefault[FinanceCategoryUpdateRequestKind],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceCategoryUpdateRequest) {
		validateName(bindingCtx.Fork("name"), value.Name)
		validateKind(bindingCtx.Fork("kind"), value.Kind)
	}
}
