// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTransferMatchingJobResponseValidator() FieldValidator[*FinanceTransferMatchingJobResponse] {
	validateJobID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTransferMatchingJobResponse) {
		validateJobID(bindingCtx.Fork("jobId"), value.JobID)
	}
}
