// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceCashFlowSeriesBucketValidator() FieldValidator[*FinanceCashFlowSeriesBucket] {
	validateStartDate := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateEndDate := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateIncomeMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateExpenseMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceCashFlowSeriesBucket) {
		validateStartDate(bindingCtx.Fork("startDate"), value.StartDate)
		validateEndDate(bindingCtx.Fork("endDate"), value.EndDate)
		validateIncomeMinor(bindingCtx.Fork("incomeMinor"), value.IncomeMinor)
		validateExpenseMinor(bindingCtx.Fork("expenseMinor"), value.ExpenseMinor)
	}
}
