// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceConnectionLinkRedirectStartRequestValidator() FieldValidator[*FinanceConnectionLinkRedirectStartRequest] {
	validateProvider := NewSimpleFieldValidator[FinanceBankLinkRedirectProvider](
		EnsureNonDefault[FinanceBankLinkRedirectProvider],
	)
	validateCallbackUrl := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceConnectionLinkRedirectStartRequest) {
		validateProvider(bindingCtx.Fork("provider"), value.Provider)
		validateCallbackUrl(bindingCtx.Fork("callbackUrl"), value.CallbackUrl)
	}
}
