// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTenantUpdateRequestValidator() FieldValidator[*FinanceTenantUpdateRequest] {
	validateName := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDisplayCurrency := NewSimpleFieldValidator[FinanceTenantDisplayCurrency](
		EnsureNonDefault[FinanceTenantDisplayCurrency],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTenantUpdateRequest) {
		validateName(bindingCtx.Fork("name"), value.Name)
		validateDisplayCurrency(bindingCtx.Fork("displayCurrency"), value.DisplayCurrency)
	}
}
