// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceProviderSnapshotMetadataValidator() FieldValidator[*FinanceProviderSnapshotMetadata] {
	validateID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateKind := NewSimpleFieldValidator[FinanceProviderSnapshotMetadataKind](
		EnsureNonDefault[FinanceProviderSnapshotMetadataKind],
	)
	validateProviderObjectID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateCapturedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceProviderSnapshotMetadata) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateKind(bindingCtx.Fork("kind"), value.Kind)
		validateProviderObjectID(bindingCtx.Fork("providerObjectId"), value.ProviderObjectID)
		validateCapturedAt(bindingCtx.Fork("capturedAt"), value.CapturedAt)
	}
}
