// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceProviderSnapshotValidator() FieldValidator[*FinanceProviderSnapshot] {
	validateID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateKind := NewSimpleFieldValidator[FinanceProviderSnapshotKind](
		EnsureNonDefault[FinanceProviderSnapshotKind],
	)
	validateProviderObjectID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateCapturedAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateData := NewSimpleFieldValidator[map[string]interface{}](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceProviderSnapshot) {
		validateID(bindingCtx.Fork("id"), value.ID)
		validateKind(bindingCtx.Fork("kind"), value.Kind)
		validateProviderObjectID(bindingCtx.Fork("providerObjectId"), value.ProviderObjectID)
		validateCapturedAt(bindingCtx.Fork("capturedAt"), value.CapturedAt)
		validateData(bindingCtx.Fork("data"), value.Data)
	}
}
