// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceCsvImportAuditsResponseValidator() FieldValidator[*FinanceCsvImportAuditsResponse] {
	validateItems := NewArrayValidator[*FinanceCsvImportAuditResponse](
		NewSimpleFieldValidator[[]*FinanceCsvImportAuditResponse](
			EnsureArrayFieldRequired,
		),
		NewFinanceCsvImportAuditResponseValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *FinanceCsvImportAuditsResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
	}
}
