// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceTransactionCreateRequestValidator() FieldValidator[*FinanceTransactionCreateRequest] {
	validateAccountID := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateSource := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateStatus := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateKind := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateAmountMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateCurrency := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateDescription := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateEffectiveAt := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateCategoryID := NewSimpleFieldValidator[string](
	)
	validateTagIDs := NewArrayValidator[string](
		NewSimpleFieldValidator[[]string](
		),
		NewSimpleFieldValidator[string](
			),
	)
	validateTransferGroupID := NewSimpleFieldValidator[string](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceTransactionCreateRequest) {
		validateAccountID(bindingCtx.Fork("accountId"), value.AccountID)
		validateSource(bindingCtx.Fork("source"), value.Source)
		validateStatus(bindingCtx.Fork("status"), value.Status)
		validateKind(bindingCtx.Fork("kind"), value.Kind)
		validateAmountMinor(bindingCtx.Fork("amountMinor"), value.AmountMinor)
		validateCurrency(bindingCtx.Fork("currency"), value.Currency)
		validateDescription(bindingCtx.Fork("description"), value.Description)
		validateEffectiveAt(bindingCtx.Fork("effectiveAt"), value.EffectiveAt)
		validateCategoryID(bindingCtx.Fork("categoryId"), value.CategoryID)
		validateTagIDs(bindingCtx.Fork("tagIds"), value.TagIDs)
		validateTransferGroupID(bindingCtx.Fork("transferGroupId"), value.TransferGroupID)
	}
}
