// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceProviderSnapshotListResponseValidator() FieldValidator[*FinanceProviderSnapshotListResponse] {
	validateItems := NewArrayValidator[*FinanceProviderSnapshotMetadata](
		NewSimpleFieldValidator[[]*FinanceProviderSnapshotMetadata](
			EnsureArrayFieldRequired,
		),
		NewFinanceProviderSnapshotMetadataValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *FinanceProviderSnapshotListResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
	}
}
