// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceAccountsResponseValidator() FieldValidator[*FinanceAccountsResponse] {
	validateItems := NewArrayValidator[*FinanceAccount](
		NewSimpleFieldValidator[[]*FinanceAccount](
			EnsureArrayFieldRequired,
		),
		NewFinanceAccountValidator(),
	)
	
	return func(bindingCtx *BindingContext, value *FinanceAccountsResponse) {
		validateItems(bindingCtx.Fork("items"), value.Items)
	}
}
