// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceDashboardMoneySummaryValidator() FieldValidator[*FinanceDashboardMoneySummary] {
	validateDisplayCurrency := NewSimpleFieldValidator[string](
		EnsureNonDefault[string],
	)
	validateIncomeMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateExpenseMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateNetMinor := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateTransactionCount := NewSimpleFieldValidator[int64](
		EnsureNonDefault[int64],
	)
	validateComplete := NewSimpleFieldValidator[bool](
	)
	
	return func(bindingCtx *BindingContext, value *FinanceDashboardMoneySummary) {
		validateDisplayCurrency(bindingCtx.Fork("displayCurrency"), value.DisplayCurrency)
		validateIncomeMinor(bindingCtx.Fork("incomeMinor"), value.IncomeMinor)
		validateExpenseMinor(bindingCtx.Fork("expenseMinor"), value.ExpenseMinor)
		validateNetMinor(bindingCtx.Fork("netMinor"), value.NetMinor)
		validateTransactionCount(bindingCtx.Fork("transactionCount"), value.TransactionCount)
		validateComplete(bindingCtx.Fork("complete"), value.Complete)
	}
}
