// Code generated by apigen DO NOT EDIT.

package internal

import (
	"time"
	. "github.com/gemyago/sumweave/apps/sumweave/internal/api/http/v1routes/models"
)

// Below is to workaround unused imports.
var _ = time.Time{}

func NewFinanceDashboardPeriodWindowValidator() FieldValidator[*FinanceDashboardPeriodWindow] {
	validateStartDate := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	validateEndDate := NewSimpleFieldValidator[time.Time](
		EnsureNonDefault[time.Time],
	)
	
	return func(bindingCtx *BindingContext, value *FinanceDashboardPeriodWindow) {
		validateStartDate(bindingCtx.Fork("startDate"), value.StartDate)
		validateEndDate(bindingCtx.Fork("endDate"), value.EndDate)
	}
}
