// Code generated by apigen DO NOT EDIT.

package internal

// PreviewFinanceAccountCsvImportParams is request parameters model. The validation for 
// parameters model is performed at parsing stage.
