// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build !release

package agentapi

import (
	"context"

	"github.com/gemyago/signal-foundry/runtime/internal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockModelsLister creates a new instance of MockModelsLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelsLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelsLister {
	mock := &MockModelsLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModelsLister is an autogenerated mock type for the ModelsLister type
type MockModelsLister struct {
	mock.Mock
}

type MockModelsLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelsLister) EXPECT() *MockModelsLister_Expecter {
	return &MockModelsLister_Expecter{mock: &_m.Mock}
}

// ListModels provides a mock function for the type MockModelsLister
func (_mock *MockModelsLister) ListModels(ctx context.Context) ([]internal.ModelInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListModels")
	}

	var r0 []internal.ModelInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]internal.ModelInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []internal.ModelInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]internal.ModelInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModelsLister_ListModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModels'
type MockModelsLister_ListModels_Call struct {
	*mock.Call
}

// ListModels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockModelsLister_Expecter) ListModels(ctx interface{}) *MockModelsLister_ListModels_Call {
	return &MockModelsLister_ListModels_Call{Call: _e.mock.On("ListModels", ctx)}
}

func (_c *MockModelsLister_ListModels_Call) Run(run func(ctx context.Context)) *MockModelsLister_ListModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockModelsLister_ListModels_Call) Return(modelInfos []internal.ModelInfo, err error) *MockModelsLister_ListModels_Call {
	_c.Call.Return(modelInfos, err)
	return _c
}

func (_c *MockModelsLister_ListModels_Call) RunAndReturn(run func(ctx context.Context) ([]internal.ModelInfo, error)) *MockModelsLister_ListModels_Call {
	_c.Call.Return(run)
	return _c
}
