#!/usr/bin/env bash
# Generate OpenCode sub-agents from .agents/prompts/openspec-manager/config.yaml.
# Usage: .agents/prompts/openspec-manager/sync-opencode-agents.sh [path-to-yaml]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
MANAGER_PROMPTS_DIR="$SCRIPT_DIR"
CONFIG="${1:-$MANAGER_PROMPTS_DIR/config.yaml}"
AGENTS_DIR="$REPO_ROOT/.opencode/agents"

if [[ ! -f "$CONFIG" ]]; then
  echo "error: config not found: $CONFIG" >&2
  exit 1
fi

if [[ ! -d "$MANAGER_PROMPTS_DIR" ]]; then
  echo "error: manager prompts dir not found: $MANAGER_PROMPTS_DIR" >&2
  exit 1
fi

mkdir -p "$AGENTS_DIR"

mapfile -t written < <(python3 - "$CONFIG" "$AGENTS_DIR" "$MANAGER_PROMPTS_DIR" <<'PY'
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("error: PyYAML is required (pip install pyyaml)")

config_path = Path(sys.argv[1])
agents_dir = Path(sys.argv[2])
manager_prompts_dir = Path(sys.argv[3])

with config_path.open(encoding="utf-8") as f:
    config = yaml.safe_load(f) or {}

sub_agents = config.get("sub-agents") or config.get("sub_agents")
if not isinstance(sub_agents, dict) or not sub_agents:
    sys.exit(f"error: no sub-agents found in {config_path}")

written = []
for role, settings in sub_agents.items():
    if not isinstance(settings, dict):
        sys.exit(f"error: sub-agents.{role} must be a mapping")

    agent_id = settings.get("sub_agent_name")
    if not agent_id:
        sys.exit(f"error: sub-agents.{role}.sub_agent_name is required")

    model = settings.get("model")
    if not model:
        sys.exit(f"error: sub-agents.{role}.model is required")

    opencode_model = settings.get("opencode_model") or settings.get("opencodeModel")
    if not opencode_model:
        sys.exit(f"error: sub-agents.{role}.opencode_model is required (provider/model)")

    reasoning = settings.get("reasoning_effort") or settings.get("reasoningEffort")
    if not reasoning:
        sys.exit(f"error: sub-agents.{role}.reasoning_effort is required")

    instruction_file = manager_prompts_dir / f"agent-{role}.md"
    if not instruction_file.is_file():
        sys.exit(f"error: instruction file missing for role {role}: {instruction_file}")

    instruction_ref = f"@./.agents/prompts/openspec-manager/{instruction_file.name}"

    lines = [
        "---",
        f"name: {agent_id}",
        f"description: I'm {agent_id} sub-agent, use me if you're working as openspec manager",
        "mode: subagent",
        f"model: {opencode_model}",
        f"reasoningEffort: {reasoning}",
        "---",
        "",
        f"<!-- openspec-role: {role}; openspec-agent: {agent_id} -->",
        "<!-- Generated by .agents/prompts/openspec-manager/sync-opencode-agents.sh; edit openspec-manager/config.yaml and re-run. -->",
        "",
        f"Read `{instruction_ref}` first and follow it.",
        "",
    ]

    out_path = agents_dir / f"{agent_id}.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    written.append(out_path)

for path in sorted(written):
    print(path)
PY
)

echo "Synced ${#written[@]} OpenCode agents into $AGENTS_DIR"
for path in "${written[@]}"; do
  echo "  $path"
done
